// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for nav.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const navBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/nav.bridge.ts
  (function() {
    function classify(href) {
      var h = (href || "").trim();
      if (!h) return null;
      var lower = h.toLowerCase();
      if (lower.charAt(0) === "#") return null;
      if (lower.indexOf("javascript:") === 0) return null;
      if (lower.indexOf("mailto:") === 0 || lower.indexOf("tel:") === 0) {
        return { external: true, href: h };
      }
      if (/^https?:\\/\\//i.test(h) || /^\\/\\//.test(h)) {
        return { external: true, href: h };
      }
      var screen = h.replace(/^\\.?\\//, "").split(/[?#]/)[0];
      return { external: false, href: h, screen };
    }
    document.addEventListener(
      "click",
      function(e) {
        var t = e.target;
        if (!t || !t.closest) return;
        var a = t.closest("a[href], [data-screen]");
        if (!a) return;
        if (e.metaKey || e.ctrlKey || e.shiftKey || e.button !== 0) return;
        var ds = a.getAttribute && a.getAttribute("data-screen");
        if (!ds) {
          var rawHref = a.getAttribute("href");
          if (rawHref != null) {
            var hh = rawHref.trim();
            if (hh === "" || hh.charAt(0) === "#") {
              e.preventDefault();
              var fid = hh.charAt(0) === "#" ? hh.slice(1) : "";
              var tgt = fid ? document.getElementById(fid) : null;
              if (tgt && tgt.scrollIntoView) {
                tgt.scrollIntoView({ behavior: "smooth", block: "start" });
              } else {
                window.scrollTo({ top: 0, behavior: "smooth" });
              }
              return;
            }
          }
        }
        var info = ds ? {
          external: false,
          href: ds,
          screen: ds.replace(/^\\.?\\//, "").split(/[?#]/)[0]
        } : classify(a.getAttribute("href") || "");
        if (!info) return;
        if (info.external) {
          try {
            a.setAttribute("target", "_blank");
            a.setAttribute("rel", "noopener noreferrer");
          } catch (_err) {
          }
          return;
        }
        e.preventDefault();
        try {
          window.parent.postMessage(
            {
              type: "prototype-navigate",
              href: info.href,
              screen: info.screen || ""
            },
            "*"
          );
        } catch (_err) {
        }
      },
      true
    );
    document.addEventListener(
      "submit",
      function(e) {
        var f = e.target;
        if (!f || f.tagName !== "FORM") return;
        var action = f.getAttribute("action") || "";
        if (/^https?:\\/\\//i.test(action)) return;
        e.preventDefault();
      },
      true
    );
  })();
})();
`;
