// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for source-location.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const sourceLocationBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/source-location.bridge.ts
  (function() {
    var FIBER_KEY_PREFIXES = [
      "__reactFiber$",
      "__reactInternalInstance$",
      "__reactInternalFiberCurrent$",
      "__reactInternalFiber$"
    ];
    var NOISE_SEGMENTS = {
      node_modules: true,
      dist: true,
      build: true,
      ".next": true,
      public: true,
      ".vite": true
    };
    var REACT_RUNTIME_MODULE_RE = /^(?:react|(?:react[-_])?jsx(?:-dev)?-runtime)(?:\\.development|\\.production(?:\\.min)?)?\\.(?:m?js|cjs)$/;
    var VITE_DEPS_SEGMENT_RE = /^deps(?:_|$)/;
    function isNoisePath(path, localServedOutput) {
      var segments = path.split("/");
      for (var i = 0; i < segments.length - 1; i += 1) {
        if (VITE_DEPS_SEGMENT_RE.test(segments[i]) && REACT_RUNTIME_MODULE_RE.test(segments[i + 1])) {
          return true;
        }
      }
      for (var i = 0; i < segments.length; i += 1) {
        var segment = segments[i];
        if (localServedOutput && (segment === "dist" || segment === "build")) {
          continue;
        }
        if (NOISE_SEGMENTS[segment]) return true;
        if (segment === "_next" && segments[i + 1] === "static") return true;
      }
      return false;
    }
    function resolveFrameUrl(rawUrl) {
      if (rawUrl.indexOf("webpack-internal:///") === 0) {
        var wPath = rawUrl.slice("webpack-internal:///".length).replace(/^\\.\\//, "");
        return wPath ? { sourceFile: wPath, localServedOutput: false } : null;
      }
      try {
        var url = new URL(rawUrl);
        var path = decodeURIComponent(url.pathname);
        var localServedOutput = path.indexOf("/@fs/") === 0;
        if (path.indexOf("/@fs/") === 0) {
          path = path.slice("/@fs".length);
        } else if (url.protocol !== "file:") {
          path = path.replace(/^\\/+/, "");
        }
        return path ? { sourceFile: path, localServedOutput } : null;
      } catch (_err) {
        return null;
      }
    }
    var STACK_FRAME_RE = /^\\s*at\\s+(?:([^\\s(]+)\\s+\\()?([^()\\s][^()]*?):(\\d+):(\\d+)\\)?\\s*$/;
    function parseStackFrame(line) {
      var match = STACK_FRAME_RE.exec(line);
      if (!match) return null;
      var functionName = match[1];
      var rawUrl = match[2];
      var resolved = resolveFrameUrl(rawUrl);
      if (!resolved) return null;
      if (isNoisePath(resolved.sourceFile, resolved.localServedOutput)) {
        return null;
      }
      var lineNumber = Number(match[3]);
      var column = Number(match[4]);
      if (!isFinite(lineNumber) || !isFinite(column)) return null;
      return {
        sourceFile: resolved.sourceFile,
        line: lineNumber,
        column,
        functionName: functionName || void 0
      };
    }
    function extractFromDebugStack(stack) {
      var lines = stack.split("\\n");
      for (var i = 0; i < lines.length; i += 1) {
        var parsed = parseStackFrame(lines[i]);
        if (parsed) return parsed;
      }
      return null;
    }
    function getFiberFromDom(node) {
      var keys = Object.keys(node);
      for (var i = 0; i < keys.length; i += 1) {
        for (var j = 0; j < FIBER_KEY_PREFIXES.length; j += 1) {
          if (keys[i].indexOf(FIBER_KEY_PREFIXES[j]) === 0) {
            return node[keys[i]];
          }
        }
      }
      return null;
    }
    function debugSourceOf(fiber) {
      var source = fiber._debugSource || fiber._debugInfo && fiber._debugInfo.source || fiber.stateNode && fiber.stateNode._debugSource || fiber.elementType && fiber.elementType._debugSource;
      if (source && source.fileName) {
        return {
          sourceFile: source.fileName,
          line: source.lineNumber,
          column: source.columnNumber
        };
      }
      var stack = fiber._debugStack && fiber._debugStack.stack || fiber._debugInfo && fiber._debugInfo.stack || fiber.stateNode && fiber.stateNode._debugStack && fiber.stateNode._debugStack.stack;
      if (stack) {
        var parsed = extractFromDebugStack(String(stack));
        if (parsed) {
          return {
            sourceFile: parsed.sourceFile,
            line: parsed.line,
            column: parsed.column
          };
        }
      }
      return null;
    }
    function hasStructuredDebugSource(fiber) {
      return !!(fiber._debugSource || fiber._debugInfo && fiber._debugInfo.source || fiber.stateNode && fiber.stateNode._debugSource || fiber.elementType && fiber.elementType._debugSource);
    }
    function isComponentFiber(fiber) {
      return typeof fiber.type === "function";
    }
    function componentNameOf(fiber) {
      var type = fiber.type;
      return type && (type.displayName || type.name) || void 0;
    }
    function resolveFromDataAttributes(el) {
      var sourceFile = el.getAttribute("data-source-file");
      var lineAttr = el.getAttribute("data-source-line");
      var columnAttr = el.getAttribute("data-source-column");
      var component = el.getAttribute("data-component-name");
      var dataLoc = el.getAttribute("data-loc");
      if (!sourceFile && dataLoc) {
        var lastColon = dataLoc.lastIndexOf(":");
        var lastPart = lastColon >= 0 ? dataLoc.slice(lastColon + 1) : "";
        if (lastColon >= 0 && /^\\d+$/.test(lastPart)) {
          var before = dataLoc.slice(0, lastColon);
          var prevColon = before.lastIndexOf(":");
          var prevPart = prevColon >= 0 ? before.slice(prevColon + 1) : "";
          var hasColumn = /^\\d+$/.test(prevPart);
          sourceFile = hasColumn ? before.slice(0, prevColon) : before;
          lineAttr = hasColumn ? prevPart : lastPart;
          columnAttr = hasColumn ? lastPart : columnAttr;
        }
      }
      if (!sourceFile || !lineAttr) return null;
      var line = Number(lineAttr);
      if (!isFinite(line)) return null;
      var column = columnAttr ? Number(columnAttr) : void 0;
      return {
        status: "resolved",
        framework: "html",
        method: "data-attribute",
        sourceFile,
        line,
        column: isFinite(column) ? column : void 0,
        componentName: component || void 0
      };
    }
    function resolveFromFiber(el) {
      var leafFiber = getFiberFromDom(el);
      if (!leafFiber) return { status: "unavailable", reason: "not-framework" };
      var elementSource = debugSourceOf(leafFiber);
      var elementMethod = elementSource ? hasStructuredDebugSource(leafFiber) ? "debug-source" : "debug-stack" : null;
      var componentFiber = null;
      var current = leafFiber.return || leafFiber.parent || leafFiber._debugOwner || null;
      var depth = 0;
      while (current && depth < 12) {
        if (!componentFiber && isComponentFiber(current)) {
          componentFiber = current;
        }
        if (componentFiber) break;
        current = current.return || current.parent || current._debugOwner;
        depth += 1;
      }
      if (!elementSource || !elementMethod) {
        return { status: "unavailable", reason: "no-debug-info" };
      }
      var result = {
        status: "resolved",
        framework: "react",
        method: elementMethod,
        sourceFile: elementSource.sourceFile,
        line: elementSource.line,
        column: elementSource.column
      };
      if (componentFiber) {
        result.componentName = componentNameOf(componentFiber);
        var ownerSource = debugSourceOf(componentFiber);
        if (ownerSource) {
          result.ownerSourceFile = ownerSource.sourceFile;
          result.ownerLine = ownerSource.line;
          result.ownerColumn = ownerSource.column;
          result.ownerComponentName = result.componentName;
          result.ownerMethod = hasStructuredDebugSource(componentFiber) ? "debug-source" : "debug-stack";
        }
        if (typeof componentFiber.key === "string" && componentFiber.key) {
          result.ownerKey = componentFiber.key;
        }
      }
      return result;
    }
    function parseFrameworkDataLoc(value) {
      var lastColon = value.lastIndexOf(":");
      if (lastColon < 0) return null;
      var lastPart = value.slice(lastColon + 1);
      if (!/^\\d+$/.test(lastPart)) return null;
      var beforeLast = value.slice(0, lastColon);
      var previousColon = beforeLast.lastIndexOf(":");
      var previousPart = previousColon >= 0 ? beforeLast.slice(previousColon + 1) : "";
      var hasColumn = /^\\d+$/.test(previousPart);
      var sourceFile = (hasColumn ? beforeLast.slice(0, previousColon) : beforeLast).trim();
      var line = Number(hasColumn ? previousPart : lastPart);
      var column = hasColumn ? Number(lastPart) : void 0;
      if (!sourceFile || !isFinite(line)) return null;
      if (column !== void 0 && !isFinite(column)) return null;
      return { sourceFile, line, column };
    }
    function resolveFromVue(el) {
      var node = el;
      var sawVue = false;
      for (var depth = 0; node && depth < 8; depth += 1) {
        var vnode = node.__vnode;
        var component = node.__vueParentComponent;
        if (vnode || component) sawVue = true;
        var inspector = vnode && vnode.props && typeof vnode.props.__v_inspector === "string" ? vnode.props.__v_inspector : null;
        if (inspector) {
          var parsed = parseFrameworkDataLoc(inspector);
          if (parsed) {
            var type = component && component.type || vnode && vnode.type;
            return {
              status: "resolved",
              framework: "vue",
              method: "vue-inspector",
              sourceFile: parsed.sourceFile,
              line: parsed.line,
              column: parsed.column,
              componentName: type && (type.name || type.__name || type.displayName)
            };
          }
        }
        node = node.parentElement;
      }
      return sawVue ? { status: "unavailable", reason: "no-debug-info" } : null;
    }
    function resolveFromSvelte(el) {
      var node = el;
      var sawSvelte = false;
      for (var depth = 0; node && depth < 8; depth += 1) {
        var meta = node.__svelte_meta;
        if (meta) sawSvelte = true;
        var loc = meta && meta.loc;
        var sourceFile = loc && (loc.file || loc.filename);
        var line = loc && Number(loc.line);
        var column = loc && Number(loc.column);
        if (sourceFile && isFinite(line)) {
          return {
            status: "resolved",
            framework: "svelte",
            method: "svelte-meta",
            sourceFile: String(sourceFile),
            line,
            column: isFinite(column) ? column : void 0,
            componentName: typeof meta.component === "string" ? meta.component : typeof meta.name === "string" ? meta.name : void 0
          };
        }
        node = node.parentElement;
      }
      return sawSvelte ? { status: "unavailable", reason: "no-debug-info" } : null;
    }
    function resolveFromFramework(el) {
      var react = resolveFromFiber(el);
      if (react.status === "resolved" || react.reason === "no-debug-info") {
        return react;
      }
      var vue = resolveFromVue(el);
      if (vue) return vue;
      var svelte = resolveFromSvelte(el);
      if (svelte) return svelte;
      return { status: "unavailable", reason: "not-framework" };
    }
    function resolveSourceLocation(el) {
      var fromAttributes = resolveFromDataAttributes(el);
      if (!fromAttributes) return resolveFromFramework(el);
      var fromFiber = resolveFromFiber(el);
      if (fromAttributes.status === "resolved" && fromFiber.status === "resolved") {
        if (fromFiber.ownerSourceFile) {
          fromAttributes.ownerSourceFile = fromFiber.ownerSourceFile;
          fromAttributes.ownerLine = fromFiber.ownerLine;
          fromAttributes.ownerColumn = fromFiber.ownerColumn;
          fromAttributes.ownerComponentName = fromFiber.ownerComponentName;
          fromAttributes.ownerMethod = fromFiber.ownerMethod;
        }
        if (fromFiber.ownerKey) fromAttributes.ownerKey = fromFiber.ownerKey;
        if (!fromAttributes.componentName) {
          fromAttributes.componentName = fromFiber.componentName;
        }
        fromAttributes.framework = fromFiber.framework;
      }
      return fromAttributes;
    }
    function findTarget(nodeId, selector) {
      if (nodeId) {
        var byId = document.querySelector(
          '[data-agent-native-node-id="' + nodeId.replace(/"/g, '\\\\"') + '"]'
        );
        if (byId) return byId;
      }
      if (selector) {
        try {
          return document.querySelector(selector);
        } catch (_err) {
          return null;
        }
      }
      return null;
    }
    window.addEventListener("message", function(e) {
      if (e.source !== window.parent) return;
      if (!e.data || e.data.type !== "agent-native:source-location-request")
        return;
      var correlationId = e.data.correlationId || "";
      var target = findTarget(e.data.nodeId, e.data.selector);
      var result = target ? resolveSourceLocation(target) : { status: "unavailable", reason: "element-not-found" };
      try {
        window.parent.postMessage(
          {
            type: "agent-native:source-location-result",
            correlationId,
            result
          },
          "*"
        );
      } catch (_err) {
      }
    });
  })();
})();
`;
