// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for zoom.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const zoomBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/zoom.bridge.ts
  (function() {
    var target = document.documentElement || document.body || document;
    function onWheel(e) {
      if (!(e.ctrlKey || e.metaKey)) return;
      if (e.cancelable) e.preventDefault();
      try {
        window.parent.postMessage(
          {
            type: "pinch-zoom-wheel",
            deltaY: e.deltaY,
            clientX: e.clientX,
            clientY: e.clientY,
            deltaMode: e.deltaMode,
            ctrlKey: !!e.ctrlKey,
            metaKey: !!e.metaKey
          },
          "*"
        );
      } catch (_err) {
      }
    }
    target.addEventListener("wheel", onWheel, {
      passive: false,
      capture: true
    });
  })();
})();
`;
