export default {
  a: () => import("./tabler-chunks/a.js"),
  b: () => import("./tabler-chunks/b.js"),
  c: () => import("./tabler-chunks/c.js"),
  d: () => import("./tabler-chunks/d.js"),
  e: () => import("./tabler-chunks/e.js"),
  f: () => import("./tabler-chunks/f.js"),
  g: () => import("./tabler-chunks/g.js"),
  h: () => import("./tabler-chunks/h.js"),
  i: () => import("./tabler-chunks/i.js"),
  j: () => import("./tabler-chunks/j.js"),
  k: () => import("./tabler-chunks/k.js"),
  l: () => import("./tabler-chunks/l.js"),
  m: () => import("./tabler-chunks/m.js"),
  n: () => import("./tabler-chunks/n.js"),
  o: () => import("./tabler-chunks/o.js"),
  p: () => import("./tabler-chunks/p.js"),
  q: () => import("./tabler-chunks/q.js"),
  r: () => import("./tabler-chunks/r.js"),
  s: () => import("./tabler-chunks/s.js"),
  t: () => import("./tabler-chunks/t.js"),
  u: () => import("./tabler-chunks/u.js"),
  v: () => import("./tabler-chunks/v.js"),
  w: () => import("./tabler-chunks/w.js"),
  x: () => import("./tabler-chunks/x.js"),
  y: () => import("./tabler-chunks/y.js"),
  z: () => import("./tabler-chunks/z.js"),
};
