import {
  IconJacket,
  IconJetpack,
  IconJetpackFilled,
  IconJetski,
  IconJewishStar,
  IconJewishStarFilled,
  IconJoinBevel,
  IconJoinRound,
  IconJoinStraight,
  IconJoker,
  IconJpg,
  IconJson,
  IconJumpRope,
} from "@tabler/icons-react";
export default {
  IconJacket,
  IconJetpack,
  IconJetpackFilled,
  IconJetski,
  IconJewishStar,
  IconJewishStarFilled,
  IconJoinBevel,
  IconJoinRound,
  IconJoinStraight,
  IconJoker,
  IconJpg,
  IconJson,
  IconJumpRope,
};
