import {
  DEFAULT_LOCALE,
  resolveLocaleFromCandidates,
  type LocaleCode,
} from "../localization/shared.js";

export const AUTH_SIGNUP_INVITE_ONLY_CODE = "INVITE_ONLY";

export interface NativeAuthCopy {
  googleButton: string;
  ssoButton: string;
  ssoEmailPlaceholder: string;
  ssoFailed: string;
  dividerOr: string;
  welcomeTitle: string;
  welcomeToApp: string;
  welcomeSubtitle: string;
  email: string;
  emailPlaceholder: string;
  legalPrefix: string;
  legalTerms: string;
  legalConnector: string;
  legalPrivacy: string;
  legalSuffix: string;
  password: string;
  confirmPassword: string;
  enterPasswordPlaceholder: string;
  forgotPassword: string;
  sendMagicLink: string;
  magicLinkSent: string;
  magicLinkSentCopy: string;
  magicLinkFailed: string;
  signupInviteOnly: string;
  usePasswordInstead: string;
  backToMagicLink: string;
  signIn: string;
  back: string;
  close: string;
  sending: string;
  signingIn: string;
  invalidEmail: string;
  invalidLogin: string;
  failedToConnect: string;
  googleNeverFinished: string;
  checking: string;
  twoFactorTitle: string;
  twoFactorSubtitle: string;
  twoFactorCodeLabel: string;
  twoFactorCodePlaceholder: string;
  twoFactorVerify: string;
  twoFactorVerifying: string;
  twoFactorInvalid: string;
  twoFactorBack: string;
}

const TWO_FACTOR_COPY = {
  twoFactorTitle: "Two-step verification",
  twoFactorSubtitle: "Enter the six-digit code from your authenticator app.",
  twoFactorCodeLabel: "Authentication code",
  twoFactorCodePlaceholder: "000000",
  twoFactorVerify: "Verify code",
  twoFactorVerifying: "Verifying...",
  twoFactorInvalid: "That code is invalid or expired. Try again.",
  twoFactorBack: "Back to sign in",
} as const;

export const NATIVE_AUTH_COPY: Record<LocaleCode, NativeAuthCopy> = {
  "en-US": {
    ...TWO_FACTOR_COPY,
    googleButton: "Sign in with Google",
    ssoButton: "Continue with SSO",
    ssoEmailPlaceholder: "Work email",
    ssoFailed: "No SSO provider was found for that email.",
    dividerOr: "or",
    welcomeTitle: "Welcome",
    welcomeToApp: "Welcome to {appName}",
    welcomeSubtitle: "Sign in or create your account",
    email: "Email",
    emailPlaceholder: "you@example.com",
    legalPrefix: "By signing up, you accept our",
    legalTerms: "Terms",
    legalConnector: "and",
    legalPrivacy: "Privacy Policy",
    legalSuffix: ".",
    password: "Password",
    confirmPassword: "Confirm password",
    enterPasswordPlaceholder: "Enter password",
    forgotPassword: "Forgot password?",
    sendMagicLink: "Continue with email",
    magicLinkSent: "Check your email",
    magicLinkSentCopy: "We sent a secure sign-in link to",
    magicLinkFailed:
      "We couldn't send a sign-in link. Check your email and try again.",
    signupInviteOnly:
      "This workspace is invite-only. Ask an administrator for an invitation.",
    usePasswordInstead: "Use a password instead",
    backToMagicLink: "Use a sign-in link instead",
    signIn: "Sign in",
    back: "Back",
    close: "Close",
    sending: "Sending...",
    signingIn: "Signing in…",
    invalidEmail: "Enter a valid email address, like you@example.com.",
    invalidLogin: "The email or password is incorrect.",
    failedToConnect: "We couldn't connect. Please try again.",
    googleNeverFinished:
      "Unable to sign in with Google right now. Please try again or use another sign-in method.",
    checking: "Checking...",
  },
  "zh-CN": {
    ...TWO_FACTOR_COPY,
    googleButton: "使用 Google 登录",
    ssoButton: "使用 SSO 继续",
    ssoEmailPlaceholder: "工作邮箱",
    ssoFailed: "未找到该邮箱对应的 SSO 提供商。",
    dividerOr: "或",
    welcomeTitle: "欢迎",
    welcomeToApp: "欢迎使用 {appName}",
    welcomeSubtitle: "继续以登录或创建账户",
    email: "电子邮箱",
    emailPlaceholder: "you@example.com",
    legalPrefix: "注册即表示你接受我们的",
    legalTerms: "条款",
    legalConnector: "和",
    legalPrivacy: "隐私政策",
    legalSuffix: "。",
    password: "密码",
    confirmPassword: "确认密码",
    enterPasswordPlaceholder: "输入密码",
    forgotPassword: "忘记密码？",
    sendMagicLink: "使用邮箱继续",
    magicLinkSent: "检查你的邮箱",
    magicLinkSentCopy: "我们已向以下邮箱发送安全登录链接：",
    magicLinkFailed: "无法发送登录链接。",
    signupInviteOnly: "此工作区仅限受邀用户访问。请联系管理员获取邀请。",
    usePasswordInstead: "改用密码",
    backToMagicLink: "改用登录链接",
    signIn: "登录",
    back: "返回",
    close: "关闭",
    sending: "正在发送...",
    signingIn: "正在登录…",
    invalidEmail: "请输入有效邮箱地址，例如 you@example.com。",
    invalidLogin: "邮箱或密码无效",
    failedToConnect: "连接失败。请重试。",
    googleNeverFinished:
      "暂时无法使用 Google 登录。请重试，或使用其他登录方式。",
    checking: "正在检查...",
  },
  "zh-TW": {
    ...TWO_FACTOR_COPY,
    googleButton: "使用 Google 登入",
    ssoButton: "使用 SSO 繼續",
    ssoEmailPlaceholder: "工作電子郵件",
    ssoFailed: "找不到該電子郵件對應的 SSO 提供者。",
    dividerOr: "或",
    welcomeTitle: "歡迎",
    welcomeToApp: "歡迎使用 {appName}",
    welcomeSubtitle: "繼續以登入或建立帳戶",
    email: "電子郵件",
    emailPlaceholder: "you@example.com",
    legalPrefix: "註冊即表示你接受我們的",
    legalTerms: "條款",
    legalConnector: "和",
    legalPrivacy: "隱私權政策",
    legalSuffix: "。",
    password: "密碼",
    confirmPassword: "確認密碼",
    enterPasswordPlaceholder: "輸入密碼",
    forgotPassword: "忘記密碼？",
    sendMagicLink: "使用電子郵件繼續",
    magicLinkSent: "檢查你的電子郵件",
    magicLinkSentCopy: "我們已向以下電子郵件寄送安全登入連結：",
    magicLinkFailed: "無法寄送登入連結。",
    signupInviteOnly: "此工作區僅限受邀使用者存取。請聯絡管理員取得邀請。",
    usePasswordInstead: "改用密碼",
    backToMagicLink: "改用登入連結",
    signIn: "登入",
    back: "返回",
    close: "關閉",
    sending: "正在寄送...",
    signingIn: "正在登入...",
    invalidEmail: "請輸入有效的電子郵件地址，例如 you@example.com。",
    invalidLogin: "電子郵件或密碼無效",
    failedToConnect: "連線失敗。請重試。",
    googleNeverFinished:
      "目前無法使用 Google 登入。請再試一次，或改用其他登入方式。",
    checking: "正在檢查...",
  },
  "es-ES": {
    ...TWO_FACTOR_COPY,
    googleButton: "Iniciar sesión con Google",
    ssoButton: "Continuar con SSO",
    ssoEmailPlaceholder: "Correo de trabajo",
    ssoFailed: "No se encontró un proveedor SSO para ese correo.",
    dividerOr: "o",
    welcomeTitle: "Bienvenido",
    welcomeToApp: "Bienvenido a {appName}",
    welcomeSubtitle: "Continúa para iniciar sesión o crear tu cuenta",
    email: "Email",
    emailPlaceholder: "you@example.com",
    legalPrefix: "Al registrarte, aceptas nuestros",
    legalTerms: "Términos",
    legalConnector: "y",
    legalPrivacy: "Política de privacidad",
    legalSuffix: ".",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    enterPasswordPlaceholder: "Introduce la contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    sendMagicLink: "Continuar con email",
    magicLinkSent: "Revisa tu email",
    magicLinkSentCopy: "Enviamos un enlace seguro a",
    magicLinkFailed: "No se pudo enviar el enlace de inicio de sesión.",
    signupInviteOnly:
      "Este espacio de trabajo es solo por invitación. Pide una invitación a un administrador.",
    usePasswordInstead: "Usar una contraseña",
    backToMagicLink: "Usar un enlace de inicio de sesión",
    signIn: "Iniciar sesión",
    back: "Volver",
    close: "Cerrar",
    sending: "Enviando...",
    signingIn: "Iniciando sesión…",
    invalidEmail: "Introduce un email válido, como you@example.com.",
    invalidLogin: "Email o contraseña no válidos",
    failedToConnect: "No se pudo conectar. Inténtalo de nuevo.",
    googleNeverFinished:
      "No se pudo iniciar sesión con Google. Inténtalo de nuevo o usa otro método de inicio de sesión.",
    checking: "Comprobando...",
  },
  "fr-FR": {
    ...TWO_FACTOR_COPY,
    googleButton: "Se connecter avec Google",
    ssoButton: "Continuer avec SSO",
    ssoEmailPlaceholder: "E-mail professionnel",
    ssoFailed: "Aucun fournisseur SSO n'a été trouvé pour cet e-mail.",
    dividerOr: "ou",
    welcomeTitle: "Bienvenue",
    welcomeToApp: "Bienvenue sur {appName}",
    welcomeSubtitle: "Continuez pour vous connecter ou créer votre compte",
    email: "E-mail",
    emailPlaceholder: "you@example.com",
    legalPrefix: "En vous inscrivant, vous acceptez nos",
    legalTerms: "Conditions",
    legalConnector: "et",
    legalPrivacy: "Politique de confidentialité",
    legalSuffix: ".",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    enterPasswordPlaceholder: "Saisir le mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    sendMagicLink: "Continuer avec l’e-mail",
    magicLinkSent: "Vérifiez votre e-mail",
    magicLinkSentCopy: "Nous avons envoyé un lien sécurisé à",
    magicLinkFailed: "Impossible d'envoyer le lien de connexion.",
    signupInviteOnly:
      "Cet espace de travail est accessible uniquement sur invitation. Demandez une invitation à un administrateur.",
    usePasswordInstead: "Utiliser un mot de passe",
    backToMagicLink: "Utiliser un lien de connexion",
    signIn: "Connexion",
    back: "Retour",
    close: "Fermer",
    sending: "Envoi...",
    signingIn: "Connexion…",
    invalidEmail: "Saisissez une adresse e-mail valide, comme you@example.com.",
    invalidLogin: "E-mail ou mot de passe invalide",
    failedToConnect: "Connexion impossible. Veuillez réessayer.",
    googleNeverFinished:
      "Impossible de vous connecter avec Google pour le moment. Réessayez ou utilisez une autre méthode de connexion.",
    checking: "Vérification...",
  },
  "de-DE": {
    ...TWO_FACTOR_COPY,
    googleButton: "Mit Google anmelden",
    ssoButton: "Mit SSO fortfahren",
    ssoEmailPlaceholder: "Arbeits-E-Mail",
    ssoFailed: "Für diese E-Mail wurde kein SSO-Anbieter gefunden.",
    dividerOr: "oder",
    welcomeTitle: "Willkommen",
    welcomeToApp: "Willkommen bei {appName}",
    welcomeSubtitle:
      "Fahre fort, um dich anzumelden oder ein Konto zu erstellen",
    email: "E-Mail",
    emailPlaceholder: "you@example.com",
    legalPrefix: "Mit der Registrierung akzeptierst du unsere",
    legalTerms: "Bedingungen",
    legalConnector: "und",
    legalPrivacy: "Datenschutzrichtlinie",
    legalSuffix: ".",
    password: "Passwort",
    confirmPassword: "Passwort bestätigen",
    enterPasswordPlaceholder: "Passwort eingeben",
    forgotPassword: "Passwort vergessen?",
    sendMagicLink: "Mit E-Mail fortfahren",
    magicLinkSent: "Prüfe deine E-Mail",
    magicLinkSentCopy: "Wir haben einen sicheren Anmeldelink gesendet an",
    magicLinkFailed: "Anmeldelink konnte nicht gesendet werden.",
    signupInviteOnly:
      "Dieser Arbeitsbereich ist nur auf Einladung zugänglich. Bitte einen Administrator um eine Einladung.",
    usePasswordInstead: "Stattdessen Passwort verwenden",
    backToMagicLink: "Stattdessen Anmeldelink verwenden",
    signIn: "Anmelden",
    back: "Zurück",
    close: "Schließen",
    sending: "Senden...",
    signingIn: "Anmeldung…",
    invalidEmail: "Gib eine gültige E-Mail-Adresse ein, z. B. you@example.com.",
    invalidLogin: "E-Mail oder Passwort ungültig",
    failedToConnect: "Verbindung fehlgeschlagen. Bitte erneut versuchen.",
    googleNeverFinished:
      "Die Anmeldung mit Google ist gerade nicht möglich. Bitte versuche es erneut oder nutze eine andere Anmeldemethode.",
    checking: "Prüfen...",
  },
  "ja-JP": {
    ...TWO_FACTOR_COPY,
    googleButton: "Google でサインイン",
    ssoButton: "SSO で続行",
    ssoEmailPlaceholder: "仕事用メールアドレス",
    ssoFailed:
      "このメールアドレスに対応する SSO プロバイダーが見つかりません。",
    dividerOr: "または",
    welcomeTitle: "ようこそ",
    welcomeToApp: "{appName}へようこそ",
    welcomeSubtitle: "続けてサインインするか、アカウントを作成します",
    email: "メール",
    emailPlaceholder: "you@example.com",
    legalPrefix: "登録すると、以下に同意したものとみなされます:",
    legalTerms: "利用規約",
    legalConnector: "および",
    legalPrivacy: "プライバシーポリシー",
    legalSuffix: "。",
    password: "パスワード",
    confirmPassword: "パスワードを確認",
    enterPasswordPlaceholder: "パスワードを入力",
    forgotPassword: "パスワードをお忘れですか？",
    sendMagicLink: "メールで続行",
    magicLinkSent: "メールを確認してください",
    magicLinkSentCopy: "安全なサインインリンクを送信しました：",
    magicLinkFailed: "サインインリンクを送信できませんでした。",
    signupInviteOnly:
      "このワークスペースは招待制です。管理者に招待を依頼してください。",
    usePasswordInstead: "パスワードを使用する",
    backToMagicLink: "サインインリンクを使用する",
    signIn: "サインイン",
    back: "戻る",
    close: "閉じる",
    sending: "送信中...",
    signingIn: "サインイン中…",
    invalidEmail:
      "you@example.com のような有効なメールアドレスを入力してください。",
    invalidLogin: "メールまたはパスワードが正しくありません",
    failedToConnect: "接続できませんでした。もう一度お試しください。",
    googleNeverFinished:
      "現在 Google でログインできません。もう一度お試しいただくか、別の方法でログインしてください。",
    checking: "確認中...",
  },
  "ko-KR": {
    ...TWO_FACTOR_COPY,
    googleButton: "Google로 로그인",
    ssoButton: "SSO로 계속",
    ssoEmailPlaceholder: "회사 이메일",
    ssoFailed: "해당 이메일에 대한 SSO 제공업체를 찾을 수 없습니다.",
    dividerOr: "또는",
    welcomeTitle: "환영합니다",
    welcomeToApp: "{appName}에 오신 것을 환영합니다",
    welcomeSubtitle: "계속해서 로그인하거나 계정을 만드세요",
    email: "이메일",
    emailPlaceholder: "you@example.com",
    legalPrefix: "가입하면 다음에 동의하게 됩니다:",
    legalTerms: "약관",
    legalConnector: "및",
    legalPrivacy: "개인정보 처리방침",
    legalSuffix: ".",
    password: "비밀번호",
    confirmPassword: "비밀번호 확인",
    enterPasswordPlaceholder: "비밀번호 입력",
    forgotPassword: "비밀번호를 잊으셨나요?",
    sendMagicLink: "이메일로 계속",
    magicLinkSent: "이메일을 확인하세요",
    magicLinkSentCopy: "안전한 로그인 링크를 보냈습니다:",
    magicLinkFailed: "로그인 링크를 보낼 수 없습니다.",
    signupInviteOnly:
      "이 워크스페이스는 초대받은 사용자만 이용할 수 있습니다. 관리자에게 초대를 요청하세요.",
    usePasswordInstead: "비밀번호 사용",
    backToMagicLink: "로그인 링크 사용",
    signIn: "로그인",
    back: "뒤로",
    close: "닫기",
    sending: "보내는 중...",
    signingIn: "로그인 중…",
    invalidEmail: "you@example.com 같은 올바른 이메일 주소를 입력하세요.",
    invalidLogin: "이메일 또는 비밀번호가 올바르지 않습니다",
    failedToConnect: "연결하지 못했습니다. 다시 시도하세요.",
    googleNeverFinished:
      "지금은 Google로 로그인할 수 없습니다. 다시 시도하거나 다른 로그인 방법을 이용해 주세요.",
    checking: "확인 중...",
  },
  "pt-BR": {
    ...TWO_FACTOR_COPY,
    googleButton: "Entrar com Google",
    ssoButton: "Continuar com SSO",
    ssoEmailPlaceholder: "E-mail de trabalho",
    ssoFailed: "Nenhum provedor SSO foi encontrado para esse e-mail.",
    dividerOr: "ou",
    welcomeTitle: "Bem-vindo",
    welcomeToApp: "Bem-vindo ao {appName}",
    welcomeSubtitle: "Continue para entrar ou criar sua conta",
    email: "Email",
    emailPlaceholder: "you@example.com",
    legalPrefix: "Ao se cadastrar, você aceita nossos",
    legalTerms: "Termos",
    legalConnector: "e",
    legalPrivacy: "Política de Privacidade",
    legalSuffix: ".",
    password: "Senha",
    confirmPassword: "Confirmar senha",
    enterPasswordPlaceholder: "Digite a senha",
    forgotPassword: "Esqueceu a senha?",
    sendMagicLink: "Continuar com email",
    magicLinkSent: "Confira seu email",
    magicLinkSentCopy: "Enviamos um link seguro para",
    magicLinkFailed: "Não foi possível enviar o link de acesso.",
    signupInviteOnly:
      "Este espaço de trabalho é somente para convidados. Peça um convite a um administrador.",
    usePasswordInstead: "Usar uma senha",
    backToMagicLink: "Usar um link de acesso",
    signIn: "Entrar",
    back: "Voltar",
    close: "Fechar",
    sending: "Enviando...",
    signingIn: "Entrando…",
    invalidEmail: "Digite um email válido, como you@example.com.",
    invalidLogin: "Email ou senha inválidos",
    failedToConnect: "Não foi possível conectar. Tente novamente.",
    googleNeverFinished:
      "Não foi possível entrar com o Google agora. Tente novamente ou use outra forma de entrar.",
    checking: "Verificando...",
  },
  "hi-IN": {
    ...TWO_FACTOR_COPY,
    googleButton: "Google से साइन इन करें",
    ssoButton: "SSO के साथ जारी रखें",
    ssoEmailPlaceholder: "कार्य ईमेल",
    ssoFailed: "इस ईमेल के लिए कोई SSO प्रदाता नहीं मिला।",
    dividerOr: "या",
    welcomeTitle: "स्वागत है",
    welcomeToApp: "{appName} में आपका स्वागत है",
    welcomeSubtitle: "साइन इन करने या अपना खाता बनाने के लिए जारी रखें",
    email: "ईमेल",
    emailPlaceholder: "you@example.com",
    legalPrefix: "साइन अप करके, आप हमारी",
    legalTerms: "शर्तें",
    legalConnector: "और",
    legalPrivacy: "गोपनीयता नीति",
    legalSuffix: "स्वीकार करते हैं।",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    enterPasswordPlaceholder: "पासवर्ड दर्ज करें",
    forgotPassword: "पासवर्ड भूल गए?",
    sendMagicLink: "ईमेल से जारी रखें",
    magicLinkSent: "अपना ईमेल देखें",
    magicLinkSentCopy: "हमने सुरक्षित साइन-इन लिंक यहां भेजा है:",
    magicLinkFailed: "साइन-इन लिंक नहीं भेजा जा सका।",
    signupInviteOnly:
      "यह वर्कस्पेस केवल आमंत्रण से उपलब्ध है। आमंत्रण के लिए किसी व्यवस्थापक से संपर्क करें।",
    usePasswordInstead: "पासवर्ड का उपयोग करें",
    backToMagicLink: "साइन-इन लिंक का उपयोग करें",
    signIn: "साइन इन",
    back: "वापस",
    close: "बंद करें",
    sending: "भेजा जा रहा है...",
    signingIn: "साइन इन हो रहा है…",
    invalidEmail: "एक मान्य ईमेल पता दर्ज करें, जैसे you@example.com.",
    invalidLogin: "ईमेल या पासवर्ड अमान्य है",
    failedToConnect: "कनेक्ट नहीं हो सका। कृपया फिर कोशिश करें।",
    googleNeverFinished:
      "अभी Google से साइन इन नहीं हो सका। फिर से कोशिश करें या साइन इन का कोई दूसरा तरीका इस्तेमाल करें।",
    checking: "जांच हो रही है...",
  },
  "ar-SA": {
    ...TWO_FACTOR_COPY,
    googleButton: "تسجيل الدخول باستخدام Google",
    ssoButton: "المتابعة باستخدام SSO",
    ssoEmailPlaceholder: "البريد الإلكتروني للعمل",
    ssoFailed: "لم يتم العثور على موفر SSO لهذا البريد الإلكتروني.",
    dividerOr: "أو",
    welcomeTitle: "مرحبًا",
    welcomeToApp: "مرحبًا بك في {appName}",
    welcomeSubtitle: "تابع لتسجيل الدخول أو إنشاء حسابك",
    email: "البريد الإلكتروني",
    emailPlaceholder: "you@example.com",
    legalPrefix: "بالتسجيل، فإنك توافق على",
    legalTerms: "الشروط",
    legalConnector: "و",
    legalPrivacy: "سياسة الخصوصية",
    legalSuffix: ".",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    enterPasswordPlaceholder: "أدخل كلمة المرور",
    forgotPassword: "هل نسيت كلمة المرور؟",
    sendMagicLink: "المتابعة باستخدام البريد الإلكتروني",
    magicLinkSent: "تحقق من بريدك الإلكتروني",
    magicLinkSentCopy: "أرسلنا رابط تسجيل دخول آمنًا إلى",
    magicLinkFailed: "تعذر إرسال رابط تسجيل الدخول.",
    signupInviteOnly:
      "مساحة العمل هذه متاحة بالدعوة فقط. اطلب دعوة من أحد المسؤولين.",
    usePasswordInstead: "استخدام كلمة مرور بدلًا من ذلك",
    backToMagicLink: "استخدام رابط تسجيل الدخول بدلًا من ذلك",
    signIn: "تسجيل الدخول",
    back: "رجوع",
    close: "إغلاق",
    sending: "جارٍ الإرسال...",
    signingIn: "جارٍ تسجيل الدخول…",
    invalidEmail: "أدخل بريدًا إلكترونيًا صالحًا، مثل you@example.com.",
    invalidLogin: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    failedToConnect: "تعذر الاتصال. حاول مرة أخرى.",
    googleNeverFinished:
      "تعذّر تسجيل الدخول باستخدام Google الآن. يُرجى المحاولة مرة أخرى أو استخدام طريقة أخرى لتسجيل الدخول.",
    checking: "جارٍ التحقق...",
  },
};

export function resolveNativeAuthCopy(locale: unknown): NativeAuthCopy {
  const resolvedLocale = resolveLocaleFromCandidates([locale]);
  return NATIVE_AUTH_COPY[resolvedLocale] ?? NATIVE_AUTH_COPY[DEFAULT_LOCALE];
}
