export const DEFAULT_WORKSPACE_SKILLS = [
  "actions",
  "adding-a-feature",
  "agent-native-docs",
  "agent-native-toolkit",
  "context-awareness",
  "customizing-agent-native",
  "delegate-to-agent",
  "external-agents",
  "frontend-design",
  "turn-into-app",
  "turn-into-skill",
  "real-time-sync",
  "secrets",
  "security",
  "self-modifying-code",
  "shadcn-ui",
  "sharing",
  "storing-data",
  "portability",
  "workspace-conventions",
] as const;

export const FRAMEWORK_TEMPLATE_SHARED_SKILLS = [
  "actions",
  "agent-native-docs",
  "agent-native-toolkit",
  "adding-a-feature",
  "capture-learnings",
  "client-methods",
  "create-skill",
  "customizing-agent-native",
  "delegate-to-agent",
  "external-agents",
  "frontend-design",
  "feature-flags",
  "integration-webhooks",
  "internationalization",
  "onboarding",
  "performance",
  "real-time-collab",
  "real-time-sync",
  "security",
  "self-modifying-code",
  "shadcn-ui",
  "secrets",
  "storing-data",
  "sharing",
  "turn-into-app",
  "turn-into-skill",
  "upgrade-agent-native",
] as const;
