import { defineAction } from "@agent-native/core/action";
import { eq } from "drizzle-orm";
import { z } from "zod";

import { getDb, schema } from "../server/db/index.js";
import { nowIso } from "../server/lib/json.js";
import { assertCanApprove } from "../server/lib/library-access.js";
import { getAssetOrThrow, serializeLibrary } from "./_helpers.js";

export default defineAction({
  description:
    "Mark an image asset as the library's canonical logo. The logo will be composited onto generated images when the user toggles 'Use logo'. Pixel-perfect — never regenerated by the model.",
  schema: z.object({
    libraryId: z.string(),
    assetId: z.string(),
  }),
  run: async ({ libraryId, assetId }) => {
    await assertCanApprove(libraryId, "Setting the canonical logo");
    const asset = await getAssetOrThrow(assetId);
    if (asset.libraryId !== libraryId) {
      throw new Error("Asset does not belong to this library.");
    }
    const db = getDb();
    const now = nowIso();
    await db
      .update(schema.assets)
      .set({ role: "logo_reference", status: "reference", updatedAt: now })
      .where(eq(schema.assets.id, assetId));
    await db
      .update(schema.assetLibraries)
      .set({ canonicalLogoAssetId: assetId, updatedAt: now })
      .where(eq(schema.assetLibraries.id, libraryId));
    const [library] = await db
      .select()
      .from(schema.assetLibraries)
      .where(eq(schema.assetLibraries.id, libraryId))
      .limit(1);
    return {
      libraryId,
      assetId,
      library: library ? serializeLibrary(library) : null,
    };
  },
});
