import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const sourcePath = path.resolve(
  scriptDir,
  "../src/assets/branding/og-background.png",
);
const targetPath = path.resolve(
  scriptDir,
  "../src/server/og-background-data.ts",
);
const base64 = readFileSync(sourcePath).toString("base64");

writeFileSync(
  targetPath,
  `// AUTO-GENERATED by scripts/generate-og-background-data.ts - do not edit by hand.
// Embedded background for all Agent-Native OG image renderers.
// Regenerate with: node --experimental-strip-types packages/core/scripts/generate-og-background-data.ts

export const AGENT_NATIVE_OG_BACKGROUND_DATA_URL =
  "data:image/png;base64,${base64}";
`,
);

console.log(`Wrote ${targetPath}`);
