import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import {
  createPostgresScriptClient,
  type PostgresScriptClient,
} from "./postgres-client.js";

type Client = PostgresScriptClient;

async function createClient({ url }: { url: string }) {
  return createPostgresScriptClient(url);
}
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

describe("db-schema", () => {
  let dir: string;
  let dbFile: string;

  async function withClient<T>(fn: (c: Client) => Promise<T>): Promise<T> {
    const c = await createClient({ url: "pglite:" + dbFile });
    try {
      return await fn(c);
    } finally {
      await c.end();
    }
  }

  beforeEach(async () => {
    dir = await mkdtemp(path.join(os.tmpdir(), "db-schema-"));
    dbFile = path.join(dir, "app");
  });

  afterEach(async () => {
    vi.unstubAllEnvs();
    vi.resetModules();
    vi.restoreAllMocks();
    await rm(dir, { recursive: true, force: true });
  });

  async function runSchema(extra: string[]): Promise<string[]> {
    const logs: string[] = [];
    const spy = vi
      .spyOn(console, "log")
      .mockImplementation((...a: unknown[]) => {
        logs.push(a.map(String).join(" "));
      });
    try {
      const { default: dbSchema } = await import("./schema.js");
      await dbSchema(extra);
    } finally {
      spy.mockRestore();
    }
    return logs;
  }

  async function runSchemaJson(extra: string[]): Promise<any> {
    const logs = await runSchema([
      "--db",
      dbFile,
      "--format",
      "json",
      ...extra,
    ]);
    const joined = logs.join("\n");
    const start = joined.indexOf("{");
    return JSON.parse(joined.slice(start));
  }

  it("introspects columns, PK, NOT NULL, DEFAULT, FKs, and indexes (JSON)", async () => {
    await withClient(async (c) => {
      await c.unsafe(
        `CREATE TABLE authors (id TEXT PRIMARY KEY, name TEXT NOT NULL, bio TEXT DEFAULT 'none')`,
      );
      await c.unsafe(
        `CREATE TABLE posts (
           id TEXT PRIMARY KEY,
           author_id TEXT NOT NULL REFERENCES authors(id),
           title TEXT
         )`,
      );
      await c.unsafe(`CREATE UNIQUE INDEX idx_posts_title ON posts(title)`);
    });

    const out = await runSchemaJson([]);

    const tables = Object.fromEntries(out.tables.map((t: any) => [t.name, t]));
    expect(Object.keys(tables).sort()).toEqual(["authors", "posts"]);

    const authors = tables.authors;
    const cols = Object.fromEntries(
      authors.columns.map((c: any) => [c.name, c]),
    );
    expect(cols.id.pk).toBe(true);
    expect(cols.name.notnull).toBe(true);
    expect(cols.name.pk).toBe(false);
    expect(cols.bio.dflt_value).not.toBeNull();

    const posts = tables.posts;
    expect(posts.foreignKeys).toHaveLength(1);
    expect(posts.foreignKeys[0]).toMatchObject({
      from: "author_id",
      table: "authors",
      to: "id",
    });

    const titleIdx = posts.indexes.find((i: any) =>
      i.name.includes("idx_posts_title"),
    );
    expect(titleIdx).toBeDefined();
    expect(titleIdx.unique).toBe(true);
    expect(titleIdx.columns).toEqual(["title"]);
  });

  it("excludes postgres_* internal tables from introspection", async () => {
    await withClient(async (c) => {
      await c.unsafe(
        `CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v TEXT)`,
      );
      await c.unsafe(`INSERT INTO t (v) VALUES ('x')`);
    });
    const out = await runSchemaJson([]);
    const names = out.tables.map((t: any) => t.name);
    expect(names).toContain("t");
    expect(names.some((n: string) => n.startsWith("postgres_"))).toBe(false);
  });

  it("emits human-readable output with annotations when no --format is given", async () => {
    await withClient(async (c) => {
      await c.unsafe(
        `CREATE TABLE widgets (id TEXT PRIMARY KEY, label TEXT NOT NULL)`,
      );
    });
    const logs = await runSchema(["--db", dbFile]);
    const text = logs.join("\n");
    expect(text).toContain("Table: widgets");
    expect(text).toContain("PRIMARY KEY");
    expect(text).toContain("NOT NULL");
    expect(text).not.toMatch(/^\s*\{/m);
  });

  it("labels a PGlite database with its pglite URL", async () => {
    await withClient(async (c) => {
      await c.unsafe(`CREATE TABLE t (id TEXT PRIMARY KEY)`);
    });
    const out = await runSchemaJson([]);
    expect(out.database).toBe(`pglite:${dbFile}`);
  });

  it("prints help and does not touch the database", async () => {
    const logs = await runSchema(["--help"]);
    expect(logs.join("\n")).toContain("Usage: pnpm action db-schema");
  });

  it("redacts the Postgres password in the database label (never leaks the secret to tool output)", async () => {
    vi.doMock("../../db/client.js", async (importOriginal) => ({
      ...(await importOriginal<typeof import("../../db/client.js")>()),
      getDatabaseUrl: () =>
        "postgres://app_user:sup3r-secret@db.example.com:5432/appdb",
    }));
    vi.doMock("postgres", () => ({
      default: () =>
        Object.assign(
          async (strings: TemplateStringsArray) => {
            const text = strings.join(" ");
            if (text.includes("information_schema.tables")) {
              return [{ name: "notes" }];
            }
            return [];
          },
          { unsafe: async () => [], end: vi.fn() },
        ),
    }));

    const logs: string[] = [];
    const spy = vi
      .spyOn(console, "log")
      .mockImplementation((...a: unknown[]) => {
        logs.push(a.map(String).join(" "));
      });
    try {
      const { default: dbSchema } = await import("./schema.js");
      await dbSchema(["--format", "json"]);
    } finally {
      spy.mockRestore();
    }
    const joined = logs.join("\n");
    const out = JSON.parse(joined.slice(joined.indexOf("{")));

    expect(out.database).toContain("app_user:***@db.example.com");
    expect(out.database).not.toContain("sup3r-secret");
  });
});
