import type { ParityRow } from "./matrix.types";

export const parityMatrix: ParityRow[] = [
  {
    id: "sidebar.personal-recent-visits",
    surface: "sidebar",
    label:
      "Read personal Recent entries, record foreground visits, and remove an entry from Recent",
    uiEntrypoints: [
      "app/components/sidebar/PersonalSidebarSections.tsx",
      "app/hooks/use-content-recent.ts",
    ],
    durableEffect:
      "Per-user Recent stores bounded Page destinations and one destination per Database with its latest visited View, then resolves current labels and the requester's pinned state under current access. Removing an entry forgets only that visit.",
    uiImplementation:
      "Recent reads use the shared Action; successful foreground navigation records a visit through the UI-only Action; the Recent row menu removes an entry through the shared Action and pins through update-document.",
    status: "action-backed",
    actions: [
      "get-content-recent",
      "record-content-visit",
      "remove-content-recent",
    ],
    exception:
      "record-content-visit is hidden with agentTool: false so agent reads and edits cannot manufacture human visit history.",
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/content-recent.test.ts",
      "shared/content-personal-navigation.test.ts",
    ],
  },
  {
    id: "sidebar.bounded-workspace-navigation",
    surface: "sidebar",
    label:
      "Page through database-backed workspace roots and children and reveal the active path",
    uiEntrypoints: [
      "app/components/sidebar/DocumentSidebar.tsx",
      "app/components/editor/database/sidebar.tsx",
      "app/hooks/use-content-database.ts",
    ],
    durableEffect: null,
    uiImplementation:
      "Database-backed Files navigation requests at most 20 immediate children per page and uses a bounded active-item context read; local-file mode still uses the document inventory.",
    status: "action-backed",
    actions: ["get-content-navigation-context", "query-content-database-items"],
    exception:
      "Both reads are hidden with agentTool: false because they are lean UI projections, not agent capability limits; agents use list-documents, get-document, search-documents, and navigate.",
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: "Bound local-file sidebar inventory",
    coverageRefs: [
      "actions/content-navigation-bounds.test.ts",
      "actions/query-content-database-items.navigation.db.test.ts",
      "app/hooks/use-content-database.test.ts",
    ],
  },
  {
    id: "sidebar.document-tree-crud",
    surface: "sidebar",
    label:
      "Create, rename, duplicate, delete, move, favorite, list, search, and open pages",
    uiEntrypoints: [
      "app/components/sidebar/DocumentSidebar.tsx",
      "app/components/sidebar/DocumentTreeItem.tsx",
      "app/components/sidebar/SidebarRowActions.tsx",
      "app/components/sidebar/MovePageDialog.tsx",
      "app/components/editor/DocumentToolbar.tsx",
      "app/hooks/use-documents.ts",
    ],
    durableEffect:
      "Document tree rows and document metadata are created, updated, deleted, moved, searched, or read.",
    uiImplementation:
      "Sidebar and hooks call document actions with optimistic cache updates for visible responsiveness; failed slash insertions roll back only an unchanged resource created by the caller; the shared sidebar row menu renames, duplicates a page with its sub-pages beside the original, moves within or between spaces (warning that access changes first), trashes, and reads last-edit activity through the same Actions.",
    status: "action-backed",
    actions: [
      "create-document",
      "clone-creative-context-document",
      "delete-document",
      "duplicate-page",
      "get-document",
      "get-document-activity",
      "list-trashed-documents",
      "list-documents",
      "move-document",
      "permanently-delete-document",
      "restore-document",
      "rollback-created-slash-document",
      "search-documents",
      "update-document",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/content-database-lifecycle.db.test.ts",
      "actions/database-setup.db.test.ts",
      "actions/database-setup-mcp.db.test.ts",
      "actions/_local-file-documents.test.ts",
      "actions/rollback-created-slash-document.test.ts",
    ],
    evalScenarioIds: ["document-search-edit"],
  },
  {
    id: "trash.search-preview-and-purge",
    surface: "sidebar",
    label:
      "Search root and nested Trash, preview Page bodies, restore or delete loaded items, and empty an explicit space scope with durable progress",
    uiEntrypoints: [
      "app/routes/_app.trash.tsx",
      "app/components/trash/TrashBrowser.tsx",
      "app/components/trash/EmptyTrashDialog.tsx",
      "app/hooks/use-content-trash.ts",
    ],
    durableEffect:
      "Authorized Trash metadata and Page bodies are read; reviewed purge plans, operations, and item outcomes are persisted before bounded permanent deletion runs.",
    uiImplementation:
      "The dedicated Trash route calls the same list, preview, restore, permanent-delete, purge-plan, purge-plan-detail, purge-execute, and operation-progress actions available to agents. Selection supports loaded rows or a server-backed matching scope; Empty Trash uses scope mode and intentionally ignores text, kind, actor, and location filters while preserving an explicit space filter.",
    status: "action-backed",
    actions: [
      "execute-content-trash-purge",
      "get-content-trash-purge-plan",
      "get-content-trash-operation",
      "get-trashed-document",
      "list-content-trash",
      "permanently-delete-document",
      "plan-content-trash-purge",
      "restore-document",
    ],
    exception:
      "The read-only preview currently renders the Page body only, not full typed Properties, comments, or History.",
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/list-content-trash.db.test.ts",
      "actions/content-trash-purge.db.test.ts",
      "app/components/editor/trash-preview-content.test.ts",
      "app/hooks/content-action-refresh.trash.test.ts",
    ],
  },
  {
    id: "workspace.spaces-and-files-catalog",
    surface: "workspace",
    label:
      "Provision, navigate, and delete Content spaces through Files and Workspaces with personal expansion state",
    uiEntrypoints: [
      "app/components/sidebar/DocumentSidebar.tsx",
      "app/hooks/use-content-spaces.ts",
    ],
    durableEffect:
      "Personal and organization spaces, user-created workspaces, their canonical Files databases, the personal Workspaces catalog, and each user's sidebar expansion state are stored and reconciled in SQL; deleting a user-created workspace atomically removes its catalog row and contents.",
    uiImplementation:
      "The app sidebar calls the shared space actions and renders the selected Files database through a saved sidebar view.",
    status: "action-backed",
    actions: [
      "backfill-content-files",
      "create-content-space",
      "delete-content-space",
      "ensure-content-spaces",
      "get-content-sidebar-state",
      "list-content-spaces",
      "update-content-sidebar-state",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/content-spaces.db.test.ts",
      "actions/content-files.db.test.ts",
      "actions/content-sidebar-state.test.ts",
    ],
  },
  {
    id: "sidebar.navigation-and-screen-context",
    surface: "sidebar",
    label: "Navigate between documents and expose current screen context",
    uiEntrypoints: [
      "app/components/sidebar/DocumentSidebar.tsx",
      "actions/navigate.ts",
      "actions/view-screen.ts",
    ],
    durableEffect:
      "Application navigation state is updated or read so the agent can reason about the user's current page/view.",
    uiImplementation:
      "The UI uses React Router and application-state writes; agents use navigation and screen-context actions.",
    status: "action-equivalent",
    actions: ["navigate", "view-screen"],
    exception:
      "Human navigation is router-local, while agent navigation/screen inspection uses application-state actions to produce the same workspace orientation effect.",
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "seeded",
    followUpPR: null,
  },
  {
    id: "workspace.root-landing-resolver",
    surface: "workspace",
    label:
      "Resolve the app root to the caller's last authorized page or a private welcome page",
    uiEntrypoints: ["app/routes/_app.home.tsx", "app/lib/content-landing.ts"],
    durableEffect:
      "The root route restores the most recent authorized page when possible and otherwise converges on one private personal welcome page while preserving last-location state.",
    uiImplementation:
      "The index route invokes the shared landing resolver on first load, then navigates to the resolved page and records the landing document in application state.",
    status: "action-backed",
    actions: ["resolve-content-landing"],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/resolve-content-landing.db.test.ts",
      "app/lib/content-landing.test.ts",
    ],
  },
  {
    id: "sidebar.chrome-state",
    surface: "sidebar",
    label: "Collapse sections and resize the sidebar",
    uiEntrypoints: [
      "app/components/sidebar/DocumentSidebar.tsx",
      "app/components/layout/Layout.tsx",
    ],
    durableEffect: null,
    uiImplementation:
      "Sidebar expansion, section collapse, and width are client-local UI state.",
    status: "client-only-ephemeral",
    actions: [],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P2",
    testCoverage: "none",
    followUpPR: null,
  },
  {
    id: "editor.document-body-and-title",
    surface: "editor",
    label: "Edit document title, body, icon, image alt text, and precise text",
    uiEntrypoints: [
      "app/components/editor/DocumentEditor.tsx",
      "app/components/editor/PageDraftRecovery.tsx",
      "app/components/editor/VisualEditor.tsx",
      "app/components/editor/DocumentDatabase.tsx",
      "app/components/editor/extensions/ImageBlock.tsx",
      "app/components/editor/SlashCommandMenu.tsx",
    ],
    durableEffect:
      "Document content, title, icon, image metadata, and text replacements are saved to the same document source.",
    uiImplementation:
      "The editor autosaves through update-document, checks browser save receipts after interrupted delivery, and seeds an empty live editor from the saved body; agents can use update-document, edit-document, pull-document, and media-specific helpers.",
    status: "action-backed",
    actions: [
      "edit-document",
      "get-document-save-attempt",
      "pull-document",
      "seed-document-collab",
      "set-image-alt-text",
      "transcribe-media",
      "update-document",
    ],
    exception:
      "Save-attempt receipt lookup and live collaboration seeding are browser-only editor support actions hidden from agent tools with agentTool: false.",
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/content-database-lifecycle.db.test.ts",
      "actions/update-document.db.test.ts",
      "actions/_local-file-documents.test.ts",
    ],
    evalScenarioIds: ["document-search-edit"],
  },
  {
    id: "editor.suggested-edits",
    surface: "editor",
    label: "Propose reviewable suggested edits (track changes)",
    uiEntrypoints: [
      "app/components/editor/DocumentEditor.tsx",
      "app/components/editor/ReviewDiscussionTools.tsx",
      "app/components/editor/CommentsSidebar.tsx",
    ],
    durableEffect:
      "Pending suggestions are stored as authored proposal records; the canonical page body stays unchanged until a reviewer accepts.",
    uiImplementation:
      "The editor's suggesting mode creates proposals through the core create-resource-suggestion action with tracked-change operations; agents propose typed find/replace suggestions through suggest-document-edit.",
    status: "action-backed",
    actions: ["suggest-document-edit"],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: ["actions/suggest-document-edit.db.test.ts"],
  },
  {
    id: "editor.blocks-field-word-count",
    surface: "editor",
    label: "Inspect per-field word counts",
    uiEntrypoints: ["app/components/editor/DocumentInfoPanel.tsx"],
    durableEffect:
      "Authorized Blocks-field word counts read the current field without combining sibling fields.",
    uiImplementation:
      "Page Info projects live per-field counts; agents request the same exact field through a read-only action.",
    status: "action-backed",
    actions: ["get-blocks-field-word-count"],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/get-blocks-field-word-count.test.ts",
      "app/components/editor/DocumentInfoPanel.test.ts",
    ],
  },
  {
    id: "editor.client-formatting-and-insertions",
    surface: "editor",
    label:
      "Rich text formatting, selection state, slash block insertion, and copy actions",
    uiEntrypoints: [
      "app/components/editor/BubbleToolbar.tsx",
      "app/components/editor/SlashCommandMenu.tsx",
      "app/components/editor/DocumentToolbar.tsx",
    ],
    durableEffect: null,
    uiImplementation:
      "Formatting and insertion controls mutate the local editor transaction; persistence is covered by the document save row.",
    status: "client-only-ephemeral",
    actions: [],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "none",
    followUpPR: null,
  },
  {
    id: "editor.agent-assist-prompts",
    surface: "editor",
    label: "Ask AI from slash generation or comment context",
    uiEntrypoints: [
      "app/components/editor/SlashCommandMenu.tsx",
      "app/components/editor/CommentsSidebar.tsx",
    ],
    durableEffect:
      "No direct durable mutation; the prompt asks the agent to use document actions when it decides to write.",
    uiImplementation:
      "Client composes context and sends it to agent chat rather than directly calling an LLM or mutating data.",
    status: "client-assist",
    actions: [],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "none",
    followUpPR: null,
  },
  {
    id: "sharing.document-discoverability-and-export",
    surface: "sharing",
    label: "Share, hide from search, export, and reveal documents",
    uiEntrypoints: [
      "app/components/editor/DocumentToolbar.tsx",
      "app/hooks/use-documents.ts",
    ],
    durableEffect:
      "Search discoverability, shareable copies, exports, and OS reveal requests are managed through Content actions.",
    uiImplementation:
      "Toolbar actions call sharing/export/discoverability actions; local source reveal is host-only and hidden from model tools.",
    status: "action-backed",
    actions: [
      "export-document",
      "reveal-local-source-file",
      "set-document-discoverability",
      "share-local-file-document",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: ["actions/_local-file-documents.test.ts"],
    evalScenarioIds: ["local-file-source-truth"],
  },
  {
    id: "sharing.os-reveal-local-source",
    surface: "sharing",
    label: "Reveal a local source file in the system file manager",
    uiEntrypoints: [
      "app/components/editor/DocumentToolbar.tsx",
      "actions/reveal-local-source-file.ts",
    ],
    durableEffect: null,
    uiImplementation:
      "A trusted host opens the OS file manager for a local file path; the action is intentionally hidden from the model with agentTool: false.",
    status: "host-only",
    actions: ["reveal-local-source-file"],
    exception:
      "OS reveal depends on trusted local host capabilities and should not spend agent tool surface or imply portable hosted behavior.",
    reliabilityRisk: "none",
    spinePriority: "P2",
    testCoverage: "seeded",
    followUpPR: "Local folder exception/docs PR",
  },
  {
    id: "database.lifecycle-and-trash",
    surface: "database",
    label: "Create, soft-delete, restore, list, and inspect content databases",
    uiEntrypoints: [
      "app/components/editor/SlashCommandMenu.tsx",
      "app/hooks/use-content-database.ts",
      "app/hooks/use-documents.ts",
    ],
    durableEffect:
      "Database pages and database records are created, read, soft-deleted, restored, and listed.",
    uiImplementation:
      "Database creation and lifecycle controls call content database actions.",
    status: "action-backed",
    actions: [
      "create-content-database",
      "create-inline-content-database",
      "delete-content-database",
      "describe-content-database",
      "get-content-database",
      "list-content-databases",
      "list-trashed-content-databases",
      "restore-content-database",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/content-database-lifecycle.db.test.ts",
      "actions/list-content-databases.db.test.ts",
      "server/plugins/agent-chat.spec.ts",
      "../../packages/core/src/server/agent-chat/content-a2a-capabilities.spec.ts",
    ],
    evalScenarioIds: ["database-source-scope"],
  },
  {
    id: "database.table-query-page",
    surface: "database",
    label: "Query one constrained table page while retaining database metadata",
    uiEntrypoints: [
      "app/components/editor/database/DatabaseView.tsx",
      "app/hooks/use-content-database.ts",
    ],
    durableEffect: null,
    uiImplementation:
      "The table view loads changed search, filter, and sort results through a page-only action while the base database response remains visible; the sidebar uses the same action's separate bounded navigation projection.",
    status: "action-backed",
    actions: ["query-content-database-items"],
    exception:
      "This UI-only bounded projection is intentionally hidden with agentTool: false; agents use get-content-database for database reads and list-documents, get-document, search-documents, and navigate for workspace navigation.",
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/content-database-lifecycle.db.test.ts",
      "app/hooks/use-content-database.test.ts",
    ],
  },
  {
    id: "database.form-submissions",
    surface: "database",
    label: "Submit public database forms as new rows",
    uiEntrypoints: ["app/components/editor/database/FormView.tsx"],
    durableEffect:
      "A validated form submission atomically creates a database row document and its editable property values.",
    uiImplementation:
      "The public form view calls the same submission action exposed to agents and rolls back the row if a property write fails.",
    status: "action-backed",
    actions: ["submit-content-database-form"],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: ["actions/submit-content-database-form.db.test.ts"],
  },
  {
    id: "database.rows",
    surface: "database",
    label: "Add, duplicate, move, open, edit, and remove database rows",
    uiEntrypoints: [
      "app/components/editor/DocumentDatabase.tsx",
      "app/components/editor/database/DatabaseView.tsx",
    ],
    durableEffect:
      "Database row memberships and ordering are created, duplicated, moved, edited, and removed without deleting the backing page; bounded migrations atomically update row bodies and properties through the same canonical data model.",
    uiImplementation:
      "Row controls call row actions; the editor and agent share stable Blocks identities for one-block edits; selected-row duplicate/removal call bounded batch actions, while bounded whole-database schema-and-body migrations use one validated, receipt-backed action instead of many partial writes.",
    status: "action-backed",
    actions: [
      "add-database-item",
      "update-database-item",
      "upsert-database-item-by-key",
      "list-content-database-blocks",
      "mutate-content-database-block",
      "remove-database-items",
      "duplicate-database-items",
      "duplicate-database-item",
      "update-database-items",
      "migrate-content-database-rows",
      "manage-content-database-migration",
      "move-database-item",
      "set-document-property",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/database-row-batch-actions.db.test.ts",
      "actions/upsert-database-item-by-key.db.test.ts",
      "actions/migrate-content-database-rows.db.test.ts",
      "actions/content-database-block-actions.db.test.ts",
      "parity/__tests__/database-row-batch-reliability.test.ts",
    ],
    evalScenarioIds: ["database-bulk-row-reliability"],
  },
  {
    id: "database.private-preview-drafts",
    surface: "database",
    label: "Persist and reconcile a user's private database-page preview draft",
    uiEntrypoints: [
      "app/components/editor/database/DatabaseView.tsx",
      "app/hooks/use-documents.ts",
    ],
    durableEffect:
      "A user's private preview draft is read, saved, conflict-checked, or deleted without changing the shared database page until the normal save flow applies it.",
    uiImplementation:
      "The database preview uses the shared draft actions to preserve in-progress body edits across hydration and conflict states.",
    status: "action-backed",
    actions: [
      "get-preview-document-draft",
      "resolve-preview-document-draft",
      "update-preview-document-draft",
    ],
    exception:
      "These per-user editor-state actions are intentionally hidden from agent tools because preview drafts are a private UI recovery mechanism.",
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: ["actions/preview-document-draft.db.test.ts"],
  },
  {
    id: "database.properties-and-view-config",
    surface: "database",
    label: "Configure properties, values, ordering, and saved views",
    uiEntrypoints: [
      "app/components/editor/DocumentProperties.tsx",
      "app/components/editor/DocumentDatabase.tsx",
      "app/components/editor/database/DatabaseView.tsx",
      "app/hooks/use-document-properties.ts",
    ],
    durableEffect:
      "Property schemas, property values, property order, filters, sorts, grouping, hidden columns, view type, and view settings are stored.",
    uiImplementation:
      "Property popovers and database view controls call document property and view actions.",
    status: "action-backed",
    actions: [
      "configure-document-property",
      "delete-document-property",
      "duplicate-document-property",
      "get-content-database-personal-view",
      "list-document-properties",
      "reorder-document-property",
      "set-document-property",
      "update-content-database-personal-view",
      "update-content-database-view",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/database-setup-mcp.db.test.ts",
      "actions/bind-content-database-source-field.db.test.ts",
      "actions/content-database-source-actions.test.ts",
      "actions/resync-content-database-source.db.test.ts",
    ],
    evalScenarioIds: ["database-source-scope"],
  },
  {
    id: "source-sync.database-source-bindings",
    surface: "source-sync",
    label:
      "Attach, inspect, refresh, disconnect, join, and bind database sources",
    uiEntrypoints: [
      "app/components/editor/DocumentDatabase.tsx",
      "app/components/editor/DocumentProperties.tsx",
      "app/components/editor/database/DatabaseView.tsx",
      "app/hooks/use-content-database.ts",
    ],
    durableEffect:
      "Mounted database source metadata, fields, source role, join keys, and source-field/property bindings are stored and refreshed.",
    uiImplementation:
      "Database settings and property UI call source actions through Content database hooks.",
    status: "action-backed",
    actions: [
      "add-content-database-source-field-property",
      "attach-content-database-source",
      "bind-content-database-source-field",
      "change-content-database-source-role",
      "disconnect-content-database-source",
      "get-content-database-source",
      "list-builder-cms-models",
      "list-notion-database-sources",
      "preview-content-database-source-attach",
      "refresh-content-database-source",
      "suggest-source-join-key",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/bind-content-database-source-field.db.test.ts",
      "actions/content-database-source-actions.test.ts",
      "actions/resync-content-database-source.db.test.ts",
    ],
    evalScenarioIds: ["database-source-scope"],
  },
  {
    id: "source-sync.builder-cms-review-and-write-gates",
    surface: "source-sync",
    label:
      "Review, stage, validate, cancel, and execute Builder CMS source writes",
    uiEntrypoints: [
      "app/components/editor/DocumentDatabase.tsx",
      "app/components/editor/database/DatabaseView.tsx",
      "app/components/editor/database-sources/BuilderSourceReviewDialog.tsx",
    ],
    durableEffect:
      "Builder source write mode, staged reviews, pre-dispatch cancellations, validation records, and bounded execution records are created through guarded actions.",
    uiImplementation:
      "Builder source dialogs call review, write-mode, validation, staging, and execution actions.",
    status: "action-backed",
    actions: [
      "cancel-prepared-builder-source-update",
      "execute-builder-source-batch",
      "execute-builder-source-execution",
      "prepare-builder-source-execution",
      "prepare-builder-source-review",
      "preview-builder-source-review",
      "review-content-database-source-change-set",
      "set-content-database-source-write-mode",
      "stage-builder-source-bulk-update",
      "stage-builder-revision",
      "validate-builder-source-execution",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/builder-source-review-gates.db.test.ts",
      "actions/cancel-prepared-builder-source-update.db.test.ts",
      "actions/execute-builder-source-execution.test.ts",
      "actions/stage-builder-source-bulk-update.db.test.ts",
    ],
    evalScenarioIds: ["builder-source-review-readonly"],
  },
  {
    id: "source-sync.builder-body-hydration-worker",
    surface: "source-sync",
    label: "Process queued Builder CMS body hydration work",
    uiEntrypoints: [
      "app/components/editor/DocumentEditor.tsx",
      "app/components/editor/database/DatabaseView.tsx",
      "app/hooks/use-content-database.ts",
    ],
    durableEffect:
      "Queued Builder body hydration entries are processed into readable Content document/database body state.",
    uiImplementation:
      "Editor and database views trigger bounded queue processing through the shared action surface after source sync exposes hydration work.",
    status: "action-backed",
    actions: ["process-builder-body-hydration"],
    exception:
      "This action is intentionally hidden from the model with agentTool: false because it is an internal bounded queue worker; agents should use source refresh, review, and execution actions rather than manually driving hydration internals.",
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: ["actions/_database-source-utils.test.ts"],
  },
  {
    id: "source-sync.builder-required-field-materialization",
    surface: "source-sync",
    label: "Add required Builder publishing fields to a connected collection",
    uiEntrypoints: [
      "app/components/editor/database/DatabaseView.tsx",
      "app/hooks/use-content-database.ts",
    ],
    durableEffect:
      "Required Builder fields are materialized as editable Content properties in one local mutation.",
    uiImplementation:
      "Connected-source settings call the shared materialization action and refresh the database cache.",
    status: "action-backed",
    actions: ["materialize-builder-required-fields"],
    exception:
      "This bounded safe-model setup action is intentionally hidden from the agent tool list; the visible source settings surface invokes it.",
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: ["actions/materialize-builder-required-fields.test.ts"],
  },
  {
    id: "source-sync.builder-documents",
    surface: "source-sync",
    label: "List, pull, check, and push Builder docs/blog MDX documents",
    uiEntrypoints: [
      "actions/list-builder-docs.ts",
      "actions/pull-builder-doc.ts",
      "actions/check-builder-doc.ts",
      "actions/push-builder-doc.ts",
    ],
    durableEffect:
      "Builder docs/blog entries can be read into Content, checked locally, and pushed through guarded Builder document actions.",
    uiImplementation:
      "Currently agent/action-facing rather than a primary visible UI surface.",
    status: "action-backed",
    actions: [
      "check-builder-doc",
      "list-builder-docs",
      "pull-builder-doc",
      "push-builder-doc",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "seeded",
    followUpPR: null,
  },
  {
    id: "source-sync.provider-api-and-staged-datasets",
    surface: "source-sync",
    label:
      "Inspect provider APIs and stage/query/delete large provider datasets",
    uiEntrypoints: [
      "actions/provider-api-catalog.ts",
      "actions/provider-api-docs.ts",
      "actions/provider-api-request.ts",
      "actions/query-staged-dataset.ts",
    ],
    durableEffect:
      "Provider API metadata and staged dataset scratch storage support scoped agent/source analysis.",
    uiImplementation:
      "Agent-facing provider API substrate; UI parity is capability parity rather than a visible button-by-button mapping.",
    status: "action-backed",
    actions: [
      "delete-staged-dataset",
      "list-staged-datasets",
      "provider-api-catalog",
      "provider-api-docs",
      "provider-api-request",
      "query-staged-dataset",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "seeded",
    followUpPR: null,
  },
  {
    id: "local-files.import-export-mounted-folder",
    surface: "local-files",
    label: "Import, check, export, push, and remove local folder source files",
    uiEntrypoints: [
      "app/routes/_app.local-files.tsx",
      "actions/import-content-source.ts",
      "actions/export-content-source.ts",
    ],
    durableEffect:
      "Local Markdown/MDX source files are imported into Content documents, editable Content documents are exported back to source-friendly files, and imported source entries can be removed without deleting files on disk.",
    uiImplementation:
      "UI reads/writes browser or Desktop folder handles around import/export actions.",
    status: "action-backed",
    actions: [
      "connect-local-folder-source",
      "disconnect-local-folder-source",
      "export-content-source",
      "import-content-source",
      "remove-local-file-source",
      "resolve-local-folder-conflict",
      "sync-local-folder-source",
      "sync-manifest-local-folder-source",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/_local-file-documents.test.ts",
      "actions/local-folder-source.db.test.ts",
    ],
    evalScenarioIds: ["local-file-source-truth"],
  },
  {
    id: "local-files.host-folder-handles",
    surface: "local-files",
    label: "Choose, persist, remove, and write trusted local folder handles",
    uiEntrypoints: ["app/routes/_app.local-files.tsx"],
    durableEffect:
      "Host directory handles and browser/Desktop write permissions are managed outside SQL action state.",
    uiImplementation:
      "Browser File System Access and Desktop bridge APIs own the physical folder handles and writes.",
    status: "host-only",
    actions: [],
    exception:
      "Mounted local folders require browser/Desktop host handles that agents cannot safely or portably hold as normal tools.",
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "none",
    followUpPR: "Local folder exception/docs PR",
  },
  {
    id: "local-files.components-workspace",
    surface: "local-files",
    label: "Register, list, and write local MDX component workspaces",
    uiEntrypoints: [
      "app/routes/_app.local-files.tsx",
      "actions/register-local-component-workspace.ts",
      "actions/list-local-component-files.ts",
      "actions/write-local-component-file.ts",
    ],
    durableEffect:
      "Trusted local component workspace registration and component file reads/writes support local MDX previews.",
    uiImplementation:
      "Desktop-host workspace registration is hidden from model tools; listed/written files use Content actions once registered.",
    status: "host-only",
    actions: [
      "list-local-component-files",
      "register-local-component-workspace",
      "write-local-component-file",
    ],
    exception:
      "Workspace registration depends on a trusted Desktop folder path and is intentionally hidden with agentTool: false.",
    reliabilityRisk: "none",
    spinePriority: "P1",
    testCoverage: "seeded",
    followUpPR: "Local folder exception/docs PR",
  },
  {
    id: "notion.route-backed-document-sync",
    surface: "source-sync",
    label:
      "Notion document sync status, link, unlink, pull, push, resolve, create, search, and disconnect",
    uiEntrypoints: [
      "app/hooks/use-notion.ts",
      "app/components/editor/DocumentToolbar.tsx",
      "app/components/editor/NotionSyncBar.tsx",
      "app/components/editor/DocumentEditor.tsx",
    ],
    durableEffect:
      "Notion connection state, page search, link metadata, and local/remote document body sync state are read or mutated through Content actions.",
    uiImplementation:
      "Notion document sync hooks call the shared action surface; OAuth auth-url/callback routes remain route-shaped because they depend on browser redirects.",
    status: "action-backed",
    actions: [
      "connect-notion-status",
      "create-and-link-notion-page",
      "disconnect-notion",
      "link-notion-page",
      "list-notion-links",
      "pull-notion-page",
      "push-notion-page",
      "refresh-notion-sync-status",
      "resolve-notion-sync-conflict",
      "search-notion-pages",
      "sync-notion-comments",
      "unlink-notion-page",
    ],
    exception:
      "Notion OAuth auth-url and callback routes remain route-shaped because they initiate and receive browser redirects rather than normal app data mutations.",
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: ["parity/__tests__/matrix-route-gap-classify.test.ts"],
    routePatterns: ["/api/notion/auth-url", "/api/notion/callback"],
  },
  {
    id: "comments.ai-intents",
    surface: "comments",
    label:
      "Mention AI in a comment to reply, suggest an edit, or apply it and resolve feedback, then undo an applied change",
    uiEntrypoints: [
      "app/components/editor/CommentsSidebar.tsx",
      "app/components/editor/comment-ai.tsx",
    ],
    durableEffect:
      "Requests retain the submitted mode, selected provider and model, source feedback, and document revisions. Auto persists one classified intent before a separately scoped execution run records the reply, suggestion, or verified edit receipt. An applied edit keeps a bounded before/after preview, and its requester can reverse the exact edits and reopen the thread.",
    uiImplementation:
      "A structured AI recipient in the Comment composer starts the request through the shared action surface. Auto classification can submit only a finite intent; execution can call only the context action and the operation bound to that persisted intent.",
    status: "action-backed",
    actions: [
      "apply-comment-ai-request",
      "create-comment-ai-suggestion",
      "get-comment-ai-context",
      "list-comment-ai-requests",
      "reconcile-comment-ai-session",
      "reply-to-comment-ai-request",
      "start-comment-ai-request",
      "submit-comment-ai-classification",
      "undo-comment-ai-request",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/comment-ai-flow.test.ts",
      "actions/undo-comment-ai-request.db.test.ts",
      "app/components/editor/comment-ai.test.tsx",
      "server/lib/comment-ai-progress.test.ts",
    ],
  },
  {
    id: "comments.email-preferences",
    surface: "comments",
    label:
      "Read and turn the current user's comment, reply, and mention emails on or off",
    uiEntrypoints: [
      "app/components/settings/notification-settings.tsx",
      "app/routes/_app.settings.tsx",
    ],
    durableEffect:
      "The per-user content-user-prefs setting stores emailNotifications, which the comment senders read before emailing each recipient.",
    uiImplementation:
      "Settings reads the preference and saves the switch optimistically, with rollback, through the same Actions the agent calls.",
    status: "action-backed",
    actions: [
      "get-content-notification-prefs",
      "update-content-notification-prefs",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P2",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: [
      "actions/content-notification-prefs.test.ts",
      "app/components/settings/notification-settings.test.tsx",
    ],
  },
  {
    id: "comments.reactions",
    surface: "comments",
    label: "React to a comment or reply with an emoji, or remove your reaction",
    uiEntrypoints: [
      "app/components/editor/CommentEntry.tsx",
      "app/components/editor/CommentReactions.tsx",
    ],
    durableEffect:
      "One row per person, emoji, and comment in document_comment_reactions; list-comments returns per-comment counts with the viewer's own reactions, and deleting a comment removes its reactions.",
    uiImplementation:
      "The reaction chips and add-reaction picker call react-to-comment with an optimistic update, and agents use the same action.",
    status: "action-backed",
    actions: ["react-to-comment", "list-comments"],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P2",
    testCoverage: "covered",
    followUpPR: null,
    coverageRefs: ["actions/react-to-comment.db.test.ts"],
  },
  {
    id: "comments.threads",
    surface: "comments",
    label: "List, add, reply, resolve, reopen, and delete comment threads",
    uiEntrypoints: [
      "app/components/editor/CommentsSidebar.tsx",
      "app/hooks/use-comments.ts",
    ],
    durableEffect:
      "Comment threads, replies, anchors, mentions, resolution state, and deletion are stored through comment actions.",
    uiImplementation:
      "Comment hooks call comment actions; comment positioning is client-only editor geometry.",
    status: "action-backed",
    actions: [
      "add-comment",
      "delete-comment",
      "list-comments",
      "update-comment",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "seeded",
    followUpPR: null,
  },
  {
    id: "versions.history-and-restore",
    surface: "versions",
    label: "Open version history and restore a previous document version",
    uiEntrypoints: [
      "app/components/editor/VersionHistoryPanel.tsx",
      "app/hooks/use-document-versions.ts",
    ],
    durableEffect:
      "Document versions are listed and selected versions can restore the document while snapshotting current state.",
    uiImplementation:
      "Version panel reads and restores through document version actions.",
    status: "action-backed",
    actions: [
      "list-document-versions",
      "list-document-history",
      "list-document-history-checkpoints",
      "get-document-history-checkpoint",
      "restore-document-version",
    ],
    exception: null,
    reliabilityRisk: "none",
    spinePriority: "P0",
    testCoverage: "seeded",
    followUpPR: null,
  },
];
