// Frozen compatibility artifact for persisted Design boards written with Group runtime v1.
// Keep this exact generated source until v1 archives are no longer supported.
// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for group-runtime.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const LEGACY_GROUP_RUNTIME_V1_SOURCE: string = `"use strict";
(() => {
  // app/components/design/bridge/group-runtime.bridge.ts
  (function() {
    const W = window;
    if (W.__anGroupRuntime?.version === 1) {
      W.__anGroupRuntime.scan();
      return;
    }
    const GROUP_SELECTOR = "[data-agent-native-measured-flow-group]";
    const states = /* @__PURE__ */ new WeakMap();
    const observed = /* @__PURE__ */ new WeakSet();
    const resizeObserver = typeof ResizeObserver === "undefined" ? null : new ResizeObserver(() => schedule());
    let frame = 0;
    let sourceRevision = 0;
    function writeStyle(group, property, value) {
      if (group.style.getPropertyValue(property) !== value) {
        group.style.setProperty(property, value);
      }
    }
    function restore(group, state) {
      writeStyle(group, "width", state.width);
      writeStyle(group, "height", state.height);
      state.lastRuntimeStyle = group.getAttribute("style") ?? "";
      group.setAttribute("data-agent-native-group-runtime-state", "unsupported");
    }
    function transformed(element) {
      const computed = getComputedStyle(element);
      return computed.transform !== "none" || computed.translate !== "none" || computed.rotate !== "none" || computed.scale !== "none" || !/^(?:1|normal)?$/.test(computed.getPropertyValue("zoom"));
    }
    function unsupported(element) {
      const style = element.style;
      return [
        style.width,
        style.height,
        style.minWidth,
        style.maxWidth,
        style.minHeight,
        style.maxHeight,
        style.flexBasis
      ].some((value) => /%|\\b(?:calc|var|min|max|clamp)\\s*\\(/i.test(value)) || Number.parseFloat(getComputedStyle(element).flexGrow) > 0 || transformed(element);
    }
    function hasTransformedAncestor(group) {
      for (let parent = group.parentElement; parent; parent = parent.parentElement) {
        if (transformed(parent)) return true;
      }
      return false;
    }
    function refreshCanonicalState(group, state) {
      const sourceStyle = group.__anSourceMeta?.style;
      if (sourceStyle === void 0 || sourceStyle === state.sourceStyle) return;
      const probe = document.createElement("div");
      probe.style.cssText = sourceStyle;
      state.width = probe.style.width;
      state.height = probe.style.height;
      state.sourceStyle = sourceStyle;
    }
    function measure(group) {
      let state = states.get(group);
      if (!state) {
        state = {
          width: group.style.width,
          height: group.style.height,
          lastRevision: sourceRevision,
          unstablePasses: 0
        };
        states.set(group, state);
      }
      refreshCanonicalState(group, state);
      if (state.cyclicRevision === sourceRevision) {
        restore(group, state);
        return;
      }
      const children = Array.from(group.children).filter(
        (child) => child instanceof HTMLElement
      );
      if (children.length === 0 || unsupported(group) || hasTransformedAncestor(group) || children.some(unsupported)) {
        restore(group, state);
        return;
      }
      const groupRect = group.getBoundingClientRect();
      let minLeft = 0;
      let minTop = 0;
      let maxRight = 0;
      let maxBottom = 0;
      for (const child of children) {
        const rect = child.getBoundingClientRect();
        minLeft = Math.min(minLeft, rect.left - groupRect.left);
        minTop = Math.min(minTop, rect.top - groupRect.top);
        maxRight = Math.max(maxRight, rect.right - groupRect.left);
        maxBottom = Math.max(maxBottom, rect.bottom - groupRect.top);
      }
      if (minLeft < -0.01 || minTop < -0.01) {
        restore(group, state);
        return;
      }
      const width = maxRight - minLeft;
      const height = maxBottom - minTop;
      if (![width, height].every(Number.isFinite) || width < 0 || height < 0) {
        restore(group, state);
        return;
      }
      const changedAgain = state.lastRevision === sourceRevision && state.lastWidth !== void 0 && state.lastHeight !== void 0 && (Math.abs(width - state.lastWidth) > 0.01 || Math.abs(height - state.lastHeight) > 0.01);
      state.unstablePasses = changedAgain ? state.unstablePasses + 1 : 0;
      state.lastRevision = sourceRevision;
      state.lastWidth = width;
      state.lastHeight = height;
      if (state.unstablePasses >= 2) {
        state.cyclicRevision = sourceRevision;
        restore(group, state);
        return;
      }
      writeStyle(group, "width", \`\${Number(width.toFixed(4))}px\`);
      writeStyle(group, "height", \`\${Number(height.toFixed(4))}px\`);
      state.lastRuntimeStyle = group.getAttribute("style") ?? "";
      group.setAttribute("data-agent-native-group-runtime-state", "active");
    }
    function depth(element) {
      let value = 0;
      for (let parent = element.parentElement; parent; parent = parent.parentElement)
        value += 1;
      return value;
    }
    function scan() {
      const groups = Array.from(
        document.querySelectorAll(GROUP_SELECTOR)
      ).sort((left, right) => depth(right) - depth(left));
      for (const group of groups) {
        if (resizeObserver && !observed.has(group)) {
          observed.add(group);
          resizeObserver.observe(group);
        }
        for (const child of group.children) {
          if (resizeObserver && !observed.has(child)) {
            observed.add(child);
            resizeObserver.observe(child);
          }
        }
        measure(group);
      }
    }
    function schedule() {
      if (frame) return;
      frame = requestAnimationFrame(() => {
        frame = 0;
        scan();
      });
    }
    W.__anGroupRuntime = { version: 1, scan: schedule };
    if (typeof MutationObserver !== "undefined" && document.body) {
      new MutationObserver((records) => {
        if (records.some((record) => {
          if (record.type !== "attributes" || record.attributeName !== "style" || !(record.target instanceof HTMLElement)) {
            return true;
          }
          const state = states.get(record.target);
          return !state || state.lastRuntimeStyle !== (record.target.getAttribute("style") ?? "");
        })) {
          sourceRevision += 1;
        }
        schedule();
      }).observe(document.body, {
        attributes: true,
        attributeFilter: ["class", "hidden", "style"],
        childList: true,
        characterData: true,
        subtree: true
      });
    }
    W.addEventListener("resize", () => {
      sourceRevision += 1;
      schedule();
    });
    if (document.fonts) {
      void document.fonts.ready.then(() => {
        sourceRevision += 1;
        schedule();
      });
      if (typeof document.fonts.addEventListener === "function") {
        document.fonts.addEventListener("loadingdone", () => {
          sourceRevision += 1;
          schedule();
        });
      }
    }
    schedule();
  })();
})();
`;
