export const INTERACTION_STATES = [
  "hover",
  "focus",
  "focus-visible",
  "active",
  "disabled",
] as const;

export type InteractionState = (typeof INTERACTION_STATES)[number];

const STATE_SET: ReadonlySet<string> = new Set(INTERACTION_STATES);

export function isInteractionState(
  value: string | null | undefined,
): value is InteractionState {
  return typeof value === "string" && STATE_SET.has(value);
}

export type InteractionStatesModel = Record<
  string,
  Partial<Record<InteractionState, Record<string, string>>>
>;

export type ResponsiveInteractionStatesModel = Record<
  string,
  InteractionStatesModel
>;

export interface InteractionStateDeclaration {
  nodeId: string;
  state: InteractionState;
  property: string;
  value: string;
}

const CSS_VALUE_BREAKOUT_RE = /[;{}<>]|\/\*|\*\/|\burl\s*\(/i;
const CSS_VALUE_CONTROL_RE = /[\u0000-\u001f\u007f]/;

export function isSafeInteractionStateCssValue(value: string): boolean {
  if (typeof value !== "string") return false;
  const trimmed = value.trim();
  if (trimmed.length === 0) return false;
  if (CSS_VALUE_CONTROL_RE.test(value) || CSS_VALUE_BREAKOUT_RE.test(value)) {
    return false;
  }
  return true;
}

export function isSafeInteractionStateCssProperty(property: string): boolean {
  return /^(?:--[a-zA-Z_][a-zA-Z0-9_-]*|-?[a-zA-Z][a-zA-Z0-9-]*)$/.test(
    property,
  );
}

const OPEN_RE = /<style\b(?=[^>]*\bdata-agent-native-states\b)[^>]*>/i;
const RESPONSIVE_OPEN_RE =
  /<style\b(?=[^>]*\bdata-agent-native-state-breakpoints\b)[^>]*>/i;

export function extractManagedInteractionStateCss(html: string): string | null {
  const openMatch = OPEN_RE.exec(html);
  if (!openMatch) return null;
  const bodyStart = openMatch.index + openMatch[0].length;
  const afterOpen = html.slice(bodyStart);
  const closeMatch = /<\s*\/\s*style\b[^>]*>/i.exec(afterOpen);
  if (!closeMatch) return null;
  return afterOpen.slice(0, closeMatch.index).trim();
}

export function injectManagedInteractionStateCss(
  html: string,
  css: string,
): string {
  const openMatch = OPEN_RE.exec(html);
  const trimmed = css.trim();
  const block =
    trimmed.length > 0
      ? `<style data-agent-native-states>\n${trimmed}\n</style>`
      : "";

  if (openMatch) {
    const bodyStart = openMatch.index + openMatch[0].length;
    const afterOpen = html.slice(bodyStart);
    const closeMatch = /<\s*\/\s*style\b[^>]*>/i.exec(afterOpen);
    if (closeMatch) {
      const closeEnd = bodyStart + closeMatch.index + closeMatch[0].length;
      if (block === "") {
        const after = html.slice(closeEnd);
        return html.slice(0, openMatch.index) + after.replace(/^\n/, "");
      }
      return html.slice(0, openMatch.index) + block + html.slice(closeEnd);
    }
  }

  if (block === "") return html;
  const headClose = html.lastIndexOf("</head>");
  if (headClose !== -1) {
    return html.slice(0, headClose) + block + "\n" + html.slice(headClose);
  }
  return block + "\n" + html;
}

export function extractManagedResponsiveInteractionStateCss(
  html: string,
): string | null {
  return extractManagedStyleBody(html, RESPONSIVE_OPEN_RE);
}

export function injectManagedResponsiveInteractionStateCss(
  html: string,
  css: string,
): string {
  return injectManagedStyleBody(
    html,
    css,
    RESPONSIVE_OPEN_RE,
    "data-agent-native-state-breakpoints",
  );
}

// ─── CSS body parse / serialize ──────────────────────────────────────────────

/**
 * Matches ONE real pseudo-class state rule for a node id, e.g.
 * `[data-agent-native-node-id="btn_1"]:focus-visible { ... }`. Deliberately
 * does NOT match the `[data-an-state-preview="..."]` twin rules — those are
 * derived output, not source of truth, and are re-generated by
 * {@link duplicateStatePreviewRules} rather than parsed back in, so hand
 * edits to a twin rule in the Code panel don't fork state.
 */
function stateRuleRegex(): RegExp {
  return /\[data-agent-native-node-id="((?:\\.|[^"\\])*)"\]:(hover|focus-visible|focus|active|disabled)\s*\{([^}]*)\}/g;
}

export function parseInteractionStatesCss(css: string): InteractionStatesModel {
  const model: InteractionStatesModel = {};
  const ruleRe = stateRuleRegex();
  let match: RegExpExecArray | null;
  while ((match = ruleRe.exec(css)) !== null) {
    const nodeId = unescAttr(match[1]);
    const state = match[2];
    if (!nodeId || !isInteractionState(state)) continue;
    const declarations = match[3]
      .split(";")
      .map((decl) => decl.trim())
      .filter(Boolean);
    for (const declaration of declarations) {
      const colon = declaration.indexOf(":");
      if (colon <= 0) continue;
      const property = declaration.slice(0, colon).trim();
      const value = stripManagedImportant(declaration.slice(colon + 1));
      if (!isSafeInteractionStateCssProperty(property)) continue;
      if (!isSafeInteractionStateCssValue(value)) continue;
      model[nodeId] ??= {};
      const node = model[nodeId];
      node[state] ??= {};
      node[state]![property] = value;
    }
  }
  return model;
}

export function serializeInteractionStatesModel(
  model: InteractionStatesModel,
): string {
  const nodeIds = Object.keys(model).sort((a, b) => a.localeCompare(b));
  const rules: string[] = [];
  for (const nodeId of nodeIds) {
    const states = model[nodeId];
    for (const state of INTERACTION_STATES) {
      const declarations = states[state];
      if (!declarations) continue;
      const properties = Object.keys(declarations).sort((a, b) =>
        a.localeCompare(b),
      );
      if (properties.length === 0) continue;
      const lines = properties.map(
        (property) =>
          `  ${property}: ${stripManagedImportant(declarations[property])} !important;`,
      );
      rules.push(
        `[data-agent-native-node-id="${escAttr(nodeId)}"]:${state} {\n` +
          `${lines.join("\n")}\n` +
          `}`,
      );
    }
  }
  return rules.join("\n\n");
}

function rebuildCssWithPreviews(model: InteractionStatesModel): string {
  const baseBody = serializeInteractionStatesModel(model);
  const previewRules: string[] = [];
  const nodeIds = Object.keys(model).sort((a, b) => a.localeCompare(b));
  for (const nodeId of nodeIds) {
    const states = model[nodeId];
    for (const state of INTERACTION_STATES) {
      const declarations = states[state];
      if (!declarations) continue;
      const properties = Object.keys(declarations).sort((a, b) =>
        a.localeCompare(b),
      );
      if (properties.length === 0) continue;
      const lines = properties.map(
        (property) =>
          `  ${property}: ${stripManagedImportant(declarations[property])} !important;`,
      );
      previewRules.push(
        `[data-agent-native-node-id="${escAttr(nodeId)}"][data-an-state-preview="${state}"] {\n` +
          `${lines.join("\n")}\n` +
          `}`,
      );
    }
  }
  if (previewRules.length === 0) return baseBody;
  return baseBody === ""
    ? previewRules.join("\n\n")
    : `${baseBody}\n\n${previewRules.join("\n\n")}`;
}

export function serializeInteractionStatesModelWithPreviews(
  model: InteractionStatesModel,
): string {
  return rebuildCssWithPreviews(model);
}

export function parseResponsiveInteractionStatesCss(
  css: string,
): ResponsiveInteractionStatesModel {
  const model: ResponsiveInteractionStatesModel = {};
  const mediaRe = /@media\s*\(\s*max-width\s*:\s*(\d+(?:\.\d+)?)px\s*\)\s*\{/g;
  let match: RegExpExecArray | null;
  while ((match = mediaRe.exec(css)) !== null) {
    const maxWidthPx = Math.round(Number.parseFloat(match[1]));
    if (!Number.isFinite(maxWidthPx) || maxWidthPx <= 0) continue;
    const bodyStart = match.index + match[0].length;
    const body = extractCssBlock(css, bodyStart);
    if (body === null) continue;
    mediaRe.lastIndex = bodyStart + body.length + 1;
    const parsed = parseInteractionStatesCss(
      body.replace(
        /(\[data-agent-native-node-id="(?:\\.|[^"\\])*"\])\1/g,
        "$1",
      ),
    );
    if (Object.keys(parsed).length > 0) model[String(maxWidthPx)] = parsed;
  }
  return model;
}

export function serializeResponsiveInteractionStatesModel(
  model: ResponsiveInteractionStatesModel,
): string {
  return Object.keys(model)
    .map((key) => Number.parseInt(key, 10))
    .filter((bound) => Number.isFinite(bound) && bound > 0)
    .sort((a, b) => b - a)
    .flatMap((bound) => {
      const body = serializeResponsiveStateBucket(model[String(bound)] ?? {});
      if (!body) return [];
      return [
        `@media (max-width: ${bound}px) {\n${body
          .split("\n")
          .map((line) => `  ${line}`)
          .join("\n")}\n}`,
      ];
    })
    .join("\n\n");
}

export function duplicateStatePreviewRules(html: string): string {
  const css = extractManagedInteractionStateCss(html);
  if (css === null) return html;
  const model = parseInteractionStatesCss(css);
  return injectManagedInteractionStateCss(html, rebuildCssWithPreviews(model));
}

function writeModel(html: string, model: InteractionStatesModel): string {
  return injectManagedInteractionStateCss(
    html,
    serializeInteractionStatesModelWithPreviews(model),
  );
}

function readModel(html: string): InteractionStatesModel {
  return parseInteractionStatesCss(
    extractManagedInteractionStateCss(html) ?? "",
  );
}

function readResponsiveModel(html: string): ResponsiveInteractionStatesModel {
  return parseResponsiveInteractionStatesCss(
    extractManagedResponsiveInteractionStateCss(html) ?? "",
  );
}

export function listInteractionStates(
  html: string,
  nodeId: string,
): InteractionState[] {
  const model = readModel(html);
  const responsive = readResponsiveModel(html);
  return INTERACTION_STATES.filter((state) => {
    const declarations = model[nodeId]?.[state];
    if (declarations && Object.keys(declarations).length > 0) return true;
    return Object.values(responsive).some((bucket) => {
      const scoped = bucket[nodeId]?.[state];
      return scoped && Object.keys(scoped).length > 0;
    });
  });
}

export function readStateStyles(
  html: string,
  nodeId: string,
  state: InteractionState,
): Record<string, string> {
  const model = readModel(html);
  return { ...(model[nodeId]?.[state] ?? {}) };
}

export function readResolvedStateStyles(
  html: string,
  nodeId: string,
  state: InteractionState,
  viewportWidthPx?: number | null,
): Record<string, string> {
  const resolved = readStateStyles(html, nodeId, state);
  if (
    viewportWidthPx == null ||
    !Number.isFinite(viewportWidthPx) ||
    viewportWidthPx <= 0
  ) {
    return resolved;
  }
  const responsive = readResponsiveModel(html);
  const matchingBounds = Object.keys(responsive)
    .map((key) => Number.parseInt(key, 10))
    .filter((bound) => bound >= viewportWidthPx)
    .sort((a, b) => b - a);
  for (const bound of matchingBounds) {
    Object.assign(resolved, responsive[String(bound)]?.[nodeId]?.[state] ?? {});
  }
  return resolved;
}

export function upsertStateStyle(
  html: string,
  nodeId: string,
  state: InteractionState,
  property: string,
  value: string,
): string {
  return upsertStateStyles(html, nodeId, state, { [property]: value });
}

export function upsertStateStyles(
  html: string,
  nodeId: string,
  state: InteractionState,
  styles: Record<string, string>,
): string {
  if (!nodeId) throw new Error("upsertStateStyles requires a nodeId.");
  if (!isInteractionState(state)) {
    throw new Error(`Invalid interaction state: "${String(state)}".`);
  }
  const normalized = normalizeStateStyles(styles);
  const model = readModel(html);
  model[nodeId] ??= {};
  const node = model[nodeId];
  node[state] = { ...(node[state] ?? {}), ...normalized };
  return writeModel(html, model);
}

export function upsertResponsiveStateStyles(
  html: string,
  nodeId: string,
  state: InteractionState,
  maxWidthPx: number,
  styles: Record<string, string>,
): string {
  if (!nodeId)
    throw new Error("upsertResponsiveStateStyles requires a nodeId.");
  if (!isInteractionState(state)) {
    throw new Error(`Invalid interaction state: "${String(state)}".`);
  }
  if (!Number.isFinite(maxWidthPx) || maxWidthPx <= 0) {
    throw new Error(`Invalid interaction-state breakpoint: ${maxWidthPx}px.`);
  }
  const normalized = normalizeStateStyles(styles);
  const model = readResponsiveModel(html);
  const bucket = String(Math.round(maxWidthPx));
  model[bucket] ??= {};
  model[bucket][nodeId] ??= {};
  const node = model[bucket][nodeId];
  node[state] = { ...(node[state] ?? {}), ...normalized };
  return injectManagedResponsiveInteractionStateCss(
    html,
    serializeResponsiveInteractionStatesModel(model),
  );
}

export function removeResponsiveStateProperty(
  html: string,
  nodeId: string,
  state: InteractionState,
  maxWidthPx: number,
  property: string,
): string {
  const model = readResponsiveModel(html);
  const bucket = String(Math.round(maxWidthPx));
  const declarations = model[bucket]?.[nodeId]?.[state];
  if (!declarations) return html;
  const normalizedProperty = normalizeCssPropertyName(property.trim());
  if (!(normalizedProperty in declarations)) return html;
  delete declarations[normalizedProperty];
  if (Object.keys(declarations).length === 0)
    delete model[bucket][nodeId][state];
  if (Object.keys(model[bucket][nodeId]).length === 0)
    delete model[bucket][nodeId];
  if (Object.keys(model[bucket]).length === 0) delete model[bucket];
  return injectManagedResponsiveInteractionStateCss(
    html,
    serializeResponsiveInteractionStatesModel(model),
  );
}

export function removeStateProperty(
  html: string,
  nodeId: string,
  state: InteractionState,
  property: string,
): string {
  const model = readModel(html);
  const node = model[nodeId];
  const declarations = node?.[state];
  if (!declarations) return html;
  const normalizedProperty = normalizeCssPropertyName(property.trim());
  if (!(normalizedProperty in declarations)) return html;
  delete declarations[normalizedProperty];
  if (Object.keys(declarations).length === 0) {
    delete node![state];
  }
  if (node && Object.keys(node).length === 0) {
    delete model[nodeId];
  }
  return writeModel(html, model);
}

export function clearState(
  html: string,
  nodeId: string,
  state: InteractionState,
): string {
  const model = readModel(html);
  const node = model[nodeId];
  if (!node?.[state]) return html;
  delete node[state];
  if (Object.keys(node).length === 0) {
    delete model[nodeId];
  }
  return writeModel(html, model);
}

export function listAllInteractionStateDeclarations(
  html: string,
  nodeId?: string | null,
): InteractionStateDeclaration[] {
  const model = readModel(html);
  const declarations: InteractionStateDeclaration[] = [];
  const nodeIds = Object.keys(model).sort((a, b) => a.localeCompare(b));
  for (const ruleNodeId of nodeIds) {
    if (nodeId != null && ruleNodeId !== nodeId) continue;
    const states = model[ruleNodeId];
    for (const state of INTERACTION_STATES) {
      const props = states[state];
      if (!props) continue;
      const properties = Object.keys(props).sort((a, b) => a.localeCompare(b));
      for (const property of properties) {
        declarations.push({
          nodeId: ruleNodeId,
          state,
          property,
          value: props[property],
        });
      }
    }
  }
  return declarations;
}

function escAttr(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function unescAttr(value: string): string {
  return value.replace(/\\"/g, '"').replace(/\\\\/g, "\\");
}

function stripManagedImportant(value: string): string {
  return value.replace(/\s*!important\s*$/i, "").trim();
}

function normalizeStateStyles(
  styles: Record<string, string>,
): Record<string, string> {
  const normalized: Record<string, string> = {};
  for (const [rawProperty, rawValue] of Object.entries(styles)) {
    const property = normalizeCssPropertyName(rawProperty.trim());
    if (!isSafeInteractionStateCssProperty(property)) {
      throw new Error(`Invalid interaction-state property: "${rawProperty}".`);
    }
    const value = stripManagedImportant(rawValue);
    if (!isSafeInteractionStateCssValue(value)) {
      throw new Error(
        `Invalid interaction-state value for "${property}": semicolons, braces, comments, angle brackets, control characters, and url(...) are not allowed.`,
      );
    }
    normalized[property] = value;
  }
  return normalized;
}

function serializeResponsiveStateBucket(model: InteractionStatesModel): string {
  const realRules: string[] = [];
  const previewRules: string[] = [];
  for (const nodeId of Object.keys(model).sort((a, b) => a.localeCompare(b))) {
    const escaped = escAttr(nodeId);
    const target = `[data-agent-native-node-id="${escaped}"]`;
    const doubledTarget = `${target}${target}`;
    for (const state of INTERACTION_STATES) {
      const declarations = model[nodeId][state];
      if (!declarations) continue;
      const properties = Object.keys(declarations).sort((a, b) =>
        a.localeCompare(b),
      );
      if (properties.length === 0) continue;
      const lines = properties.map(
        (property) =>
          `  ${property}: ${stripManagedImportant(declarations[property])} !important;`,
      );
      realRules.push(`${doubledTarget}:${state} {\n${lines.join("\n")}\n}`);
      previewRules.push(
        `${doubledTarget}[data-an-state-preview="${state}"] {\n${lines.join("\n")}\n}`,
      );
    }
  }
  return [...realRules, ...previewRules].join("\n\n");
}

function extractManagedStyleBody(html: string, openRe: RegExp): string | null {
  const openMatch = openRe.exec(html);
  if (!openMatch) return null;
  const bodyStart = openMatch.index + openMatch[0].length;
  const afterOpen = html.slice(bodyStart);
  const closeMatch = /<\s*\/\s*style\b[^>]*>/i.exec(afterOpen);
  if (!closeMatch) return null;
  return afterOpen.slice(0, closeMatch.index).trim();
}

function injectManagedStyleBody(
  html: string,
  css: string,
  openRe: RegExp,
  attribute: string,
): string {
  const openMatch = openRe.exec(html);
  const trimmed = css.trim();
  const block = trimmed ? `<style ${attribute}>\n${trimmed}\n</style>` : "";
  if (openMatch) {
    const bodyStart = openMatch.index + openMatch[0].length;
    const afterOpen = html.slice(bodyStart);
    const closeMatch = /<\s*\/\s*style\b[^>]*>/i.exec(afterOpen);
    if (closeMatch) {
      const closeEnd = bodyStart + closeMatch.index + closeMatch[0].length;
      if (!block) {
        return (
          html.slice(0, openMatch.index) +
          html.slice(closeEnd).replace(/^\n/, "")
        );
      }
      return html.slice(0, openMatch.index) + block + html.slice(closeEnd);
    }
  }
  if (!block) return html;
  const headClose = /<\/head\s*>/gi;
  let close: RegExpExecArray | null = null;
  let match: RegExpExecArray | null;
  while ((match = headClose.exec(html)) !== null) close = match;
  const index = close?.index ?? -1;
  return index >= 0
    ? html.slice(0, index) + block + "\n" + html.slice(index)
    : block + "\n" + html;
}

function extractCssBlock(css: string, start: number): string | null {
  let depth = 1;
  let index = start;
  while (index < css.length && depth > 0) {
    if (css[index] === "{") depth++;
    else if (css[index] === "}") depth--;
    index++;
  }
  return depth === 0 ? css.slice(start, index - 1) : null;
}

function normalizeCssPropertyName(property: string): string {
  if (property.startsWith("--")) return property;
  return property.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}
