import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  findPrerenderTargets,
  validateNetlifyHeadersArtifact,
  validateStaticCacheContract,
} from "./guard-ssr-cache-artifact.ts";

const validHeaders = `# Generated by @agent-native/core deploy/netlify-static-headers.ts

/*
  Cache-Control: public, max-age=600, stale-while-revalidate=604800, stale-if-error=3600
  CDN-Cache-Control: public, max-age=600, stale-while-revalidate=604800, stale-if-error=3600
  Netlify-CDN-Cache-Control: public, durable, s-maxage=31536000, stale-while-revalidate=604800, stale-if-error=3600

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/_agent-native/*
  Cache-Control: no-cache, no-store
`;

describe("SSR static cache artifact guard", () => {
  it("recognizes the repository's prerendered Netlify apps", () => {
    const targets = findPrerenderTargets();
    assert.deepEqual(
      [...new Set(targets.map((target) => target.publishDir))].sort(),
      ["packages/docs/dist", "templates/clips/dist"],
    );
  });

  it("accepts the canonical generated header artifact", () => {
    assert.deepEqual(validateNetlifyHeadersArtifact(validHeaders), []);
  });

  it("rejects the platform default shell policy", () => {
    const findings = validateNetlifyHeadersArtifact(
      validHeaders.replace(
        "public, max-age=600, stale-while-revalidate=604800, stale-if-error=3600",
        "public, max-age=0, must-revalidate",
      ),
    );
    assert.ok(findings.length > 0);
  });

  it("accepts the explicit all-provider no-store override", () => {
    const disabledHeaders = validHeaders
      .replaceAll(
        "Cache-Control: public, max-age=600, stale-while-revalidate=604800, stale-if-error=3600",
        "Cache-Control: no-store",
      )
      .replaceAll(
        "CDN-Cache-Control: public, max-age=600, stale-while-revalidate=604800, stale-if-error=3600",
        "CDN-Cache-Control: no-store",
      )
      .replaceAll(
        "Netlify-CDN-Cache-Control: public, durable, s-maxage=31536000, stale-while-revalidate=604800, stale-if-error=3600",
        "Netlify-CDN-Cache-Control: no-store",
      );

    assert.deepEqual(validateNetlifyHeadersArtifact(disabledHeaders), []);
  });

  it("passes the checked-in source contract", () => {
    assert.deepEqual(validateStaticCacheContract(), []);
  });
});
