import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const GENERATED_NETLIFY_HEADERS_MARKER =
  "# Generated by @agent-native/core deploy/netlify-static-headers.ts";

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const PRERENDER_CONFIG_NAMES = new Set([
  "react-router.config.js",
  "react-router.config.mjs",
  "react-router.config.ts",
  "react-router.config.tsx",
]);
const SKIP_DIRS = new Set([
  ".git",
  ".next",
  ".nuxt",
  ".output",
  ".react-router",
  ".turbo",
  "build",
  "coverage",
  "corpus",
  "dist",
  "node_modules",
]);

export type StaticCacheFinding = {
  file: string;
  message: string;
};

export type PrerenderTarget = {
  configFile: string;
  netlifyFile: string;
  packageDir: string;
  publishDir: string;
};

function readFileSafe(file: string): string | null {
  return existsSync(file) ? readFileSync(file, "utf8") : null;
}

function walk(dir: string): string[] {
  const entries = readdirSync(dir, { withFileTypes: true });

  const files: string[] = [];
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const absolute = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walk(absolute));
    } else if (entry.isFile() && PRERENDER_CONFIG_NAMES.has(entry.name)) {
      files.push(absolute);
    }
  }
  return files;
}

export function findPrerenderTargets(root = REPO_ROOT): PrerenderTarget[] {
  const configs = [
    ...walk(path.join(root, "packages")),
    ...walk(path.join(root, "templates")),
  ];

  return configs.flatMap((configFile) => {
    const config = readFileSafe(configFile);
    if (!config || !/\bprerender\s*:/.test(config)) return [];

    const packageDir = path.dirname(configFile);
    const netlifyFile = path.join(packageDir, "netlify.toml");
    if (!existsSync(netlifyFile)) return [];

    const netlify = readFileSafe(netlifyFile) ?? "";
    const publishDir =
      netlify.match(/^\s*publish\s*=\s*"([^"]+)"\s*$/m)?.[1] ?? "";

    return [{ configFile, netlifyFile, packageDir, publishDir }];
  });
}

function blockAfterGeneratedMarker(
  contents: string,
  pathname: string,
): string | null {
  const generatedStart = contents.indexOf(GENERATED_NETLIFY_HEADERS_MARKER);
  if (generatedStart === -1) return null;
  const generated = contents.slice(generatedStart);
  const blockStart = generated.indexOf(`\n\n${pathname}\n`);
  if (blockStart === -1) return null;
  const nextBlock = generated.indexOf("\n\n", blockStart + 2);
  return generated.slice(
    blockStart,
    nextBlock === -1 ? generated.length : nextBlock,
  );
}

export function validateNetlifyHeadersArtifact(
  contents: string,
  file = "dist/_headers",
): StaticCacheFinding[] {
  const findings: StaticCacheFinding[] = [];
  const shell = blockAfterGeneratedMarker(contents, "/*");
  const assets = blockAfterGeneratedMarker(contents, "/assets/*");
  const internal = blockAfterGeneratedMarker(contents, "/_agent-native/*");

  if (!shell) {
    findings.push({
      file,
      message:
        "generated public shell header block is missing; static HTML/.data would use the platform default",
    });
  } else {
    const shellCacheControls = [
      "Cache-Control",
      "CDN-Cache-Control",
      "Netlify-CDN-Cache-Control",
    ].map((name) =>
      shell.match(new RegExp(`^\\s+${name}:\\s*(.+)$`, "m"))?.[1]?.trim(),
    );
    const allNoStore = shellCacheControls.every(
      (value) => value === "no-store",
    );
    const anyNoStore = shellCacheControls.some((value) => value === "no-store");

    if (allNoStore) {
      // This is the explicit AGENT_NATIVE_SSR_CACHE=off deployment policy.
      // It is intentionally different from the normal public SWR contract,
      // but every provider must still agree so one cache cannot serve stale
      // HTML after another provider has disabled caching.
    } else if (
      anyNoStore ||
      shellCacheControls.some(
        (value) =>
          !value ||
          !value.includes("public") ||
          !value.includes("stale-while-revalidate"),
      ) ||
      shell.includes("max-age=0") ||
      shell.includes("must-revalidate")
    ) {
      findings.push({
        file,
        message:
          "generated public shell headers must consistently use either public stale-while-revalidate or the explicit all-provider no-store override",
      });
    }
  }

  if (
    !assets ||
    !assets.includes("max-age=31536000") ||
    !assets.includes("immutable")
  ) {
    findings.push({
      file,
      message:
        "generated hashed asset headers must include one-year immutable caching",
    });
  }

  if (!internal || !internal.includes("no-store")) {
    findings.push({
      file,
      message:
        "generated /_agent-native headers must stay no-store and outside the public shell cache",
    });
  }

  return findings;
}

export function validateStaticCacheContract(
  root = REPO_ROOT,
  artifactDir = process.env.GUARD_SSR_CACHE_ARTIFACT_DIR,
): StaticCacheFinding[] {
  const findings: StaticCacheFinding[] = [];
  const helperFile = path.join(
    root,
    "packages/core/src/deploy/netlify-static-headers.ts",
  );
  const buildFile = path.join(root, "packages/core/src/deploy/build.ts");
  const helper = readFileSafe(helperFile);
  const build = readFileSafe(buildFile);

  if (!helper) {
    findings.push({
      file: "packages/core/src/deploy/netlify-static-headers.ts",
      message: "shared static header writer is missing",
    });
  } else {
    for (const required of [
      "resolveSsrCacheHeaders",
      "IMMUTABLE_ASSET_CACHE_CONTROL",
      "no-cache, no-store",
      GENERATED_NETLIFY_HEADERS_MARKER,
    ]) {
      if (!helper.includes(required)) {
        findings.push({
          file: "packages/core/src/deploy/netlify-static-headers.ts",
          message: `shared static header writer is missing ${JSON.stringify(required)}`,
        });
      }
    }
  }

  if (!build) {
    findings.push({
      file: "packages/core/src/deploy/build.ts",
      message: "shared Netlify build is missing",
    });
  } else {
    const redirectsIndex = build.indexOf(
      "writeSingleTemplateNetlifyRedirects(cwd)",
    );
    const headersIndex = build.indexOf(
      'writeNetlifyStaticHeaders(path.join(cwd, "dist"))',
    );
    if (
      redirectsIndex === -1 ||
      headersIndex === -1 ||
      headersIndex < redirectsIndex
    ) {
      findings.push({
        file: "packages/core/src/deploy/build.ts",
        message:
          "the Netlify build must generate static cache headers after the public files and redirects are assembled",
      });
    }
  }

  const targets = findPrerenderTargets(root);
  if (targets.length === 0) {
    findings.push({
      file: "packages/docs/react-router.config.ts",
      message: "no Netlify app with a prerender configuration was discovered",
    });
  }

  for (const target of targets) {
    const relativeConfig = path.relative(root, target.configFile);
    const relativeNetlify = path.relative(root, target.netlifyFile);
    const netlify = readFileSafe(target.netlifyFile) ?? "";
    if (!target.publishDir || !target.publishDir.endsWith("/dist")) {
      findings.push({
        file: relativeNetlify,
        message: "prerendered Netlify apps must publish a dist directory",
      });
    }
    if (!/NITRO_PRESET=netlify/.test(netlify) || !/\bbuild\b/.test(netlify)) {
      findings.push({
        file: relativeNetlify,
        message:
          "prerendered Netlify apps must run the shared Netlify build with NITRO_PRESET=netlify",
      });
    }
    if (!existsSync(path.join(target.packageDir, "package.json"))) {
      findings.push({
        file: relativeConfig,
        message: "prerender config has no package.json beside it",
      });
    }
  }

  if (artifactDir) {
    const absoluteArtifactDir = path.resolve(root, artifactDir);
    const target = targets.find(
      (candidate) =>
        path.resolve(root, candidate.publishDir) === absoluteArtifactDir,
    );
    if (!target) {
      findings.push({
        file: artifactDir,
        message:
          "artifact path is not the publish directory of a discovered prerendered Netlify app",
      });
    } else {
      const headersFile = path.join(absoluteArtifactDir, "_headers");
      const headers = readFileSafe(headersFile);
      if (headers === null) {
        findings.push({
          file: path.join(artifactDir, "_headers"),
          message:
            "built prerendered publish directory is missing _headers; refusing to publish platform-default caching",
        });
      } else {
        findings.push(...validateNetlifyHeadersArtifact(headers, headersFile));
      }
    }
  }

  return findings;
}

function main(): void {
  const findings = validateStaticCacheContract();
  if (findings.length > 0) {
    console.error(
      "guard:ssr-cache-artifact found cache contract violations:\n",
    );
    for (const finding of findings) {
      console.error(`- ${finding.file}: ${finding.message}`);
    }
    process.exitCode = 1;
    return;
  }

  console.log(
    "guard:ssr-cache-artifact: clean (runtime and prerendered Netlify shells share the public SWR policy).",
  );
}

if (
  process.argv[1] &&
  pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url
) {
  main();
}
