#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describeConfigFields } from "../packages/core/src/app-config/describe.js";

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);

const TARGET = path.join(REPO_ROOT, "docs", "environment-variables.md");
const BEGIN = "<!-- BEGIN GENERATED: declared-app-config -->";
const END = "<!-- END GENERATED: declared-app-config -->";

function formatDefault(value: unknown): string {
  if (value === undefined) return "—";
  return `\`${JSON.stringify(value)}\``;
}

function renderRows(header: string[], body: string[][]): string[] {
  const widths = header.map((_, column) =>
    Math.max(
      header[column].length,
      ...body.map((cells) => cells[column].length),
    ),
  );
  const line = (cells: string[]) =>
    `| ${cells.map((cell, column) => cell.padEnd(widths[column])).join(" | ")} |`;
  return [
    line(header),
    line(widths.map((width) => "-".repeat(width))),
    ...body.map(line),
  ];
}

function renderTable(): string {
  const fields = describeConfigFields();
  const rows = fields.map((field) => [
    `\`${field.path}\``,
    field.env.length ? field.env.map((key) => `\`${key}\``).join(", ") : "—",
    field.type,
    formatDefault(field.defaultValue),
    field.doc ?? "",
  ]);

  return [
    BEGIN,
    "",
    "<!-- Generated by `pnpm sync:config-docs`. Do not edit by hand. -->",
    "",
    "## Declared app configuration",
    "",
    "Every field below is server-only and set with `defineAppConfig()` from",
    "server code. The environment variable is a declared deployment alias for",
    "the same field, listed in the order it is consulted; app configuration",
    "wins over any of them. These fields are deliberately separate from the",
    "public `agent-native.config.ts` surface. Fields with no alias are settable",
    "only in code.",
    "",
    ...renderRows(
      ["Field", "Environment aliases", "Type", "Default", "Description"],
      rows,
    ),
    "",
    END,
  ].join("\n");
}

function main(): void {
  const check = process.argv.includes("--check");
  const source = readFileSync(TARGET, "utf8");
  const block = renderTable();

  const start = source.indexOf(BEGIN);
  const end = source.indexOf(END);

  let next: string;
  if (start === -1 || end === -1) {
    if (check) {
      console.error(
        `[sync-config-docs] ${path.relative(REPO_ROOT, TARGET)} has no generated block. Run \`pnpm sync:config-docs\`.`,
      );
      process.exit(1);
    }
    next = `${source.trimEnd()}\n\n${block}\n`;
  } else {
    if (end < start) {
      console.error(
        "[sync-config-docs] generated block markers are out of order.",
      );
      process.exit(2);
    }
    next = source.slice(0, start) + block + source.slice(end + END.length);
  }

  if (next === source) {
    console.log("[sync-config-docs] up to date");
    return;
  }
  if (check) {
    console.error(
      "[sync-config-docs] declared configuration docs are stale. Run `pnpm sync:config-docs`.",
    );
    process.exit(1);
  }
  writeFileSync(TARGET, next);
  console.log(
    `[sync-config-docs] wrote ${describeConfigFields().length} fields to ${path.relative(REPO_ROOT, TARGET)}`,
  );
}

main();
