#!/usr/bin/env node
/**
 * Materializes the on-disk copies of exported Agent-Native app skills and their
 * optional `references/*.md` files FROM the single source of truth:
 * `BUILT_IN_APP_SKILLS` in `packages/core/src/cli/skills.ts`.
 *
 * Plan's on-disk copies live in two location families per skill:
 *   1. `templates/plan/.agents/skills/<name>/<relPath>`
 *   2. `skills/<exported-dir>/<relPath>`
 *
 * Design's exported coding-agent skills live under `skills/<name>/<relPath>`,
 * then repo-local `.agents/skills/<name>` symlinks make them available in this
 * checkout, matching the way this repo exposes `visual-plan` and
 * `visual-recap`.
 *
 * The copies were previously hand-maintained and drifted from the constant.
 * This script mirrors `sync-plan-marketplace.ts` and `sync-workspace-core-skills.ts`:
 * it writes by default and validates with `--check`, failing with a clear
 * "Run: pnpm sync:plan-skills" message when the committed tree drifts.
 *
 * The SKILL.md body is written VERBATIM from the constant — including its own
 * frontmatter `name:` field — because separate tests assert byte-identity for
 * the Plan copies. The plugin bundle / corpus is generated by other scripts.
 */
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readlinkSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { BUILT_IN_APP_SKILLS } from "../packages/core/src/cli/skills.js";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, "..");

const planEntry = BUILT_IN_APP_SKILLS["visual-plans"];
const designEntry = BUILT_IN_APP_SKILLS.design;
const agentNativeEntry = BUILT_IN_APP_SKILLS["agent-native"];
const turnIntoAppEntry = BUILT_IN_APP_SKILLS["turn-into-app"];

type GeneratedSkill = {
  skill: string;
  body: string;
  references: Record<string, string>;
  targetDirs: string[];
};

const GENERATED_SKILLS: GeneratedSkill[] = [
  {
    skill: "an",
    body: agentNativeEntry.skillMarkdown,
    references: agentNativeEntry.extraFiles?.["an"] ?? {},
    targetDirs: [join("skills", "an")],
  },
  {
    skill: "visual-plan",
    body: planEntry.skillMarkdown,
    references: planEntry.extraFiles?.["visual-plan"] ?? {},
    targetDirs: [
      join("templates", "plan", ".agents", "skills", "visual-plan"),
      join("skills", "visual-plans"),
    ],
  },
  {
    skill: "visual-recap",
    body: planEntry.extraSkills?.["visual-recap"] ?? "",
    references: planEntry.extraFiles?.["visual-recap"] ?? {},
    targetDirs: [
      join("templates", "plan", ".agents", "skills", "visual-recap"),
      join("skills", "visual-recap"),
    ],
  },
  {
    skill: "visualize-repo",
    body: planEntry.extraSkills?.["visualize-repo"] ?? "",
    references: planEntry.extraFiles?.["visualize-repo"] ?? {},
    targetDirs: [
      join("templates", "plan", ".agents", "skills", "visualize-repo"),
      join("skills", "visualize-repo"),
    ],
  },
  {
    skill: "design-exploration",
    body: designEntry.skillMarkdown,
    references: designEntry.extraFiles?.["design-exploration"] ?? {},
    targetDirs: [join("skills", "design-exploration")],
  },
  {
    skill: "visual-edit",
    body: designEntry.extraSkills?.["visual-edit"] ?? "",
    references: designEntry.extraFiles?.["visual-edit"] ?? {},
    targetDirs: [
      join("skills", "visual-edit"),
      join("templates", "design", ".agents", "skills", "visual-edit"),
    ],
  },
  {
    skill: "turn-into-app",
    body: turnIntoAppEntry.skillMarkdown,
    references: turnIntoAppEntry.extraFiles?.["turn-into-app"] ?? {},
    targetDirs: [join("skills", "turn-into-app")],
  },
];

const check = process.argv.includes("--check");

type ExpectedFile = { rel: string; content: string };
type ExpectedSymlink = { rel: string; target: string };

const REPO_SKILL_SYMLINKS: ExpectedSymlink[] = [
  {
    rel: join(".agents", "skills", "an"),
    target: "../../skills/an",
  },
  {
    rel: join(".agents", "skills", "visual-plan"),
    target: "../../skills/visual-plans",
  },
  {
    rel: join(".agents", "skills", "visual-recap"),
    target: "../../skills/visual-recap",
  },
  {
    rel: join(".agents", "skills", "visualize-repo"),
    target: "../../skills/visualize-repo",
  },
  {
    rel: join(".agents", "skills", "design-exploration"),
    target: "../../skills/design-exploration",
  },
  {
    rel: join(".agents", "skills", "visual-edit"),
    target: "../../skills/visual-edit",
  },
  {
    rel: join(".agents", "skills", "turn-into-app"),
    target: "../../skills/turn-into-app",
  },
];

function skillRelPaths(
  skill: GeneratedSkill,
): { rel: string; content: string }[] {
  if (!skill.body) {
    throw new Error(
      `Missing SKILL.md body for exported app skill ${skill.skill}`,
    );
  }
  const files: { rel: string; content: string }[] = [
    { rel: "SKILL.md", content: skill.body },
  ];
  for (const rel of Object.keys(skill.references).sort()) {
    files.push({ rel, content: skill.references[rel] });
  }
  return files;
}

function targetDirs(skill: GeneratedSkill): string[] {
  return skill.targetDirs.map((dir) => join(rootDir, dir));
}

function expectedFiles(): ExpectedFile[] {
  const files: ExpectedFile[] = [];
  for (const skill of GENERATED_SKILLS) {
    const skillFiles = skillRelPaths(skill);
    for (const dir of targetDirs(skill)) {
      for (const { rel, content } of skillFiles) {
        files.push({ rel: relative(rootDir, join(dir, rel)), content });
      }
    }
  }
  return files;
}

function generateSymlinks(): void {
  for (const link of REPO_SKILL_SYMLINKS) {
    const abs = join(rootDir, link.rel);
    if (existsSync(abs)) {
      const stat = lstatSync(abs);
      if (stat.isSymbolicLink() && readlinkSync(abs) === link.target) {
        continue;
      }
      rmSync(abs, { recursive: true, force: true });
    }
    mkdirSync(dirname(abs), { recursive: true });
    symlinkSync(link.target, abs, "dir");
  }
}

function existingReferenceFiles(skillDir: string): string[] {
  const refDir = join(skillDir, "references");
  if (!existsSync(refDir)) return [];
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const dirEntry of readdirSync(dir, { withFileTypes: true })) {
      const abs = join(dir, dirEntry.name);
      if (dirEntry.isDirectory()) walk(abs);
      else if (dirEntry.isFile()) out.push(relative(rootDir, abs));
    }
  };
  walk(refDir);
  return out.sort();
}

function generate(files: ExpectedFile[]): void {
  const expectedSet = new Set(files.map((file) => file.rel));
  for (const skill of GENERATED_SKILLS) {
    for (const dir of targetDirs(skill)) {
      for (const rel of existingReferenceFiles(dir)) {
        if (!expectedSet.has(rel)) {
          rmSync(join(rootDir, rel), { force: true });
        }
      }
    }
  }

  for (const file of files) {
    const abs = join(rootDir, file.rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, file.content, "utf-8");
  }
  generateSymlinks();
}

function checkInSync(files: ExpectedFile[]): void {
  const expectedSet = new Set(files.map((file) => file.rel));

  const missing = files
    .filter((file) => !existsSync(join(rootDir, file.rel)))
    .map((file) => file.rel);
  const changed = files
    .filter((file) => existsSync(join(rootDir, file.rel)))
    .filter(
      (file) => readFileSync(join(rootDir, file.rel), "utf-8") !== file.content,
    )
    .map((file) => file.rel);

  const extra: string[] = [];
  for (const skill of GENERATED_SKILLS) {
    for (const dir of targetDirs(skill)) {
      for (const rel of existingReferenceFiles(dir)) {
        if (!expectedSet.has(rel)) extra.push(rel);
      }
    }
  }
  const badSymlinks = REPO_SKILL_SYMLINKS.filter((link) => {
    const abs = join(rootDir, link.rel);
    if (!existsSync(abs)) return true;
    const stat = lstatSync(abs);
    return !stat.isSymbolicLink() || readlinkSync(abs) !== link.target;
  }).map((link) => `${link.rel} -> ${link.target}`);

  if (
    missing.length === 0 &&
    extra.length === 0 &&
    changed.length === 0 &&
    badSymlinks.length === 0
  ) {
    return;
  }

  const sections: string[] = [];
  if (missing.length > 0)
    sections.push(`Missing:\n${missing.sort().join("\n")}`);
  if (extra.length > 0) sections.push(`Extra:\n${extra.sort().join("\n")}`);
  if (changed.length > 0)
    sections.push(`Changed:\n${changed.sort().join("\n")}`);
  if (badSymlinks.length > 0)
    sections.push(`Bad symlinks:\n${badSymlinks.sort().join("\n")}`);
  throw new Error(
    `Exported app skills are out of sync with BUILT_IN_APP_SKILLS.\n\n${sections.join(
      "\n\n",
    )}\n\nRun: pnpm sync:plan-skills`,
  );
}

function main(): void {
  const files = expectedFiles();
  if (check) {
    checkInSync(files);
    console.log("Exported app skills are in sync with skills.ts constants.");
  } else {
    generate(files);
    checkInSync(files);
    console.log("Synced exported app skills from skills.ts constants.");
  }
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
