import fs from "node:fs";
import path from "node:path";

import { normalizeAppBasePath } from "../server/app-base-path.js";
import { resolveSsrCacheHeaders } from "../shared/cache-control.js";
import { normalizeFrameworkRoutePrefix } from "../shared/framework-route-prefix.js";
import { IMMUTABLE_ASSET_CACHE_CONTROL } from "./immutable-assets.js";

export const GENERATED_NETLIFY_HEADERS_MARKER =
  "# Generated by @agent-native/core deploy/netlify-static-headers.ts";

const LEGACY_GENERATED_NETLIFY_HEADERS_MARKER =
  "# Generated by @agent-native/docs scripts/generate-netlify-headers.ts";

type HeaderEntries = ReadonlyArray<readonly [string, string]>;

function renderHeaderBlock(pathname: string, headers: HeaderEntries): string {
  return [
    pathname,
    ...headers.map(([name, value]) => `  ${name}: ${value}`),
  ].join("\n");
}

function frameworkRoutePatterns(
  env: Record<string, string | undefined>,
): string[] {
  const prefix = normalizeFrameworkRoutePrefix(
    env.AGENT_NATIVE_CONFIG_RUNTIME_FRAMEWORK_ROUTE_PREFIX?.trim() || undefined,
    "AGENT_NATIVE_CONFIG_RUNTIME_FRAMEWORK_ROUTE_PREFIX",
  );
  const basePath = normalizeAppBasePath(
    env.VITE_APP_BASE_PATH || env.APP_BASE_PATH,
  );
  return basePath ? [`${prefix}/*`, `${basePath}${prefix}/*`] : [`${prefix}/*`];
}

export function renderNetlifyStaticHeaders(
  env: Record<string, string | undefined> = process.env,
): string {
  const ssrHeaders = resolveSsrCacheHeaders(env);
  const ssrHeaderEntries: HeaderEntries = [
    ["Cache-Control", ssrHeaders["cache-control"]],
    ["CDN-Cache-Control", ssrHeaders["cdn-cache-control"]],
    ["Netlify-CDN-Cache-Control", ssrHeaders["netlify-cdn-cache-control"]],
  ];
  const immutableAssetHeaders: HeaderEntries = [
    ["Cache-Control", IMMUTABLE_ASSET_CACHE_CONTROL],
    ["CDN-Cache-Control", IMMUTABLE_ASSET_CACHE_CONTROL],
    ["Netlify-CDN-Cache-Control", IMMUTABLE_ASSET_CACHE_CONTROL],
  ];
  const internalHeaders: HeaderEntries = [
    ["Cache-Control", "no-cache, no-store"],
    ["CDN-Cache-Control", "no-cache, no-store"],
    ["Netlify-CDN-Cache-Control", "no-cache, no-store"],
  ];

  return (
    [
      GENERATED_NETLIFY_HEADERS_MARKER,
      renderHeaderBlock("/*", ssrHeaderEntries),
      renderHeaderBlock("/assets/*", immutableAssetHeaders),
      ...frameworkRoutePatterns(env).map((pattern) =>
        renderHeaderBlock(pattern, internalHeaders),
      ),
    ].join("\n\n") + "\n"
  );
}

export function writeNetlifyStaticHeaders(
  publishDir: string,
  env: Record<string, string | undefined> = process.env,
): void {
  if (!fs.existsSync(publishDir)) {
    throw new Error(`Netlify publish directory does not exist: ${publishDir}`);
  }

  const headersPath = path.join(publishDir, "_headers");
  const existing = fs.existsSync(headersPath)
    ? fs.readFileSync(headersPath, "utf8").trim()
    : "";
  const generated = renderNetlifyStaticHeaders(env).trim();
  const generatedStart = [
    GENERATED_NETLIFY_HEADERS_MARKER,
    LEGACY_GENERATED_NETLIFY_HEADERS_MARKER,
  ]
    .map((marker) => existing.indexOf(marker))
    .filter((index) => index >= 0)
    .sort((a, b) => a - b)[0];
  const existingWithoutGenerated =
    generatedStart === undefined
      ? existing
      : existing.slice(0, generatedStart).trimEnd();
  const contents = existingWithoutGenerated
    ? `${existingWithoutGenerated}\n\n${generated}`
    : generated;

  fs.writeFileSync(headersPath, `${contents}\n`);
}
