import { execSync } from "node:child_process";
import { readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const designRoot = resolve(__dirname, "../../../..");
const bridgeDir = __dirname;
const generatedDir = join(designRoot, ".generated", "bridge");

const GENERATED_BANNER = `// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts
`;

async function compileBridge(srcFile: string): Promise<string> {
  const result = await esbuild.build({
    entryPoints: [srcFile],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2020",
    write: false,
    external: [],
  });

  if (result.errors.length > 0) {
    const msgs = await esbuild.formatMessages(result.errors, { kind: "error" });
    throw new Error(`esbuild error for ${srcFile}:\n${msgs.join("\n")}`);
  }

  const output = result.outputFiles[0];
  if (!output) throw new Error(`No output from esbuild for ${srcFile}`);
  return output.text;
}

function bridgeName(filename: string): string {
  return filename.replace(/\.bridge\.ts$/, "");
}

function generatedModuleSrc(name: string, compiled: string): string {
  const escaped = compiled
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
  return `${GENERATED_BANNER}
/** Compiled IIFE string for ${name}.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const ${camelCase(name)}BridgeScript: string = \`${escaped}\`;
`;
}

function camelCase(name: string): string {
  return name.replace(/[-_]([a-z])/g, (_, c: string) => c.toUpperCase());
}

async function runCodegen(): Promise<void> {
  const bridgeFiles = readdirSync(bridgeDir).filter((f) =>
    f.endsWith(".bridge.ts"),
  );

  if (bridgeFiles.length === 0) {
    console.log("[bridge/codegen] No *.bridge.ts files found.");
    return;
  }

  for (const filename of bridgeFiles) {
    const srcPath = join(bridgeDir, filename);
    const name = bridgeName(filename);
    const outPath = join(generatedDir, `${name}.generated.ts`);

    console.log(`[bridge/codegen] Compiling ${filename} ...`);
    const compiled = await compileBridge(srcPath);
    const src = generatedModuleSrc(name, compiled);
    writeFileSync(outPath, src, "utf-8");
    console.log(`[bridge/codegen] → .generated/bridge/${name}.generated.ts`);
  }

  try {
    execSync(`pnpm exec oxfmt .generated/bridge/`, {
      cwd: designRoot,
      stdio: "pipe",
    });
  } catch {
    // oxfmt not critical — formatting mismatches caught by CI linter, not here.
  }

  console.log("[bridge/codegen] Done.");
}

runCodegen().catch((err) => {
  console.error("[bridge/codegen] FAILED:", err);
  process.exit(1);
});
