import fs from "fs";
import path from "path";

import { loadEnv, type Plugin } from "vite";

import type { AgentNativeConfigInput } from "../config.js";
import { getWorkspaceCoreExports } from "../deploy/workspace-core.js";
import { findWorkspaceRoot } from "../scripts/utils.js";
import {
  readAgentsBundleFromFs,
  resolveAgentInstructionPaths,
  type WorkspaceAgentsSource,
} from "../server/agents-bundle.js";
import {
  createAgentNativeConfigContext,
  loadResolvedAgentNativeConfig,
} from "./agent-native-config-loader.js";

const VIRTUAL_ID = "virtual:agents-bundle";
const RESOLVED_ID = "\0" + VIRTUAL_ID;
const TEMPLATE_SKILLS_DIRS = [
  path.join(".agents", "skills"),
  path.join(".agent", "skills"),
] as const;

const FULL_RELOAD_COALESCE_MS = 500;

export interface AgentsBundlePluginOptions {
  agentNativeConfig?: AgentNativeConfigInput;
}

async function emitBundleModule(
  projectRoot: string,
  agentConfig: Awaited<ReturnType<typeof loadResolvedAgentNativeConfig>>,
): Promise<string> {
  let workspaceSource: WorkspaceAgentsSource | null = null;
  try {
    const ws = await getWorkspaceCoreExports(projectRoot);
    if (ws) {
      workspaceSource = {
        skillsDir: ws.skillsDir,
        agentsMdPath: ws.agentsMdPath,
        rootDir: ws.packageDir,
      };
    }
  } catch {
    // fall back to template-only
  }

  const bundle = readAgentsBundleFromFs(projectRoot, workspaceSource, {
    instructions: agentConfig.instructions,
  });
  return `// AUTO-GENERATED by @agent-native/core/vite/agents-bundle-plugin
// Contains the inlined AGENTS.md + .agents/skills/ content from the template,
// merged with any workspace AGENTS.md + .agents/skills/ when present.
const bundle = ${JSON.stringify(bundle)};
export default bundle;
`;
}

export function agentsBundlePlugin(
  options: AgentsBundlePluginOptions = {},
): Plugin {
  let projectRoot = "";
  let agentConfigPromise: ReturnType<typeof loadResolvedAgentNativeConfig> =
    Promise.resolve({});

  return {
    name: "agent-native-agents-bundle",

    async configResolved(config) {
      projectRoot = config.root;
      const mode = config.mode ?? "development";
      const workspaceRoot = findWorkspaceRoot(projectRoot);
      const environment = {
        ...(workspaceRoot && workspaceRoot !== projectRoot
          ? loadEnv(mode, workspaceRoot, "")
          : {}),
        ...loadEnv(mode, projectRoot, ""),
        ...process.env,
      };
      agentConfigPromise = loadResolvedAgentNativeConfig(
        projectRoot,
        createAgentNativeConfigContext(config.command, mode),
        {
          environment,
          loadProjectConfig: options.agentNativeConfig === undefined,
          projectConfig: options.agentNativeConfig,
        },
      );
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
      return null;
    },

    async load(id) {
      if (id !== RESOLVED_ID) return null;
      if (!projectRoot) projectRoot = process.cwd();
      return await emitBundleModule(projectRoot, await agentConfigPromise);
    },

    async configureServer(server) {
      const watcher = server.watcher;
      const agentConfig = await agentConfigPromise;
      const instructionPaths = resolveAgentInstructionPaths(
        agentConfig.instructions,
      );
      const instructionFiles = new Set(
        [instructionPaths.runtime, instructionPaths.development].map((file) =>
          path.resolve(projectRoot, file),
        ),
      );

      let workspaceAgentsMdPath: string | null = null;
      let workspaceSkillsDir: string | null = null;
      try {
        const ws = await getWorkspaceCoreExports(projectRoot);
        if (ws) {
          workspaceAgentsMdPath = ws.agentsMdPath;
          workspaceSkillsDir = ws.skillsDir;
        }
      } catch {
        // ignore
      }

      const shouldInvalidate = (file: string): boolean => {
        if (instructionFiles.has(path.resolve(file))) return true;

        const rel = path.relative(projectRoot, file);
        if (!rel.startsWith("..")) {
          if (rel === "AGENTS.md") return true;
          for (const skillsDir of TEMPLATE_SKILLS_DIRS) {
            if (rel.startsWith(skillsDir + path.sep)) return true;
          }
        }
        if (workspaceAgentsMdPath && file === workspaceAgentsMdPath) {
          return true;
        }
        if (
          workspaceSkillsDir &&
          file.startsWith(workspaceSkillsDir + path.sep)
        ) {
          return true;
        }
        return false;
      };

      let reloadTimer: ReturnType<typeof setTimeout> | null = null;
      const scheduleFullReload = () => {
        if (reloadTimer) clearTimeout(reloadTimer);
        reloadTimer = setTimeout(() => {
          reloadTimer = null;
          server.ws.send({ type: "full-reload" });
        }, FULL_RELOAD_COALESCE_MS);
      };
      server.httpServer?.once("close", () => {
        if (reloadTimer) clearTimeout(reloadTimer);
        reloadTimer = null;
      });

      const invalidate = (file: string) => {
        if (!shouldInvalidate(file)) return;
        const mod = server.moduleGraph.getModuleById(RESOLVED_ID);
        if (mod) {
          server.moduleGraph.invalidateModule(mod);
          scheduleFullReload();
        }
      };

      const agentsMdPath = path.join(projectRoot, "AGENTS.md");
      const skillsDirs = TEMPLATE_SKILLS_DIRS.map((rel) =>
        path.join(projectRoot, rel),
      );
      if (fs.existsSync(agentsMdPath)) watcher.add(agentsMdPath);
      for (const skillsDir of skillsDirs) {
        if (fs.existsSync(skillsDir)) watcher.add(skillsDir);
      }
      for (const instructionFile of instructionFiles) {
        if (fs.existsSync(instructionFile)) {
          watcher.add(instructionFile);
        } else {
          const parent = path.dirname(instructionFile);
          if (fs.existsSync(parent)) watcher.add(parent);
        }
      }
      if (workspaceAgentsMdPath && fs.existsSync(workspaceAgentsMdPath)) {
        watcher.add(workspaceAgentsMdPath);
      }
      if (workspaceSkillsDir && fs.existsSync(workspaceSkillsDir)) {
        watcher.add(workspaceSkillsDir);
      }

      watcher.on("change", invalidate);
      watcher.on("add", invalidate);
      watcher.on("unlink", invalidate);
    },
  };
}
