type ChatFirstPageMessages = Record<string, string>;

export const chatFirstPageTranslations: Record<string, ChatFirstPageMessages> =
  {
    "zh-TW": {
      chatFirstWorkspaceApps: "工作區應用程式",
      searchApps: "搜尋應用程式",
      searchAppsPlaceholder: "依名稱或描述搜尋",
      clearAppSearch: "清除搜尋",
      noAppsMatch: "沒有符合搜尋條件的應用程式",
      pinApp: "釘選此應用程式",
      unpinApp: "取消釘選此應用程式",
      appPinSaveFailed: "無法儲存應用程式釘選。",
      appPinSavedLocally: "應用程式釘選只儲存在此裝置上。",
      chatFirstCreateWorkspaceApp: "建立工作區應用程式",
      chatFirstOpenApp: "開啟 {{name}}",
      chatFirstAppsLoadError: "無法載入工作區應用程式",
      chatFirstNoWorkspaceApps: "尚無工作區應用程式。",
      chatFirstCreateApp: "建立應用程式",
      chatFirstRetry: "重試",
      chatFirstUnpinApp: "取消釘選此應用程式",
      chatFirstPinApp: "釘選此應用程式",
      chatFirstRemovePinned: "從釘選應用程式移除",
      chatFirstPinTop: "將應用程式釘選至頂端",
      chatFirstOpenSideSurfaces: "開啟側邊面板",
      chatFirstCloseTab: "關閉 {{name}}",
      chatFirstClose: "關閉",
      chatFirstCloseOthers: "關閉其他",
      chatFirstCloseToRight: "關閉右側",
      chatFirstCloseAll: "全部關閉",
      chatFirstBrowserAgentHint: "請代理開啟網頁 URL。",
      chatFirstUnavailable: "此面板在此不可用。",
      chatFirstOpenActivity: "開啟活動",
      chatFirstDeferred: "延後",
      chatFirstSurfaceBrowserLabel: "瀏覽器",
      chatFirstSurfaceBrowserDescription: "開啟帶有網址列控制項的一般網頁。",
      chatFirstSurfaceBrowserReason: "請代理開啟網頁 URL。",
      chatFirstSurfaceTerminalLabel: "終端機",
      chatFirstSurfaceTerminalDescription: "在對話旁執行指令。",
      chatFirstSurfaceTerminalReason:
        "本版本延後：現有終端機是獨立主機介面；嵌入面板需要共用 PTY 生命週期。",
      chatFirstSurfaceFilesLabel: "檔案",
      chatFirstSurfaceFilesDescription: "瀏覽目前工作區樹狀結構。",
      chatFirstSurfaceFilesReason:
        "本版本延後：共用面板合約尚未在兩個用戶端提供受限工作區樹。",
      chatFirstSurfaceDiffLabel: "差異",
      chatFirstSurfaceDiffDescription: "檢視目前變更集。",
      chatFirstSurfaceDiffReason:
        "本版本延後：差異區塊仍可在聊天中使用，直到定義共用變更檔案來源。",
      chatFirstSurfaceSideChatLabel: "側邊聊天",
      chatFirstSurfaceSideChatDescription:
        "在主聊天旁監看並傳送訊息給另一個工作階段。",
      chatFirstSurfaceAgentsLabel: "代理",
      chatFirstSurfaceAgentsDescription:
        "檢視代理工作階段，並在對話旁監看一個工作階段。",
      chatFirstSurfaceSideChatReason: "從任何聊天列選擇「監看並傳送訊息」。",
      chatFirstSurfaceAgentsReason: "檢視最近的執行，或在此對話旁監看一個。",
      chatFirstAppView: "情境應用程式檢視",
      chatFirstContextualView: "情境檢視 · {{view}}",
      chatFirstWorkspaceApp: "工作區應用程式",
      chatFirstCloseAppPane: "關閉應用程式面板",
      chatFirstAppUnavailable: "此工作區應用程式已不存在。",
      chatFirstLoadingApp: "正在載入應用程式",
      chatFirstBrowserBack: "返回",
      chatFirstBrowserForward: "前進",
      chatFirstBrowserReload: "重新載入頁面",
      chatFirstBrowserAddress: "瀏覽器網址",
      chatFirstBrowserOpenExternal: "在外部瀏覽器開啟",
      chatFirstBrowserClose: "關閉瀏覽器",
      chatFirstBrowserPage: "瀏覽器頁面",
      chatFirstBrowserInvalidUrl: "請輸入完整的 http(s) 網址以導覽。",
      chatFirstWatchingSession: "正在觀看 {{name}}",
      chatFirstSession: "工作階段",
      chatFirstStopWatchingSession: "停止觀看工作階段",
      chatFirstStopWatching: "停止觀看",
      chatFirstWatchedSession: "觀看中的工作階段",
      chatFirstSessionMessagePlaceholder: "傳送訊息給此工作階段…",
      chatFirstAgentsTitle: "子代理",
      chatFirstUntitledAgentSession: "未命名代理工作階段",
      chatFirstAgentChatSession: "代理聊天工作階段",
    },
    "zh-CN": {
      chatFirstWorkspaceApps: "工作区应用",
      searchApps: "搜索应用",
      searchAppsPlaceholder: "按名称或描述搜索",
      clearAppSearch: "清除搜索",
      noAppsMatch: "没有匹配搜索的应用",
      pinApp: "固定此应用",
      unpinApp: "取消固定此应用",
      appPinSaveFailed: "无法保存应用固定设置。",
      appPinSavedLocally: "应用固定设置仅保存在此设备上。",
      chatFirstCreateWorkspaceApp: "创建工作区应用",
      chatFirstOpenApp: "打开 {{name}}",
      chatFirstAppsLoadError: "无法加载工作区应用",
      chatFirstNoWorkspaceApps: "尚无工作区应用。",
      chatFirstCreateApp: "创建应用",
      chatFirstRetry: "重试",
      chatFirstUnpinApp: "取消固定此应用",
      chatFirstPinApp: "固定此应用",
      chatFirstRemovePinned: "从固定应用中移除",
      chatFirstPinTop: "固定应用到顶部",
      chatFirstOpenSideSurfaces: "打开侧边面板",
      chatFirstCloseTab: "关闭 {{name}}",
      chatFirstClose: "关闭",
      chatFirstCloseOthers: "关闭其他",
      chatFirstCloseToRight: "关闭右侧",
      chatFirstCloseAll: "全部关闭",
      chatFirstBrowserAgentHint: "请让代理打开网页 URL。",
      chatFirstUnavailable: "此面板在此不可用。",
      chatFirstOpenActivity: "打开活动",
      chatFirstDeferred: "延后",
      chatFirstSurfaceBrowserLabel: "浏览器",
      chatFirstSurfaceBrowserDescription: "打开带地址栏控件的普通网页。",
      chatFirstSurfaceBrowserReason: "请让代理打开网页 URL。",
      chatFirstSurfaceTerminalLabel: "终端",
      chatFirstSurfaceTerminalDescription: "在对话旁运行命令。",
      chatFirstSurfaceTerminalReason:
        "本版本延后：现有终端是独立主机界面；嵌入面板需要共享 PTY 生命周期。",
      chatFirstSurfaceFilesLabel: "文件",
      chatFirstSurfaceFilesDescription: "浏览当前工作区树。",
      chatFirstSurfaceFilesReason:
        "本版本延后：共享面板契约尚未在两个客户端提供受限工作区树。",
      chatFirstSurfaceDiffLabel: "差异",
      chatFirstSurfaceDiffDescription: "查看当前变更集。",
      chatFirstSurfaceDiffReason:
        "本版本延后：差异块仍可在聊天中使用，直到定义共享变更文件来源。",
      chatFirstSurfaceSideChatLabel: "侧边聊天",
      chatFirstSurfaceSideChatDescription:
        "在主聊天旁监看并向另一个会话发送消息。",
      chatFirstSurfaceAgentsLabel: "代理",
      chatFirstSurfaceAgentsDescription:
        "查看代理会话，并在对话旁监看一个会话。",
      chatFirstSurfaceSideChatReason: "从任意聊天行选择“监看并发送消息”。",
      chatFirstSurfaceAgentsReason: "查看最近运行或在此对话旁监看一个。",
      chatFirstAppView: "上下文应用视图",
      chatFirstContextualView: "上下文视图 · {{view}}",
      chatFirstWorkspaceApp: "工作区应用",
      chatFirstCloseAppPane: "关闭应用面板",
      chatFirstAppUnavailable: "此工作区应用已不可用。",
      chatFirstLoadingApp: "正在加载应用",
      chatFirstBrowserBack: "返回",
      chatFirstBrowserForward: "前进",
      chatFirstBrowserReload: "重新加载页面",
      chatFirstBrowserAddress: "浏览器地址",
      chatFirstBrowserOpenExternal: "在外部浏览器中打开",
      chatFirstBrowserClose: "关闭浏览器",
      chatFirstBrowserPage: "浏览器页面",
      chatFirstBrowserInvalidUrl: "请输入完整的 http(s) URL 以导航。",
      chatFirstWatchingSession: "正在查看 {{name}}",
      chatFirstSession: "会话",
      chatFirstStopWatchingSession: "停止查看会话",
      chatFirstStopWatching: "停止查看",
      chatFirstWatchedSession: "查看中的会话",
      chatFirstSessionMessagePlaceholder: "向此会话发送消息…",
      chatFirstAgentsTitle: "子代理",
      chatFirstUntitledAgentSession: "未命名代理会话",
      chatFirstAgentChatSession: "代理聊天会话",
    },
    "es-ES": {
      chatFirstWorkspaceApps: "Apps del espacio de trabajo",
      searchApps: "Buscar apps",
      searchAppsPlaceholder: "Buscar por nombre o descripción",
      clearAppSearch: "Borrar búsqueda",
      noAppsMatch: "Ninguna app coincide con tu búsqueda",
      pinApp: "Fijar esta app",
      unpinApp: "Desfijar esta app",
      appPinSaveFailed: "No se pudieron guardar las apps fijadas.",
      appPinSavedLocally:
        "Las apps fijadas solo se guardan en este dispositivo.",
      chatFirstCreateWorkspaceApp: "Crear app del espacio de trabajo",
      chatFirstOpenApp: "Abrir {{name}}",
      chatFirstAppsLoadError:
        "No se pudieron cargar las apps del espacio de trabajo",
      chatFirstNoWorkspaceApps: "Aún no hay apps del espacio de trabajo.",
      chatFirstCreateApp: "Crear app",
      chatFirstRetry: "Reintentar",
      chatFirstUnpinApp: "Quitar fijación a esta app",
      chatFirstPinApp: "Fijar esta app",
      chatFirstRemovePinned: "Quitar de las apps fijadas",
      chatFirstPinTop: "Fijar app arriba",
      chatFirstOpenSideSurfaces: "Abrir paneles laterales",
      chatFirstCloseTab: "Cerrar {{name}}",
      chatFirstClose: "Cerrar",
      chatFirstCloseOthers: "Cerrar otras",
      chatFirstCloseToRight: "Cerrar a la derecha",
      chatFirstCloseAll: "Cerrar todo",
      chatFirstBrowserAgentHint: "Pide al agente que abra una URL web.",
      chatFirstUnavailable: "Esta superficie no está disponible aquí.",
      chatFirstOpenActivity: "Abrir actividad",
      chatFirstDeferred: "Pospuesto",
      chatFirstSurfaceBrowserLabel: "Navegador",
      chatFirstSurfaceBrowserDescription:
        "Abre una página web normal con controles de dirección.",
      chatFirstSurfaceBrowserReason: "Pide al agente que abra una URL web.",
      chatFirstSurfaceTerminalLabel: "Terminal",
      chatFirstSurfaceTerminalDescription:
        "Ejecuta comandos junto a la conversación.",
      chatFirstSurfaceTerminalReason:
        "Pospuesto en esta versión: el terminal actual es una superficie independiente; el panel integrado necesita un ciclo de vida PTY compartido.",
      chatFirstSurfaceFilesLabel: "Archivos",
      chatFirstSurfaceFilesDescription:
        "Explora el árbol del espacio de trabajo activo.",
      chatFirstSurfaceFilesReason:
        "Pospuesto en esta versión: el contrato compartido aún no expone un árbol de espacio de trabajo acotado en ambos clientes.",
      chatFirstSurfaceDiffLabel: "Diferencias",
      chatFirstSurfaceDiffDescription: "Revisa el conjunto de cambios actual.",
      chatFirstSurfaceDiffReason:
        "Pospuesto en esta versión: los bloques de diferencias siguen disponibles en el chat mientras se define una fuente compartida de archivos modificados.",
      chatFirstSurfaceSideChatLabel: "Chat lateral",
      chatFirstSurfaceSideChatDescription:
        "Observa y escribe a otra sesión junto al chat principal.",
      chatFirstSurfaceAgentsLabel: "Agentes",
      chatFirstSurfaceAgentsDescription:
        "Revisa sesiones de agentes y observa una junto a la conversación.",
      chatFirstSurfaceSideChatReason:
        "Elige Observar y escribir desde cualquier fila de chat.",
      chatFirstSurfaceAgentsReason:
        "Revisa ejecuciones recientes u observa una junto a esta conversación.",
      chatFirstAppView: "Vista contextual de la app",
      chatFirstContextualView: "Vista contextual · {{view}}",
      chatFirstWorkspaceApp: "App del espacio de trabajo",
      chatFirstCloseAppPane: "Cerrar panel de la app",
      chatFirstAppUnavailable:
        "Esta app del espacio de trabajo ya no está disponible.",
      chatFirstLoadingApp: "Cargando app",
      chatFirstBrowserBack: "Atrás",
      chatFirstBrowserForward: "Adelante",
      chatFirstBrowserReload: "Recargar página",
      chatFirstBrowserAddress: "Dirección del navegador",
      chatFirstBrowserOpenExternal: "Abrir en el navegador externo",
      chatFirstBrowserClose: "Cerrar navegador",
      chatFirstBrowserPage: "Página del navegador",
      chatFirstBrowserInvalidUrl:
        "Introduce una URL http(s) completa para navegar.",
      chatFirstWatchingSession: "Viendo {{name}}",
      chatFirstSession: "sesión",
      chatFirstStopWatchingSession: "Dejar de ver la sesión",
      chatFirstStopWatching: "Dejar de ver",
      chatFirstWatchedSession: "Sesión observada",
      chatFirstSessionMessagePlaceholder: "Envía un mensaje a esta sesión…",
      chatFirstAgentsTitle: "Subagentes",
      chatFirstUntitledAgentSession: "Sesión de agente sin título",
      chatFirstAgentChatSession: "Sesión de chat del agente",
    },
    "fr-FR": {
      chatFirstWorkspaceApps: "Applications de l’espace de travail",
      searchApps: "Rechercher des applications",
      searchAppsPlaceholder: "Rechercher par nom ou description",
      clearAppSearch: "Effacer la recherche",
      noAppsMatch: "Aucune application ne correspond à votre recherche",
      pinApp: "Épingler cette application",
      unpinApp: "Désépingler cette application",
      appPinSaveFailed: "Impossible d’enregistrer les applications épinglées.",
      appPinSavedLocally:
        "Les applications épinglées sont enregistrées uniquement sur cet appareil.",
      chatFirstCreateWorkspaceApp: "Créer une application d’espace de travail",
      chatFirstOpenApp: "Ouvrir {{name}}",
      chatFirstAppsLoadError:
        "Impossible de charger les applications de l’espace de travail",
      chatFirstNoWorkspaceApps:
        "Aucune application d’espace de travail pour le moment.",
      chatFirstCreateApp: "Créer une application",
      chatFirstRetry: "Réessayer",
      chatFirstUnpinApp: "Désépingler cette application",
      chatFirstPinApp: "Épingler cette application",
      chatFirstRemovePinned: "Retirer des applications épinglées",
      chatFirstPinTop: "Épingler l’application en haut",
      chatFirstOpenSideSurfaces: "Ouvrir les panneaux latéraux",
      chatFirstCloseTab: "Fermer {{name}}",
      chatFirstClose: "Fermer",
      chatFirstCloseOthers: "Fermer les autres",
      chatFirstCloseToRight: "Fermer à droite",
      chatFirstCloseAll: "Tout fermer",
      chatFirstBrowserAgentHint: "Demandez à l’agent d’ouvrir une URL web.",
      chatFirstUnavailable: "Cette surface n’est pas disponible ici.",
      chatFirstOpenActivity: "Ouvrir l’activité",
      chatFirstDeferred: "Différé",
      chatFirstSurfaceBrowserLabel: "Navigateur",
      chatFirstSurfaceBrowserDescription:
        "Ouvrir une page web avec les contrôles de la barre d’adresse.",
      chatFirstSurfaceBrowserReason: "Demandez à l’agent d’ouvrir une URL web.",
      chatFirstSurfaceTerminalLabel: "Terminal",
      chatFirstSurfaceTerminalDescription:
        "Exécuter des commandes à côté de la conversation.",
      chatFirstSurfaceTerminalReason:
        "Différé dans cette version : le terminal actuel est une surface hôte autonome ; un panneau intégré nécessite un cycle de vie PTY partagé.",
      chatFirstSurfaceFilesLabel: "Fichiers",
      chatFirstSurfaceFilesDescription:
        "Parcourir l’arborescence de l’espace de travail actif.",
      chatFirstSurfaceFilesReason:
        "Différé dans cette version : le contrat partagé n’expose pas encore une arborescence d’espace de travail bornée dans les deux clients.",
      chatFirstSurfaceDiffLabel: "Diff",
      chatFirstSurfaceDiffDescription:
        "Examiner l’ensemble de modifications actuel.",
      chatFirstSurfaceDiffReason:
        "Différé dans cette version : les blocs diff restent disponibles dans le chat pendant la définition d’une source partagée de fichiers modifiés.",
      chatFirstSurfaceSideChatLabel: "Chat latéral",
      chatFirstSurfaceSideChatDescription:
        "Suivre et écrire à une autre session à côté du chat principal.",
      chatFirstSurfaceAgentsLabel: "Agents",
      chatFirstSurfaceAgentsDescription:
        "Examiner les sessions d’agents et en suivre une à côté de la conversation.",
      chatFirstSurfaceSideChatReason:
        "Choisissez Suivre et écrire depuis une ligne de chat.",
      chatFirstSurfaceAgentsReason:
        "Examinez les exécutions récentes ou suivez-en une à côté de cette conversation.",
      chatFirstAppView: "Vue contextuelle de l’application",
      chatFirstContextualView: "Vue contextuelle · {{view}}",
      chatFirstWorkspaceApp: "Application d’espace de travail",
      chatFirstCloseAppPane: "Fermer le panneau de l’application",
      chatFirstAppUnavailable:
        "Cette application d’espace de travail n’est plus disponible.",
      chatFirstLoadingApp: "Chargement de l’application",
      chatFirstBrowserBack: "Retour",
      chatFirstBrowserForward: "Suivant",
      chatFirstBrowserReload: "Recharger la page",
      chatFirstBrowserAddress: "Adresse du navigateur",
      chatFirstBrowserOpenExternal: "Ouvrir dans le navigateur externe",
      chatFirstBrowserClose: "Fermer le navigateur",
      chatFirstBrowserPage: "Page du navigateur",
      chatFirstBrowserInvalidUrl:
        "Saisissez une URL http(s) complète pour naviguer.",
      chatFirstWatchingSession: "Session suivie : {{name}}",
      chatFirstSession: "session",
      chatFirstStopWatchingSession: "Arrêter de suivre la session",
      chatFirstStopWatching: "Arrêter le suivi",
      chatFirstWatchedSession: "Session suivie",
      chatFirstSessionMessagePlaceholder: "Envoyer un message à cette session…",
      chatFirstAgentsTitle: "Sous-agents",
      chatFirstUntitledAgentSession: "Session d’agent sans titre",
      chatFirstAgentChatSession: "Session de chat de l’agent",
    },
    "de-DE": {
      chatFirstWorkspaceApps: "Arbeitsbereich-Apps",
      searchApps: "Apps durchsuchen",
      searchAppsPlaceholder: "Nach Name oder Beschreibung suchen",
      clearAppSearch: "Suche löschen",
      noAppsMatch: "Keine Apps entsprechen deiner Suche",
      pinApp: "Diese App anheften",
      unpinApp: "Diese App loslösen",
      appPinSaveFailed: "App-Anheftungen konnten nicht gespeichert werden.",
      appPinSavedLocally:
        "App-Anheftungen werden nur auf diesem Gerät gespeichert.",
      chatFirstCreateWorkspaceApp: "Arbeitsbereich-App erstellen",
      chatFirstOpenApp: "{{name}} öffnen",
      chatFirstAppsLoadError:
        "Arbeitsbereich-Apps konnten nicht geladen werden",
      chatFirstNoWorkspaceApps: "Noch keine Arbeitsbereich-Apps.",
      chatFirstCreateApp: "App erstellen",
      chatFirstRetry: "Erneut versuchen",
      chatFirstUnpinApp: "Diese App loslösen",
      chatFirstPinApp: "Diese App anheften",
      chatFirstRemovePinned: "Aus angehefteten Apps entfernen",
      chatFirstPinTop: "App oben anheften",
      chatFirstOpenSideSurfaces: "Seitenflächen öffnen",
      chatFirstCloseTab: "{{name}} schließen",
      chatFirstClose: "Schließen",
      chatFirstCloseOthers: "Andere schließen",
      chatFirstCloseToRight: "Nach rechts schließen",
      chatFirstCloseAll: "Alle schließen",
      chatFirstBrowserAgentHint: "Bitte den Agenten, eine Web-URL zu öffnen.",
      chatFirstUnavailable: "Diese Fläche ist hier nicht verfügbar.",
      chatFirstOpenActivity: "Aktivität öffnen",
      chatFirstDeferred: "Zurückgestellt",
      chatFirstSurfaceBrowserLabel: "Browser",
      chatFirstSurfaceBrowserDescription:
        "Eine normale Webseite mit Adressleisten-Steuerung öffnen.",
      chatFirstSurfaceBrowserReason:
        "Bitte den Agenten, eine Web-URL zu öffnen.",
      chatFirstSurfaceTerminalLabel: "Terminal",
      chatFirstSurfaceTerminalDescription:
        "Befehle neben der Unterhaltung ausführen.",
      chatFirstSurfaceTerminalReason:
        "In dieser Version zurückgestellt: Das vorhandene Terminal ist eine eigenständige Host-Fläche; ein eingebettetes Panel benötigt einen gemeinsamen PTY-Lebenszyklus.",
      chatFirstSurfaceFilesLabel: "Dateien",
      chatFirstSurfaceFilesDescription:
        "Den aktiven Arbeitsbereich-Baum durchsuchen.",
      chatFirstSurfaceFilesReason:
        "In dieser Version zurückgestellt: Der gemeinsame Flächenvertrag stellt in beiden Clients noch keinen begrenzten Arbeitsbereich-Baum bereit.",
      chatFirstSurfaceDiffLabel: "Diff",
      chatFirstSurfaceDiffDescription: "Den aktuellen Änderungsstand prüfen.",
      chatFirstSurfaceDiffReason:
        "In dieser Version zurückgestellt: Diff-Blöcke bleiben im Chat verfügbar, während eine gemeinsame Quelle für geänderte Dateien definiert wird.",
      chatFirstSurfaceSideChatLabel: "Seitenchat",
      chatFirstSurfaceSideChatDescription:
        "Eine andere Sitzung neben dem Hauptchat beobachten und anschreiben.",
      chatFirstSurfaceAgentsLabel: "Agenten",
      chatFirstSurfaceAgentsDescription:
        "Agentensitzungen prüfen und eine neben der Unterhaltung beobachten.",
      chatFirstSurfaceSideChatReason:
        "Wähle Beobachten und anschreiben in einer Chatzeile.",
      chatFirstSurfaceAgentsReason:
        "Prüfe aktuelle Läufe oder beobachte einen neben dieser Unterhaltung.",
      chatFirstAppView: "Kontextuelle App-Ansicht",
      chatFirstContextualView: "Kontextuelle Ansicht · {{view}}",
      chatFirstWorkspaceApp: "Arbeitsbereich-App",
      chatFirstCloseAppPane: "App-Panel schließen",
      chatFirstAppUnavailable:
        "Diese Arbeitsbereich-App ist nicht mehr verfügbar.",
      chatFirstLoadingApp: "App wird geladen",
      chatFirstBrowserBack: "Zurück",
      chatFirstBrowserForward: "Vorwärts",
      chatFirstBrowserReload: "Seite neu laden",
      chatFirstBrowserAddress: "Browseradresse",
      chatFirstBrowserOpenExternal: "In externem Browser öffnen",
      chatFirstBrowserClose: "Browser schließen",
      chatFirstBrowserPage: "Browserseite",
      chatFirstBrowserInvalidUrl:
        "Gib zum Navigieren eine vollständige http(s)-URL ein.",
      chatFirstWatchingSession: "{{name}} wird beobachtet",
      chatFirstSession: "Sitzung",
      chatFirstStopWatchingSession: "Beobachtung der Sitzung beenden",
      chatFirstStopWatching: "Beobachtung beenden",
      chatFirstWatchedSession: "Beobachtete Sitzung",
      chatFirstSessionMessagePlaceholder: "Nachricht an diese Sitzung…",
      chatFirstAgentsTitle: "Subagenten",
      chatFirstUntitledAgentSession: "Unbenannte Agentensitzung",
      chatFirstAgentChatSession: "Agenten-Chat-Sitzung",
    },
    "ja-JP": {
      chatFirstWorkspaceApps: "ワークスペースアプリ",
      searchApps: "アプリを検索",
      searchAppsPlaceholder: "名前または説明で検索",
      clearAppSearch: "検索をクリア",
      noAppsMatch: "検索に一致するアプリはありません",
      pinApp: "このアプリを固定",
      unpinApp: "このアプリの固定を解除",
      appPinSaveFailed: "アプリの固定を保存できませんでした。",
      appPinSavedLocally: "アプリの固定はこのデバイスにのみ保存されます。",
      chatFirstCreateWorkspaceApp: "ワークスペースアプリを作成",
      chatFirstOpenApp: "{{name}}を開く",
      chatFirstAppsLoadError: "ワークスペースアプリを読み込めませんでした",
      chatFirstNoWorkspaceApps: "ワークスペースアプリはまだありません。",
      chatFirstCreateApp: "アプリを作成",
      chatFirstRetry: "再試行",
      chatFirstUnpinApp: "このアプリの固定を解除",
      chatFirstPinApp: "このアプリを固定",
      chatFirstRemovePinned: "固定アプリから削除",
      chatFirstPinTop: "アプリを上部に固定",
      chatFirstOpenSideSurfaces: "サイドサーフェスを開く",
      chatFirstCloseTab: "{{name}}を閉じる",
      chatFirstClose: "閉じる",
      chatFirstCloseOthers: "他を閉じる",
      chatFirstCloseToRight: "右側を閉じる",
      chatFirstCloseAll: "すべて閉じる",
      chatFirstBrowserAgentHint:
        "エージェントにウェブ URL を開くよう依頼します。",
      chatFirstUnavailable: "このサーフェスはここでは利用できません。",
      chatFirstOpenActivity: "アクティビティを開く",
      chatFirstDeferred: "保留中",
      chatFirstSurfaceBrowserLabel: "ブラウザー",
      chatFirstSurfaceBrowserDescription:
        "アドレスバー操作付きで通常のウェブページを開きます。",
      chatFirstSurfaceBrowserReason:
        "エージェントにウェブ URL を開くよう依頼します。",
      chatFirstSurfaceTerminalLabel: "ターミナル",
      chatFirstSurfaceTerminalDescription: "会話の横でコマンドを実行します。",
      chatFirstSurfaceTerminalReason:
        "このリリースでは保留中です。既存のターミナルは独立したホストサーフェスで、埋め込みには共有 PTY ライフサイクルが必要です。",
      chatFirstSurfaceFilesLabel: "ファイル",
      chatFirstSurfaceFilesDescription:
        "現在のワークスペースツリーを参照します。",
      chatFirstSurfaceFilesReason:
        "このリリースでは保留中です。共有サーフェス契約はまだ両クライアントに限定されたワークスペースツリーを公開していません。",
      chatFirstSurfaceDiffLabel: "差分",
      chatFirstSurfaceDiffDescription: "現在の変更セットを確認します。",
      chatFirstSurfaceDiffReason:
        "このリリースでは保留中です。共有の変更ファイルソースを定義するまで、差分ブロックはチャットで利用できます。",
      chatFirstSurfaceSideChatLabel: "サイドチャット",
      chatFirstSurfaceSideChatDescription:
        "メインチャットの横で別のセッションを監視し、メッセージを送ります。",
      chatFirstSurfaceAgentsLabel: "エージェント",
      chatFirstSurfaceAgentsDescription:
        "エージェントセッションを確認し、会話の横で監視します。",
      chatFirstSurfaceSideChatReason:
        "チャット行から「監視してメッセージ」を選択します。",
      chatFirstSurfaceAgentsReason:
        "最近の実行を確認するか、この会話の横で監視します。",
      chatFirstAppView: "コンテキストアプリビュー",
      chatFirstContextualView: "コンテキストビュー · {{view}}",
      chatFirstWorkspaceApp: "ワークスペースアプリ",
      chatFirstCloseAppPane: "アプリパネルを閉じる",
      chatFirstAppUnavailable:
        "このワークスペースアプリは利用できなくなりました。",
      chatFirstLoadingApp: "アプリを読み込み中",
      chatFirstBrowserBack: "戻る",
      chatFirstBrowserForward: "進む",
      chatFirstBrowserReload: "ページを再読み込み",
      chatFirstBrowserAddress: "ブラウザのアドレス",
      chatFirstBrowserOpenExternal: "外部ブラウザで開く",
      chatFirstBrowserClose: "ブラウザを閉じる",
      chatFirstBrowserPage: "ブラウザページ",
      chatFirstBrowserInvalidUrl:
        "移動するには完全な http(s) URL を入力してください。",
      chatFirstWatchingSession: "{{name}} を監視中",
      chatFirstSession: "セッション",
      chatFirstStopWatchingSession: "セッションの監視を停止",
      chatFirstStopWatching: "監視を停止",
      chatFirstWatchedSession: "監視中のセッション",
      chatFirstSessionMessagePlaceholder: "このセッションにメッセージを送信…",
      chatFirstAgentsTitle: "サブエージェント",
      chatFirstUntitledAgentSession: "無題のエージェントセッション",
      chatFirstAgentChatSession: "エージェントチャットセッション",
    },
    "ko-KR": {
      chatFirstWorkspaceApps: "워크스페이스 앱",
      searchApps: "앱 검색",
      searchAppsPlaceholder: "이름 또는 설명으로 검색",
      clearAppSearch: "검색 지우기",
      noAppsMatch: "검색 결과가 없습니다",
      pinApp: "이 앱 고정",
      unpinApp: "이 앱 고정 해제",
      appPinSaveFailed: "앱 고정을 저장하지 못했습니다.",
      appPinSavedLocally: "앱 고정은 이 기기에만 저장됩니다.",
      chatFirstCreateWorkspaceApp: "워크스페이스 앱 만들기",
      chatFirstOpenApp: "{{name}} 열기",
      chatFirstAppsLoadError: "워크스페이스 앱을 불러오지 못했습니다",
      chatFirstNoWorkspaceApps: "아직 워크스페이스 앱이 없습니다.",
      chatFirstCreateApp: "앱 만들기",
      chatFirstRetry: "다시 시도",
      chatFirstUnpinApp: "이 앱 고정 해제",
      chatFirstPinApp: "이 앱 고정",
      chatFirstRemovePinned: "고정된 앱에서 제거",
      chatFirstPinTop: "앱을 맨 위에 고정",
      chatFirstOpenSideSurfaces: "사이드 표면 열기",
      chatFirstCloseTab: "{{name}} 닫기",
      chatFirstClose: "닫기",
      chatFirstCloseOthers: "다른 항목 닫기",
      chatFirstCloseToRight: "오른쪽 닫기",
      chatFirstCloseAll: "모두 닫기",
      chatFirstBrowserAgentHint: "에이전트에게 웹 URL을 열도록 요청하세요.",
      chatFirstUnavailable: "이 표면은 여기에서 사용할 수 없습니다.",
      chatFirstOpenActivity: "활동 열기",
      chatFirstDeferred: "보류됨",
      chatFirstSurfaceBrowserLabel: "브라우저",
      chatFirstSurfaceBrowserDescription:
        "주소 표시줄 제어 기능이 있는 일반 웹 페이지를 엽니다.",
      chatFirstSurfaceBrowserReason: "에이전트에게 웹 URL을 열도록 요청하세요.",
      chatFirstSurfaceTerminalLabel: "터미널",
      chatFirstSurfaceTerminalDescription: "대화 옆에서 명령을 실행합니다.",
      chatFirstSurfaceTerminalReason:
        "이번 릴리스에서는 보류됩니다. 기존 터미널은 독립 호스트 표면이며, 임베드된 패널에는 공유 PTY 수명 주기가 필요합니다.",
      chatFirstSurfaceFilesLabel: "파일",
      chatFirstSurfaceFilesDescription: "현재 워크스페이스 트리를 탐색합니다.",
      chatFirstSurfaceFilesReason:
        "이번 릴리스에서는 보류됩니다. 공유 표면 계약은 아직 두 클라이언트에 제한된 워크스페이스 트리를 제공하지 않습니다.",
      chatFirstSurfaceDiffLabel: "Diff",
      chatFirstSurfaceDiffDescription: "현재 변경 세트를 검토합니다.",
      chatFirstSurfaceDiffReason:
        "이번 릴리스에서는 보류됩니다. 공유 변경 파일 소스를 정의하는 동안 Diff 블록은 채팅에서 계속 사용할 수 있습니다.",
      chatFirstSurfaceSideChatLabel: "사이드 채팅",
      chatFirstSurfaceSideChatDescription:
        "기본 채팅 옆에서 다른 세션을 보고 메시지를 보냅니다.",
      chatFirstSurfaceAgentsLabel: "에이전트",
      chatFirstSurfaceAgentsDescription:
        "에이전트 세션을 검토하고 대화 옆에서 하나를 봅니다.",
      chatFirstSurfaceSideChatReason:
        "채팅 행에서 ‘보고 메시지 보내기’를 선택하세요.",
      chatFirstSurfaceAgentsReason:
        "최근 실행을 검토하거나 이 대화 옆에서 하나를 보세요.",
      chatFirstAppView: "컨텍스트 앱 보기",
      chatFirstContextualView: "컨텍스트 보기 · {{view}}",
      chatFirstWorkspaceApp: "워크스페이스 앱",
      chatFirstCloseAppPane: "앱 패널 닫기",
      chatFirstAppUnavailable:
        "이 워크스페이스 앱은 더 이상 사용할 수 없습니다.",
      chatFirstLoadingApp: "앱 로드 중",
      chatFirstBrowserBack: "뒤로",
      chatFirstBrowserForward: "앞으로",
      chatFirstBrowserReload: "페이지 새로고침",
      chatFirstBrowserAddress: "브라우저 주소",
      chatFirstBrowserOpenExternal: "외부 브라우저에서 열기",
      chatFirstBrowserClose: "브라우저 닫기",
      chatFirstBrowserPage: "브라우저 페이지",
      chatFirstBrowserInvalidUrl: "이동하려면 전체 http(s) URL을 입력하세요.",
      chatFirstWatchingSession: "{{name}} 세션 보는 중",
      chatFirstSession: "세션",
      chatFirstStopWatchingSession: "세션 보기 중지",
      chatFirstStopWatching: "보기 중지",
      chatFirstWatchedSession: "보고 있는 세션",
      chatFirstSessionMessagePlaceholder: "이 세션에 메시지 보내기…",
      chatFirstAgentsTitle: "서브에이전트",
      chatFirstUntitledAgentSession: "제목 없는 에이전트 세션",
      chatFirstAgentChatSession: "에이전트 채팅 세션",
    },
    "pt-BR": {
      chatFirstWorkspaceApps: "Apps do espaço de trabalho",
      searchApps: "Pesquisar apps",
      searchAppsPlaceholder: "Pesquisar por nome ou descrição",
      clearAppSearch: "Limpar pesquisa",
      noAppsMatch: "Nenhum app corresponde à sua pesquisa",
      pinApp: "Fixar este app",
      unpinApp: "Desafixar este app",
      appPinSaveFailed: "Não foi possível salvar os apps fixados.",
      appPinSavedLocally:
        "Os apps fixados são salvos somente neste dispositivo.",
      chatFirstCreateWorkspaceApp: "Criar app do espaço de trabalho",
      chatFirstOpenApp: "Abrir {{name}}",
      chatFirstAppsLoadError:
        "Não foi possível carregar os apps do espaço de trabalho",
      chatFirstNoWorkspaceApps: "Ainda não há apps do espaço de trabalho.",
      chatFirstCreateApp: "Criar app",
      chatFirstRetry: "Tentar novamente",
      chatFirstUnpinApp: "Desafixar este app",
      chatFirstPinApp: "Fixar este app",
      chatFirstRemovePinned: "Remover dos apps fixados",
      chatFirstPinTop: "Fixar app no topo",
      chatFirstOpenSideSurfaces: "Abrir superfícies laterais",
      chatFirstCloseTab: "Fechar {{name}}",
      chatFirstClose: "Fechar",
      chatFirstCloseOthers: "Fechar outras",
      chatFirstCloseToRight: "Fechar à direita",
      chatFirstCloseAll: "Fechar tudo",
      chatFirstBrowserAgentHint: "Peça ao agente para abrir uma URL web.",
      chatFirstUnavailable: "Esta superfície não está disponível aqui.",
      chatFirstOpenActivity: "Abrir atividade",
      chatFirstDeferred: "Adiado",
      chatFirstSurfaceBrowserLabel: "Navegador",
      chatFirstSurfaceBrowserDescription:
        "Abra uma página web comum com controles da barra de endereço.",
      chatFirstSurfaceBrowserReason: "Peça ao agente para abrir uma URL web.",
      chatFirstSurfaceTerminalLabel: "Terminal",
      chatFirstSurfaceTerminalDescription:
        "Execute comandos ao lado da conversa.",
      chatFirstSurfaceTerminalReason:
        "Adiado nesta versão: o terminal existente é uma superfície de host independente; um painel integrado precisa de um ciclo de vida PTY compartilhado.",
      chatFirstSurfaceFilesLabel: "Arquivos",
      chatFirstSurfaceFilesDescription:
        "Navegue pela árvore do espaço de trabalho ativo.",
      chatFirstSurfaceFilesReason:
        "Adiado nesta versão: o contrato compartilhado ainda não expõe uma árvore de espaço de trabalho limitada nos dois clientes.",
      chatFirstSurfaceDiffLabel: "Diff",
      chatFirstSurfaceDiffDescription: "Revise o conjunto de alterações atual.",
      chatFirstSurfaceDiffReason:
        "Adiado nesta versão: os blocos de diff continuam disponíveis no chat enquanto uma fonte compartilhada de arquivos alterados é definida.",
      chatFirstSurfaceSideChatLabel: "Chat lateral",
      chatFirstSurfaceSideChatDescription:
        "Acompanhe e envie mensagens para outra sessão ao lado do chat principal.",
      chatFirstSurfaceAgentsLabel: "Agentes",
      chatFirstSurfaceAgentsDescription:
        "Revise sessões de agentes e acompanhe uma ao lado da conversa.",
      chatFirstSurfaceSideChatReason:
        "Escolha Acompanhar e enviar mensagem em qualquer linha de chat.",
      chatFirstSurfaceAgentsReason:
        "Revise execuções recentes ou acompanhe uma ao lado desta conversa.",
      chatFirstAppView: "Visão contextual do app",
      chatFirstContextualView: "Visão contextual · {{view}}",
      chatFirstWorkspaceApp: "App do espaço de trabalho",
      chatFirstCloseAppPane: "Fechar painel do app",
      chatFirstAppUnavailable:
        "Este app do espaço de trabalho não está mais disponível.",
      chatFirstLoadingApp: "Carregando app",
      chatFirstBrowserBack: "Voltar",
      chatFirstBrowserForward: "Avançar",
      chatFirstBrowserReload: "Recarregar página",
      chatFirstBrowserAddress: "Endereço do navegador",
      chatFirstBrowserOpenExternal: "Abrir no navegador externo",
      chatFirstBrowserClose: "Fechar navegador",
      chatFirstBrowserPage: "Página do navegador",
      chatFirstBrowserInvalidUrl:
        "Digite uma URL http(s) completa para navegar.",
      chatFirstWatchingSession: "Acompanhando {{name}}",
      chatFirstSession: "sessão",
      chatFirstStopWatchingSession: "Parar de acompanhar a sessão",
      chatFirstStopWatching: "Parar de acompanhar",
      chatFirstWatchedSession: "Sessão acompanhada",
      chatFirstSessionMessagePlaceholder: "Enviar mensagem para esta sessão…",
      chatFirstAgentsTitle: "Subagentes",
      chatFirstUntitledAgentSession: "Sessão de agente sem título",
      chatFirstAgentChatSession: "Sessão de chat do agente",
    },
    "hi-IN": {
      chatFirstWorkspaceApps: "वर्कस्पेस ऐप्स",
      searchApps: "ऐप्स खोजें",
      searchAppsPlaceholder: "नाम या विवरण से खोजें",
      clearAppSearch: "खोज साफ़ करें",
      noAppsMatch: "आपकी खोज से कोई ऐप मेल नहीं खाता",
      pinApp: "इस ऐप को पिन करें",
      unpinApp: "इस ऐप से पिन हटाएं",
      appPinSaveFailed: "ऐप पिन सहेजे नहीं जा सके।",
      appPinSavedLocally: "ऐप पिन केवल इस डिवाइस पर सहेजे गए हैं।",
      chatFirstCreateWorkspaceApp: "वर्कस्पेस ऐप बनाएँ",
      chatFirstOpenApp: "{{name}} खोलें",
      chatFirstAppsLoadError: "वर्कस्पेस ऐप्स लोड नहीं हो सके",
      chatFirstNoWorkspaceApps: "अभी कोई वर्कस्पेस ऐप नहीं है।",
      chatFirstCreateApp: "ऐप बनाएँ",
      chatFirstRetry: "पुनः प्रयास करें",
      chatFirstUnpinApp: "इस ऐप से पिन हटाएं",
      chatFirstPinApp: "इस ऐप को पिन करें",
      chatFirstRemovePinned: "पिन किए गए ऐप्स से हटाएँ",
      chatFirstPinTop: "ऐप को सबसे ऊपर पिन करें",
      chatFirstOpenSideSurfaces: "साइड पैनल खोलें",
      chatFirstCloseTab: "{{name}} बंद करें",
      chatFirstClose: "बंद करें",
      chatFirstCloseOthers: "अन्य बंद करें",
      chatFirstCloseToRight: "दाईं ओर बंद करें",
      chatFirstCloseAll: "सभी बंद करें",
      chatFirstBrowserAgentHint: "एजेंट से वेब URL खोलने को कहें।",
      chatFirstUnavailable: "यह सतह यहाँ उपलब्ध नहीं है।",
      chatFirstOpenActivity: "गतिविधि खोलें",
      chatFirstDeferred: "स्थगित",
      chatFirstSurfaceBrowserLabel: "ब्राउज़र",
      chatFirstSurfaceBrowserDescription:
        "एड्रेस बार नियंत्रणों के साथ सामान्य वेब पेज खोलें।",
      chatFirstSurfaceBrowserReason: "एजेंट से वेब URL खोलने को कहें।",
      chatFirstSurfaceTerminalLabel: "टर्मिनल",
      chatFirstSurfaceTerminalDescription: "बातचीत के साथ कमांड चलाएँ।",
      chatFirstSurfaceTerminalReason:
        "इस रिलीज़ में स्थगित: मौजूदा टर्मिनल एक अलग होस्ट सतह है; एम्बेडेड पैनल के लिए साझा PTY जीवनचक्र चाहिए।",
      chatFirstSurfaceFilesLabel: "फ़ाइलें",
      chatFirstSurfaceFilesDescription: "सक्रिय वर्कस्पेस ट्री ब्राउज़ करें।",
      chatFirstSurfaceFilesReason:
        "इस रिलीज़ में स्थगित: साझा सतह अनुबंध अभी दोनों क्लाइंट में सीमित वर्कस्पेस ट्री उपलब्ध नहीं कराता।",
      chatFirstSurfaceDiffLabel: "डिफ़",
      chatFirstSurfaceDiffDescription: "वर्तमान बदलावों की समीक्षा करें।",
      chatFirstSurfaceDiffReason:
        "इस रिलीज़ में स्थगित: साझा बदली हुई फ़ाइल स्रोत परिभाषित होने तक डिफ़ ब्लॉक चैट में उपलब्ध हैं।",
      chatFirstSurfaceSideChatLabel: "साइड चैट",
      chatFirstSurfaceSideChatDescription:
        "मुख्य चैट के साथ दूसरे सत्र को देखें और संदेश भेजें।",
      chatFirstSurfaceAgentsLabel: "एजेंट",
      chatFirstSurfaceAgentsDescription:
        "एजेंट सत्रों की समीक्षा करें और बातचीत के साथ एक देखें।",
      chatFirstSurfaceSideChatReason: "किसी भी चैट पंक्ति से देखें और संदेश भेजें चुनें।",
      chatFirstSurfaceAgentsReason:
        "हाल की रन की समीक्षा करें या इस बातचीत के साथ एक देखें।",
      chatFirstAppView: "संदर्भित ऐप दृश्य",
      chatFirstContextualView: "संदर्भित दृश्य · {{view}}",
      chatFirstWorkspaceApp: "वर्कस्पेस ऐप",
      chatFirstCloseAppPane: "ऐप पैनल बंद करें",
      chatFirstAppUnavailable: "यह वर्कस्पेस ऐप अब उपलब्ध नहीं है।",
      chatFirstLoadingApp: "ऐप लोड हो रहा है",
      chatFirstBrowserBack: "पीछे",
      chatFirstBrowserForward: "आगे",
      chatFirstBrowserReload: "पेज फिर लोड करें",
      chatFirstBrowserAddress: "ब्राउज़र पता",
      chatFirstBrowserOpenExternal: "बाहरी ब्राउज़र में खोलें",
      chatFirstBrowserClose: "ब्राउज़र बंद करें",
      chatFirstBrowserPage: "ब्राउज़र पेज",
      chatFirstBrowserInvalidUrl: "नेविगेट करने के लिए पूरा http(s) URL डालें।",
      chatFirstWatchingSession: "{{name}} देखा जा रहा है",
      chatFirstSession: "सेशन",
      chatFirstStopWatchingSession: "सेशन देखना बंद करें",
      chatFirstStopWatching: "देखना बंद करें",
      chatFirstWatchedSession: "देखा जा रहा सेशन",
      chatFirstSessionMessagePlaceholder: "इस सेशन को संदेश भेजें…",
      chatFirstAgentsTitle: "सबएजेंट",
      chatFirstUntitledAgentSession: "बिना नाम का एजेंट सेशन",
      chatFirstAgentChatSession: "एजेंट चैट सेशन",
    },
    "ar-SA": {
      chatFirstWorkspaceApps: "تطبيقات مساحة العمل",
      searchApps: "البحث عن التطبيقات",
      searchAppsPlaceholder: "البحث بالاسم أو الوصف",
      clearAppSearch: "مسح البحث",
      noAppsMatch: "لا توجد تطبيقات تطابق بحثك",
      pinApp: "تثبيت هذا التطبيق",
      unpinApp: "إلغاء تثبيت هذا التطبيق",
      appPinSaveFailed: "تعذر حفظ تثبيتات التطبيقات.",
      appPinSavedLocally: "تُحفظ تثبيتات التطبيقات على هذا الجهاز فقط.",
      chatFirstCreateWorkspaceApp: "إنشاء تطبيق مساحة عمل",
      chatFirstOpenApp: "فتح {{name}}",
      chatFirstAppsLoadError: "تعذر تحميل تطبيقات مساحة العمل",
      chatFirstNoWorkspaceApps: "لا توجد تطبيقات لمساحة العمل بعد.",
      chatFirstCreateApp: "إنشاء تطبيق",
      chatFirstRetry: "إعادة المحاولة",
      chatFirstUnpinApp: "إلغاء تثبيت هذا التطبيق",
      chatFirstPinApp: "تثبيت هذا التطبيق",
      chatFirstRemovePinned: "إزالة من التطبيقات المثبتة",
      chatFirstPinTop: "تثبيت التطبيق في الأعلى",
      chatFirstOpenSideSurfaces: "فتح الأسطح الجانبية",
      chatFirstCloseTab: "إغلاق {{name}}",
      chatFirstClose: "إغلاق",
      chatFirstCloseOthers: "إغلاق الآخرين",
      chatFirstCloseToRight: "إغلاق ما على اليمين",
      chatFirstCloseAll: "إغلاق الكل",
      chatFirstBrowserAgentHint: "اطلب من الوكيل فتح عنوان ويب.",
      chatFirstUnavailable: "هذا السطح غير متاح هنا.",
      chatFirstOpenActivity: "فتح النشاط",
      chatFirstDeferred: "مؤجل",
      chatFirstSurfaceBrowserLabel: "المتصفح",
      chatFirstSurfaceBrowserDescription:
        "فتح صفحة ويب عادية مع عناصر تحكم شريط العنوان.",
      chatFirstSurfaceBrowserReason: "اطلب من الوكيل فتح عنوان ويب.",
      chatFirstSurfaceTerminalLabel: "الطرفية",
      chatFirstSurfaceTerminalDescription: "تشغيل الأوامر بجانب المحادثة.",
      chatFirstSurfaceTerminalReason:
        "مؤجل في هذا الإصدار: الطرفية الحالية سطح مضيف مستقل؛ ويحتاج اللوح المضمن إلى دورة حياة PTY مشتركة.",
      chatFirstSurfaceFilesLabel: "الملفات",
      chatFirstSurfaceFilesDescription: "تصفح شجرة مساحة العمل النشطة.",
      chatFirstSurfaceFilesReason:
        "مؤجل في هذا الإصدار: لا يعرض عقد السطح المشترك شجرة مساحة عمل محدودة في كلا العميلين بعد.",
      chatFirstSurfaceDiffLabel: "الفروقات",
      chatFirstSurfaceDiffDescription: "مراجعة مجموعة التغييرات الحالية.",
      chatFirstSurfaceDiffReason:
        "مؤجل في هذا الإصدار: تظل كتل الفروقات متاحة في الدردشة ريثما يتم تعريف مصدر مشترك للملفات المتغيرة.",
      chatFirstSurfaceSideChatLabel: "دردشة جانبية",
      chatFirstSurfaceSideChatDescription:
        "راقب جلسة أخرى وأرسل إليها رسائل بجانب الدردشة الرئيسية.",
      chatFirstSurfaceAgentsLabel: "الوكلاء",
      chatFirstSurfaceAgentsDescription:
        "راجع جلسات الوكلاء وراقب جلسة بجانب المحادثة.",
      chatFirstSurfaceSideChatReason:
        "اختر المراقبة وإرسال رسالة من أي صف دردشة.",
      chatFirstSurfaceAgentsReason:
        "راجع عمليات التشغيل الأخيرة أو راقب واحدة بجانب هذه المحادثة.",
      chatFirstAppView: "عرض التطبيق السياقي",
      chatFirstContextualView: "عرض سياقي · {{view}}",
      chatFirstWorkspaceApp: "تطبيق مساحة العمل",
      chatFirstCloseAppPane: "إغلاق لوح التطبيق",
      chatFirstAppUnavailable: "لم يعد تطبيق مساحة العمل هذا متاحًا.",
      chatFirstLoadingApp: "جارٍ تحميل التطبيق",
      chatFirstBrowserBack: "رجوع",
      chatFirstBrowserForward: "تقدم",
      chatFirstBrowserReload: "إعادة تحميل الصفحة",
      chatFirstBrowserAddress: "عنوان المتصفح",
      chatFirstBrowserOpenExternal: "فتح في متصفح خارجي",
      chatFirstBrowserClose: "إغلاق المتصفح",
      chatFirstBrowserPage: "صفحة المتصفح",
      chatFirstBrowserInvalidUrl: "أدخل عنوان http(s) كاملًا للتنقل.",
      chatFirstWatchingSession: "تتم مشاهدة {{name}}",
      chatFirstSession: "جلسة",
      chatFirstStopWatchingSession: "إيقاف مشاهدة الجلسة",
      chatFirstStopWatching: "إيقاف المشاهدة",
      chatFirstWatchedSession: "الجلسة قيد المشاهدة",
      chatFirstSessionMessagePlaceholder: "إرسال رسالة إلى هذه الجلسة…",
      chatFirstAgentsTitle: "الوكلاء الفرعيون",
      chatFirstUntitledAgentSession: "جلسة وكيل بلا عنوان",
      chatFirstAgentChatSession: "جلسة دردشة الوكيل",
    },
  };
