import type { VideoProvider } from "./types.js";

export const googleMeetProvider: VideoProvider = {
  kind: "google_meet",
  label: "Google Meet",
  async createMeeting({ booking }) {
    // Meeting URL is generated by Google Calendar. If the consumer calls this
    // directly rather than via google_calendar.createEvent, return a
    // placeholder to signal that the event creation flow should handle it.
    return {
      meetingUrl: "",
      meetingId: `meet_${booking.uid}`,
    };
  },
};
