import { table, text, now } from "../db/schema.js";

export function ownableColumns() {
  return {
    ownerEmail: text("owner_email").notNull().default("local@localhost"),
    orgId: text("org_id"),
    visibility: text("visibility", {
      enum: ["private", "org", "public"],
    })
      .notNull()
      .default("private"),
  };
}

/**
 * Create a companion shares table for an ownable resource. Call this right
 * after defining the parent table.
 *
 * Columns:
 * - `id`              — share row id (generated by the share action)
 * - `resourceId`      — id of the parent resource
 * - `principalType`   — `'user' | 'group' | 'org'`
 * - `principalId`     — email (for user) or org id (for org)
 * - `role`            — `'viewer' | 'commenter' | 'editor' | 'admin'`
 * - `createdBy`       — email of the user who created the share
 * - `createdAt`       — ISO timestamp
 *
 * Uniqueness across `(resource_id, principal_type, principal_id)` is enforced
 * at the action layer via upsert-style logic. A composite DB-level unique
 * index can be added per template if desired — omitted here to keep the
 * factory uses the shared Postgres schema helpers.
 */
export function createSharesTable(tableName: string) {
  return table(tableName, {
    id: text("id").primaryKey(),
    resourceId: text("resource_id").notNull(),
    principalType: text("principal_type", {
      enum: ["user", "group", "org"],
    }).notNull(),
    principalId: text("principal_id").notNull(),
    role: text("role", {
      enum: ["viewer", "commenter", "editor", "admin"],
    })
      .notNull()
      .default("viewer"),
    createdBy: text("created_by").notNull().default(""),
    createdAt: text("created_at").notNull().default(now()),
    notifiedAt: text("notified_at"),
  });
}

export type Visibility = "private" | "org" | "public";
export type ShareRole = "viewer" | "commenter" | "editor" | "admin";
export type PrincipalType = "user" | "group" | "org";

export const ROLE_RANK: Record<ShareRole | "owner", number> = {
  viewer: 1,
  commenter: 2,
  editor: 3,
  admin: 4,
  owner: 5,
};

export function roleSatisfies(
  actual: ShareRole | "owner",
  minimum: ShareRole | "owner",
): boolean {
  return ROLE_RANK[actual] >= ROLE_RANK[minimum];
}
