/**
 * Convert a slide text object between plain lines and real UL/OL markup.
 *
 * Decks generated by the agent represent bullets as styled flex rows (see
 * `bullet-editing.ts`). Toolbar-created lists deliberately use semantic markup
 * instead, because an ordered list must renumber itself when items are added,
 * removed, or reordered, and styled rows cannot. Both shapes stay editable:
 * `RICH_BLOCK_TAGS` in SlideEditor already treats UL/OL/LI as text blocks.
 *
 * No React exports, so this stays Fast-Refresh friendly and unit-testable.
 */

import { isBulletMarker, isBulletRow } from "./bullet-editing";

export type SlideListKind = "bullet" | "ordered";

const LIST_TAG: Record<SlideListKind, "UL" | "OL"> = {
  bullet: "UL",
  ordered: "OL",
};

const LIST_STYLE: Record<SlideListKind, string> = {
  bullet:
    "margin:0;padding-left:1.25em;list-style-position:outside;list-style-type:disc;",
  ordered:
    "margin:0;padding-left:1.25em;list-style-position:outside;list-style-type:decimal;",
};

const ROW_TEXT_PROPERTY =
  /^(color|font(-.+)?|letter-spacing|word-spacing|line-height|text-(transform|shadow|decoration(-.+)?))$/;

const HEADING_TAG = /^H[1-6]$/;

const HEADING_TEXT_PROPERTIES = [
  "color",
  "font-family",
  "font-size",
  "font-style",
  "font-weight",
  "letter-spacing",
  "line-height",
  "text-transform",
] as const;

export type TextLook = [property: string, value: string][];

export function headingTextLook(element: Element): TextLook | null {
  if (!HEADING_TAG.test(element.tagName)) return null;
  const computed = element.ownerDocument.defaultView!.getComputedStyle(element);
  return HEADING_TEXT_PROPERTIES.map((property) => [
    property,
    computed.getPropertyValue(property),
  ]);
}

export function keepTextLook(target: HTMLElement, look: TextLook | null) {
  if (!look) return;
  const computed = target.ownerDocument.defaultView!.getComputedStyle(target);
  for (const [property, value] of look) {
    if (value && computed.getPropertyValue(property) !== value) {
      target.style.setProperty(property, value);
    }
  }
}

function isListTag(element: Element): boolean {
  return element.tagName === "UL" || element.tagName === "OL";
}

function listElement(element: HTMLElement): HTMLElement | null {
  if (isListTag(element)) return element;
  const children = Array.from(element.children);
  return children.length === 1 && isListTag(children[0])
    ? (children[0] as HTMLElement)
    : null;
}

export function detectSlideListKind(
  element: HTMLElement | null,
): SlideListKind | null {
  const list = element ? listElement(element) : null;
  if (!list) return null;
  return list.tagName === "OL" ? "ordered" : "bullet";
}

function bulletRows(element: HTMLElement): HTMLElement[] {
  if (isListTag(element)) return [];
  return Array.from(element.children).filter(
    (child): child is HTMLElement =>
      child instanceof HTMLElement && isBulletRow(child),
  );
}

export function activeSlideListKind(
  element: HTMLElement | null,
): SlideListKind | null {
  if (!element) return null;
  return (
    detectSlideListKind(element) ??
    (bulletRows(element).length > 0 ? "bullet" : null)
  );
}

function retag(element: HTMLElement, tagName: string): HTMLElement {
  const replacement = element.ownerDocument.createElement(tagName);
  for (const attribute of Array.from(element.attributes)) {
    replacement.setAttribute(attribute.name, attribute.value);
  }
  replacement.append(...Array.from(element.childNodes));
  element.replaceWith(replacement);
  return replacement;
}

const BLOCK_TAGS = new Set([
  "ARTICLE",
  "BLOCKQUOTE",
  "DIV",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "H6",
  "LI",
  "OL",
  "P",
  "PRE",
  "SECTION",
  "UL",
]);

function blockChildren(source: HTMLElement): HTMLElement[] | null {
  const blocks: HTMLElement[] = [];
  for (const node of Array.from(source.childNodes)) {
    if (node.nodeType === Node.TEXT_NODE) {
      if ((node.textContent ?? "").trim()) return null;
      continue;
    }
    if (!(node instanceof HTMLElement)) continue;
    if (node.tagName === "BR") continue;
    if (!BLOCK_TAGS.has(node.tagName)) return null;
    blocks.push(node);
  }
  return blocks.length > 0 ? blocks : null;
}

interface Line {
  html: string;
  look: TextLook | null;
}

function readLines(source: HTMLElement): Line[] {
  const blocks = blockChildren(source);
  if (blocks) {
    return blocks.flatMap((block) =>
      lineHtml(block).map((html) => ({ html, look: headingTextLook(block) })),
    );
  }

  return source.innerHTML
    .split(/<br\s*\/?>/i)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((html) => ({ html, look: null }));
}

function lineHtml(block: HTMLElement): string[] {
  const stripped = block.cloneNode(true) as HTMLElement;
  for (const child of Array.from(stripped.children)) {
    if (isBulletMarker(child)) child.remove();
  }
  const html = stripped.innerHTML.trim();
  return html ? [html] : [];
}

function itemHtml(list: HTMLElement): string[] {
  return Array.from(list.children)
    .filter((child): child is HTMLElement => child instanceof HTMLElement)
    .map((item) => item.innerHTML);
}

export function createSlideList(
  doc: Document,
  kind: SlideListKind,
): HTMLElement {
  const list = doc.createElement(LIST_TAG[kind]);
  list.setAttribute("style", LIST_STYLE[kind]);
  return list;
}

function buildList(
  doc: Document,
  kind: SlideListKind,
  lines: string[],
): HTMLElement {
  const list = createSlideList(doc, kind);
  for (const line of lines) {
    const item = doc.createElement("li");
    item.innerHTML = line;
    list.appendChild(item);
  }
  return list;
}

function buildLines(doc: Document, lines: string[]): DocumentFragment {
  const fragment = doc.createDocumentFragment();
  for (const line of lines) {
    const block = doc.createElement("div");
    block.innerHTML = line;
    fragment.appendChild(block);
  }
  return fragment;
}

export function toggleSlideList(
  element: HTMLElement,
  kind: SlideListKind,
): HTMLElement | null {
  const doc = element.ownerDocument;
  const existing = listElement(element);

  if (!existing) {
    const rows = bulletRows(element);
    if (rows.length > 0) return toggleBulletRows(element, rows, kind);
    const lines = readLines(element);
    if (lines.length === 0) return null;
    const look = headingTextLook(element);
    const holder =
      element.tagName === "P" || look ? retag(element, "DIV") : element;
    const list = buildList(
      doc,
      kind,
      lines.map((line) => line.html),
    );
    holder.replaceChildren(list);
    keepTextLook(holder, look);
    Array.from(list.children).forEach((item, index) =>
      keepTextLook(item as HTMLElement, lines[index].look),
    );
    return holder;
  }

  const lines = itemHtml(existing);

  if (existing.tagName !== LIST_TAG[kind]) {
    const switched = retag(existing, LIST_TAG[kind]);
    switched.style.setProperty(
      "list-style-type",
      kind === "ordered" ? "decimal" : "disc",
    );
    return existing === element ? switched : element;
  }

  if (existing === element) {
    const unwrapped = retag(element, "DIV");
    unwrapped.replaceChildren(buildLines(doc, lines));
    unwrapped.style.removeProperty("padding-left");
    unwrapped.style.removeProperty("list-style-position");
    unwrapped.style.removeProperty("list-style-type");
    return unwrapped;
  }

  existing.replaceWith(buildLines(doc, lines));
  return element;
}

function toggleBulletRows(
  element: HTMLElement,
  rows: HTMLElement[],
  kind: SlideListKind,
): HTMLElement {
  if (kind === "bullet") {
    for (const row of rows) {
      const marker = row.firstElementChild;
      if (marker && isBulletMarker(marker)) marker.remove();
    }
    return element;
  }
  const runs: HTMLElement[][] = [];
  rows.forEach((row, index) => {
    if (index > 0 && rows[index - 1].nextElementSibling === row) {
      runs[runs.length - 1].push(row);
    } else {
      runs.push([row]);
    }
  });
  for (const run of runs) numberRows(element, run, kind);
  return element;
}

function numberRows(
  element: HTMLElement,
  rows: HTMLElement[],
  kind: SlideListKind,
) {
  const list = createSlideList(element.ownerDocument, kind);
  for (const row of rows) {
    const [line] = lineHtml(row);
    if (line === undefined) continue;
    const item = element.ownerDocument.createElement("li");
    item.innerHTML = line;
    for (let index = 0; index < row.style.length; index += 1) {
      const name = row.style.item(index);
      if (!ROW_TEXT_PROPERTY.test(name)) continue;
      item.style.setProperty(
        name,
        row.style.getPropertyValue(name),
        row.style.getPropertyPriority(name),
      );
    }
    list.append(item);
  }
  rows[0].before(list);
  for (const row of rows) row.remove();
}
